### ISSUE TITLE
workon_cwd:6: command not found: realpath

### ISSUE THREAD

**Issue by axiaoxin** [robbyrussell/oh-my-zsh#4079] opened 2015-06-23 02:29 UTC
I always open the virtualenv plugin,but I upgrade oh-my-zsh today, when I cd to a project dir, it tell me `workon_cwd:6: command not found: realpath`

**Comment by wiltzius** [comment] 2015-06-23 05:31
same. it is a bummer, i am going to try downgrading somehow.

**Comment by wiltzius** [comment] 2015-06-23 05:31
I'll note that if I ctrl-c it seems to recover fine, though.

**Comment by axiaoxin** [comment] 2015-06-23 05:35
it can not auto active the virtualenv

**Comment by diwu1989** [comment] 2015-06-23 05:56
hitting this one too

**Comment by wolfg1969** [comment] 2015-06-23 07:03
same. after upgrade.

**Comment by wernight** [comment] 2015-06-23 07:26
+1

**Comment by levchik** [comment] 2015-06-23 09:04
Same here

**Comment by gmeans** [comment] 2015-06-23 13:42
I had the same issue. @wernight 's workaround worked as well.

**Comment by AlanAlbuquerque** [comment] 2015-06-23 14:06
@wernight It worked for me, thanks.

**Comment by harrislapiroff** [comment] 2015-06-23 19:27
+1

**Comment by apjanke** [comment] 2015-06-23 20:13
Duplicate of #4030.
Fixed by #4025.
Caused by #3918.

Affects some non-OS X systems too, since `realpath` isn't standard everywhere.

**Comment by diwu1989** [comment] 2015-06-25 06:31
can someone fix or revert the offending commit?

**Comment by oskargicast** [comment] 2015-06-27 06:56
@axiaoxin You need to install realthpath requirement. If you are inside a devian based OS: sudo apt-get install realpath.

**Comment by wolfg1969** [comment] 2015-06-27 07:24
For Mac OS X:
```
brew tap iveney/mocha
brew install realpath
```

**Comment by SanketDG** [comment] 2015-06-27 10:23
@oskargicast It can't find `realpath` on Linux Mint 17.1.

**Comment by twz915** [comment] 2015-06-29 01:17
@wolfg1969 fixed, thanks, Mac 10.10

**Comment by diwu1989** [comment] 2015-06-29 17:42
installing realpath shouldn't be necessary, this used to work just fine before

**Comment by apjanke** [comment] 2015-06-29 23:09
Agreed. We shouldn't introduce dependencies on programs that aren't widely available by default unless they're really necessary. And in this case, it isn't; `zsh`'s own `:A` modifier flag does the same thing as `realpath`. (Try it out yourself: `ln -s /usr/share/man dummy; cd dummy; d="."; echo ${d:A}`.)

I've put in a PR using `:A` at #4106 that cleans this up. If any of you who are having this problem could test it out and comment on #4106, I'd appreciate it, and that would help get it merged quickly.

**Closed** 2015-07-06 16:32 UTC
