### ISSUE TITLE
Paste issues from putty

### ISSUE THREAD

**Issue by mathisen99** [robbyrussell/oh-my-zsh#8128] opened 2019-09-03 15:55 UTC
i cant paste into putty anymore without getting this error.
**bracketed-paste-magic:zle:47: not enough arguments for -U**

this does not happend with bash or just regulat zsh i have tested it. and i did remove all traces from oh-my-zsh before trying to re-install it but same thing happends again.
i deleted this before trying again.

**.oh-my-zsh
.zcompdump
.zsh-update
.zsh_history
.zshrc**

not sure where to look anymore. or what files i can provide to troubleshoot this.
can also add that i dont got physical access to this machine. 
VPS Debian (10) Buster

**Comment by Andreychik32** [comment] 2019-09-03 17:08
Yes, can confirm this on Debian 10 VPS using PuTTY with latest oh-my-zsh.

**Comment by Yuubari** [comment] 2019-09-03 21:40
Same error on FreeBSD (pasting using PuTTY).

**Comment by mathisen99** [comment] 2019-09-06 10:35
how do i change label to bug ? as this has been confirmed now on multiple devices. i also tried on diffrent computers same thing.

**Comment by kraml** [comment] 2019-09-11 07:10
I have this problem too on multiple systems, WSL, Arch Linux, OpenSUSE, they all have this problem.

**Comment by mcornella** [comment] 2019-09-11 13:46
Please everyone post your zsh versions. You can disable the [magic functions widgets by setting `DISABLE_MAGIC_FUNCTIONS=true`](https://github.com/robbyrussell/oh-my-zsh/blob/fd4571d1b02ac68833a5b5c166395434723b9128/lib/misc.zsh#L4) before sourcing ohmyzsh.

**Comment by Yuubari** [comment] 2019-09-11 14:26
My case:
```
% zsh --version
zsh 5.7.1 (amd64-portbld-freebsd12.0)
```
I have already disabled the magic functions for now, but paste interception is something I am very fold of and would like to have working again.

**Comment by Andreychik32** [comment] 2019-09-11 14:36
@mcornella, here it is:
```sh
~> zsh --version
zsh 5.7.1 (x86_64-debian-linux-gnu)
```

**Comment by mathisen99** [comment] 2019-09-11 15:02
> Please everyone post your zsh versions. You can disable the [magic functions widgets by setting `DISABLE_MAGIC_FUNCTIONS=true`](https://github.com/robbyrussell/oh-my-zsh/blob/fd4571d1b02ac68833a5b5c166395434723b9128/lib/misc.zsh#L4) before sourcing ohmyzsh.

➜  ~ zsh --version
zsh 5.7.1 (x86_64-debian-linux-gnu)

**Comment by kraml** [comment] 2019-09-12 00:53
Mine is zsh 5.7.1 too.

**Comment by AnyoeDove** [comment] 2019-09-16 16:11
Alpine Linux Edge(3.11_alpha20190809) with zsh 5.7.1 (x86_64-alpine-linux-musl)
Debian Buster 10.1 with zsh 5.7.1 (x86_64-debian-linux-gnu)

only happened in PuTTY 0.72.

**Comment by vkatochka** [comment] 2019-09-20 16:23
Same problem
putty Release 0.72 Build platform: 64-bit x86 Windows

> uname -a
Linux name 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

> lsb_release -a
Description:    Ubuntu 18.04.3 LTS

>  zsh --version
zsh 5.4.2 (x86_64-ubuntu-linux-gnu)

**Comment by mcornella** [comment] 2019-09-20 21:29
This happens from versions 5.3 onward due to commit https://github.com/zsh-users/zsh/commit/3594f55fc087c1272ec4a4f15f17dfb007a226ec#diff-e7b21246ded3cacd55cd188f312de4de overwriting [a quote of `$PASTED` in this line](https://github.com/zsh-users/zsh/commit/9cfd26bf10f530d746afadf3a04c4cf401fbbb9d#diff-e7b21246ded3cacd55cd188f312de4deR165).

I've passed on the issue to the Zsh maintainers so hopefully next version will ship the fix. Until that is patched and you use the next version you should keep the magic functions disabled or manually patch the `bracketed-paste-magic` function to add the quotes to the line I linked above. You can get the directory of the `bracketed-paste-magic` file with the following script:
```
for d ($fpath); do [[ -e $d/bracketed-paste-magic ]] && echo $d; done
```

Closing since this is ultimately an upstream issue.

**Closed by mcornella** 2019-09-20 21:29 UTC
Labels: Type: bug

**Comment by AnyoeDove** [comment] 2019-10-21 17:10
looks like the `bracketed-paste-magic` function works fine in PuTTY 0.73

**Comment by cloonix** [comment] 2019-11-06 12:55
> looks like the `bracketed-paste-magic` function works fine in PuTTY 0.73

Confirmed. Update to 0.73 solved this issue for me too.
