### ISSUE TITLE
Why my terminal so slow `cd` in a huge git repository

### ISSUE THREAD

**Issue by 10cl** [robbyrussell/oh-my-zsh#6591] opened 2018-02-01 02:32 UTC
When I entered an old Android project, it was a huge git repository. I just enter `cd xxx` , It will take me a long time to go in. I want to know how to reconfigure it make it fast. thanks.

**Comment by nguymin4** [comment] 2018-02-17 00:14
I agree it's very slow.

**Comment by developer-jason** [comment] 2018-02-21 08:25
also same here..

**Comment by mcornella** [comment] 2018-08-09 19:42
Duplicate of #3009.

**Closed by mcornella** 2018-08-09 19:42 UTC
