### ISSUE TITLE
Git status is not correct while submodule is ignored

### ISSUE THREAD

**Issue by RingoD** [robbyrussell/oh-my-zsh#6208] opened 2017-07-28 07:59 UTC
My git repo contains a submodule with ignore-flag.
See ignore flag for submodule : https://git-scm.com/docs/gitmodules#gitmodules-submoduleltnamegtignore

So the changed of submodule will not be shown in the result of `git status`. But at this time, oh-my-zsh still show a fork but not circle.

Here is the sample result at my cmd.

```
# sanhuazhang @ SANHUAZHANG-MC0 in ~/Developer/myrepo on git:master x [15:50:07]
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

# sanhuazhang @ SANHUAZHANG-MC0 in ~/Developer/myrepo on git: master x [15:51:14] C:1
$ git submodule update
Submodule path 'XXX': checked out 'XXX'

# sanhuazhang @ SANHUAZHANG-MC0 in ~/Developer/myrepo on git: master o [15:57:46]
```

I think you can see the changed of "fork and circle" status before and after git submodule update.

Is it a bug or a fixed issue?

**Comment by mcornella** [comment] 2019-04-07 21:03
This is a duplicate of #5617.

**Closed by mcornella** 2019-04-07 21:03 UTC
