### ISSUE TITLE
AWS Plugin no longer working.

### ISSUE THREAD

**Issue by anamorph** [robbyrussell/oh-my-zsh#7890] opened 2019-05-29 12:26 UTC
seems the regex to extract profile names isn't working anymore.
I replaced:

`grep '\[profile' "${AWS_CONFIG_FILE:-$HOME/.aws/config}"|sed -e 's/.*profile \([a-zA-Z0-9_\.-]*\).*/\1/'`

by:
`grep '\[[^]]*]' ${AWS_CONFIG_FILE:-$HOME/.aws/config} | cut -d "[" -f2 | cut -d "]" -f1`

and it worked.

please fix :-)

**Comment by mcornella** [comment] 2019-05-29 16:09
Can you post your aws config file? (remove sensitive info first)

**Comment by vdlp-mw** [comment] 2019-06-11 12:33
The following regex may be more flexible:
```zsh
grep -Eo '\[profile\s*(\S+)\s*?\]' "${AWS_CONFIG_FILE:-$HOME/.aws/config}" \ # Get all [profile*] blocks.
  | cut -d']' -f1  \  # Cut the lefthand side of ']', resulting in [profile*
  | awk '{$1=$1};1' \ # Remove leading/trailing spaces
  | grep -Eo '\S+$'   # Grep all right hand side data.
```

This will correctly match the following profiles:
```ini
[profile ihi0 ]
[profile mvw045]
[profile test-ing]
[profile   billing]
[profile ihi-staging  ]
[profile ihi-prod]
```

**Comment by mcornella** [comment] 2019-06-11 18:22
The current version works with all of these profiles though, while OP's version gets everything inside `[]`. Has the config formatting changed?

**Comment by vdlp-mw** [comment] 2019-06-12 06:48
If `grep '\[profile' "${AWS_CONFIG_FILE:-$HOME/.aws/config}"|sed -e 's/.*profile \([a-zA-Z0-9_\.-]*\).*/\1/'` is the current format than it does not get `[profile   billing]` because of the double spacing.

Not sure wether it's valid or not.

**Comment by mcornella** [comment] 2019-06-12 18:35
That doesn't explain @anamorph's problem though, and it's a minor enough thing that I don't think it warrants a "fix". I don't think people will bump into this, and if they do they'll quickly know how to fix it.

Since OP hasn't replied for 2 weeks I'm closing this as non-reproducible.

**Closed by mcornella** 2019-06-12 18:35 UTC
Labels: Type: support

**Comment by anamorph** [comment] 2019-06-13 05:35
> Can you post your aws config file? (remove sensitive info first)

There it is, sorry for the delay.

[default]
region = eu-west-1
output = json

[customer3dotcom]
region = eu-west-1
output = json

[customer1-demo]
region = eu-west-1
output = json

[customer1-master]
region = eu-west-1
output = json

[customer1-nicolas]
region = eu-west-1
output = json

[customer1-prod]
region = eu-west-1
output = json

[customer1-sit]
region = eu-west-1
output = json

[customer1-uat]
region = eu-west-1
output = json

[customer1-log]
region = eu-west-1
output = json

[customer1-shared]
region = eu-west-1
output = json
[profile customer2-prod]
region = eu-west-1
output = json

**Comment by vdlp-mw** [comment] 2019-06-13 07:04
You're missing the profile prefix in your config. This is what the docs say:

> **Important**
> The credentials file uses a different naming format than the CLI config file for named profiles. **Include the prefix "profile"** only when configuring a named profile in the config file. Do not use profile when configuring the credentials file.

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html


```
[default]
region = eu-west-1
output = json

[profile customer3dotcom]
region = eu-west-1
output = json

[profile customer1-demo]
region = eu-west-1
output = json

[profile customer1-master]
region = eu-west-1
output = json

[profile customer1-nicolas]
region = eu-west-1
output = json

[profile customer1-prod]
region = eu-west-1
output = json

[profile customer1-sit]
region = eu-west-1
output = json

[profile customer1-uat]
region = eu-west-1
output = json

[profile customer1-log]
region = eu-west-1
output = json

[profile customer1-shared]
region = eu-west-1
output = json

[profile customer2-prod]
region = eu-west-1
output = json
```

**Comment by StoyanIvanovI** [comment] 2019-11-28 16:30
The discussion above is incorrect because profiles are valid both defined in `~/.aws/config` and `~/.aws/credentials` files. In the credentials file they do not have a `[profile ]` prefix. The word "profile" is something AWS has been trying to get away from as it was too restrictive. Profile just means a set of credentials now and AWS CLI and SDK honour it. All the saml and mfa login tools don't bother maintaining a config file but just credentials file. The "improvement" that was done to check if profiles exist definitely broke the tool for many people. I had to reinstall machineand was surprised that it doesn't work any more for me. I guess I'm back to simple env variable setting...

**Comment by mcornella** [comment] 2019-11-28 17:34
When was there a version that worked? From what I'm seeing, the aws plugin always checked the config file. There has never been a version checking the credentials file nor it's different profile syntax (`[<profile>]`). Can you point to a version that worked for both?

**Comment by StoyanIvanovI** [comment] 2019-12-11 09:10
I cannot point to a version that worked but can definitely confirm that at the moment it doesn't work getting an error `asp:7: no matches found: available_profiles=()` for a credentials configuration that absolutely works with exporting `AWS_PROFILE=my_profile_name`.

**Comment by mcornella** [comment] 2019-12-13 19:18
@StoyanIvanovI subscribe to #8472 for updates to this problem.
