### ISSUE TITLE
Cursor shows one character behind

### ISSUE THREAD

**Issue by cuimalo** [robbyrussell/oh-my-zsh#3325] opened 2014-11-15 21:13 UTC
I'm having an issue with the cursor showing one character behind where it should when using the [chrome mosh app](https://chrome.google.com/webstore/detail/mosh/ooiklbnjmhbcgemelgfhaeaocllobloj) and [chrome ssh app](https://chrome.google.com/webstore/detail/secure-shell/pnhechapfaindjhompbnflcldabbghjo). 

I'm accessing a Ubuntu 14.04 VPS with a vanilla `curl -L http://install.ohmyz.sh | sh` install. This does not happen when I use [putty](http://www.chiark.greenend.org.uk/~sgtatham/putty/). I suspect this is a UTF-8 issue. 

![image](https://cloud.githubusercontent.com/assets/545016/5059253/fea8d270-6cd1-11e4-99be-94c5d4dab84e.png)

**Comment by mcornella** [comment] 2015-02-21 21:36
I have no idea how to debug this, sorry. Please post your current configuration (`~/.zshrc` file) and which version of `oh-my-zsh` you have installed: `cd "$ZSH"; git rev-parse --short HEAD; cd -`.

**Comment by apjanke** [comment] 2015-03-07 03:27
I think this is an issue in the Mosh Chrome app, possibly specific to it on Windows, and not zsh or oh-my-zsh.

I can reproduce this by logging in from the Mosh Chrome app running in Windows 7 by logging in to an Ubuntu machine running zsh, oh-my-zsh, and the default `robbyrussell` theme. Like OP, the cursor lags behind where it should be, and it looks like @cuimalo's screenshot. (Not exactly a full character: the red insertion point is not centered over the character.)

But if I switch the theme to `agnoster` or something else, the cursor is aligned. And if I just fill up the line with characters to the cursor wraps to the next line, the cursor looks properly aligned on that line.

More tellingly, if I take that "➜" character ([U+279C, Heavy Round-Tipped Rightwards Arrow](http://www.fileformat.info/info/unicode/char/279c/index.htm)) and stick it in my `$PS1` in `~/.bashrc`, the same problem happens under `bash`.

![mosh cursor bug on bash](https://cloud.githubusercontent.com/assets/2618447/6539823/f4aebf86-c44d-11e4-9d8d-1bf49499732b.png)

It looks like Chrome Mosh is unaware that the `➜` is taking up more than a normal character width when displayed in the font that its terminal emulation is using, and is misplacing the cursor.

So it doesn't look like it's an issue in `zsh` or oh-my-zsh; it's just that it's an oh-my-zsh theme that happens to contain that character.

You can [report it as a bug to mosh-chrome](https://github.com/rpwoodbu/mosh-chrome/issues), which is also hosted here on GitHub.

**Comment by apjanke** [comment] 2015-04-01 03:32
Can we close this? It's a `mosh` bug, not an `oh-my-zsh` bug.

**Comment by southskies** [comment] 2015-04-02 20:58
Totall, awesome work!

**Closed** 2015-06-05 15:02 UTC

**Comment by ChaosJohn** [comment] 2017-11-22 06:27
I wrote a shell script to fix the error while still using default robbyrussell theme. 
https://gist.github.com/ChaosJohn/245c58ae042f172feca2d81ee498afc1

**Comment by cellcoresystems** [comment] 2020-03-30 23:46
I also had a lot of trouble to set up Powerline on iTerm2 and also oh-my-zsh and just recently bought a Chromebook and I had the same issue like you.

SOLUTION:
Use the right fonts -> https://github.com/wernight/powerline-web-fonts

No Problem with hterm or iTerm or any other terminal emulator.
Use one of those fonts with zsh and you will be happy :o)

Cheers guys.
