### ISSUE TITLE
Divide by zero error for random_emoji in emoji plugin

### ISSUE THREAD

**Issue by idlem1nd** [robbyrussell/oh-my-zsh#4245] opened 2015-08-14 10:58 UTC
I'm on master, HEAD is at 192de6b.

Enabled the emoji plugin, also running:

```
plugins=(git git-extras osx history history-substring-search emoji)
```

I can select an individual emoji ok using e.g. `echo $emoji[penguin]` but if I try the random function, I get a divide by zero error for any category (no category specified works ok).

```
$> random_emoji fruits
random_emoji:9: division by zero
```

**Comment by mcornella** [comment] 2015-08-14 17:29
Gotcha. This is because the `random_emoji` mixes `$group` and `$group_name` variables incorrectly.
Here's a patch:
```diff
diff --git a/plugins/emoji/emoji.plugin.zsh b/plugins/emoji/emoji.plugin.zsh
index a98d0b7..adb11bb 100644
--- a/plugins/emoji/emoji.plugin.zsh
+++ b/plugins/emoji/emoji.plugin.zsh
@@ -255,7 +255,7 @@ function random_emoji() {
   if [[ -z "$group" || "$group" == "all" ]]; then
        names=(${(k)emoji})
   else
-       names=(${=emoji_groups[$group_name]})
+       names=(${=emoji_groups[$group]})
   fi
   local list_size=$#names
   local random_index=$(( ( RANDOM % $list_size ) + 1 ))
```

**Comment by mcornella** [comment] 2015-08-16 20:41
Fixed in #4250

**Comment by idlem1nd** [comment] 2015-08-17 10:36
Thanks @mcornella, with the patch it works as expected. Quick question that's got me puzzled if you have the time...

I tried to modify the agnoster theme to include a random fruit emoji in the prompt when there's no errors:

```
163 prompt_status() {
164   local symbols=
165   symbols=()
166   [[ $RETVAL -ne 0 ]] && symbols+="%{%F{red}%}✘"
167   [[ $UID -eq 0 ]] && symbols+="%{%F{yellow}%}⚡"
168   [[ $(jobs -l | wc -l) -gt 0 ]] && symbols+="%{%F{cyan}%}⚙"
169 
170   #[[ -n "$symbols" ]] && prompt_segment black default "$symbols"
171   if [[ -n "$symbols" ]]; then
172     prompt_segment black default "$symbols"
173   else 
174     fruit="$(random_emoji fruits) "                                                                                                                  
175     prompt_segment blue black $fruit
176   fi  
177 }
```

This puts an emoji in the right place, but is the same emoji every time unless I run the random_emoji command. I would expect it to change as `build_prompt` is re-evaluated each time. Can you explain why it doesn't change?

```
 🍊  ~ >
 🍊  ~ > 
 🍊  ~ > 
 🍊  ~ > 
 🍊  ~ > random_emoji 
💫
 🍉  ~ > 
 🍉  ~ > 
 🍉  ~ > random_emoji
🍦
 🍍  ~ > 
```

**Comment by mcornella** [comment] 2015-08-17 11:50
That's an interesting behavior. It's seems the `$RANDOM` variable is not getting updated each time it is referenced. I can trigger an update by running `echo $RANDOM` each time. Otherwise, the emoji stays the same. I'll investigate...
cc @apjanke

**Comment by mcornella** [comment] 2015-08-17 12:01
Here's a sample of this behavior. The random on the left is the value of `$RANDOM`:
```
 21101 🍒 ~  :
 21101 🍒 ~  :
 21101 🍒 ~  :
 21101 🍒 ~  :
 21101 🍒 ~  :
 21101 🍒 ~  :
 21101 🍒 ~  echo $RANDOM
21101
 27880 🍑 ~  
```

**Comment by mcornella** [comment] 2015-08-17 12:05
It seems there's some problem with [using `$RANDOM` in prompt sequences, try putting it on `precmd`](http://stackoverflow.com/questions/22332710/unix-shell-how-to-have-a-prompt-that-change-randomly):
```zsh
 27880 🍑 ~  precmd_functions=(dummy_random)
 27880 🍑 ~  dummy_random(){echo $RANDOM &>/dev/null}
 15940 🍑 ~ 
 16415 🍊 ~  
 25208 🍎 ~  
 17990 🍊 ~  
 13922 🍇 ~  
 3529 🍉 ~  
 17281 🍆 ~  
```

**Comment by idlem1nd** [comment] 2015-08-17 12:36
Nice one! Added the following to my theme and it works great 👌

```
 precmd()                                                                                                                                             
 {
   # force a change in $RANDOM so that random_emoji will return a 
   # new emoji for every new prompt
   echo $RANDOM &>/dev/null
 }
```

**Comment by mcornella** [comment] 2015-08-17 13:30
[`: $RANDOM`](http://www.zsh.org/mla/workers/2002/msg00121.html) is a better alternative, and you should put that in a function different than `precmd()`, which is possibly going to clash with the rest of `precmd_functions`.
I'll ask around in the mailing list to see if there's a better alternative, anyway.

**Comment by idlem1nd** [comment] 2015-08-17 14:07
Okay, thanks. Calling `: $RANDOM` from inside one of the theme's helper functions works just fine, and doesn't pollute `precmd()`.

```zsh
 prompt_status() {
   local symbols=
   symbols=()
   [[ $RETVAL -ne 0 ]] && symbols+="💥 "
   [[ $UID -eq 0 ]] && symbols+="⚡️ "
   [[ $(jobs -l | wc -l) -gt 0 ]] && symbols+="🔧 "
 
   if [[ -n "$symbols" ]]; then                                                                                                                         
     prompt_segment black default "$symbols"
   else
     # force a new $RANDOM so that random_emoji returns a new emoji for each prompt 
     # see http://www.zsh.org/mla/workers/2002/msg00121.html
     : $RANDOM
     prompt_segment blue black "$(random_emoji fruits) "
   fi  
 }  
```

**Comment by mcornella** [comment] 2015-08-17 14:21
Ok, I see what's happening, it's the subshell syntax `$()`:
```
$ echo $(echo $RANDOM)
8079
$ echo $(echo $RANDOM)
8079
$ echo $(echo $RANDOM)
8079
$ echo $(echo $RANDOM)
8079
$ (echo $RANDOM)
8079
$ (echo $RANDOM)
8079
$ (echo $RANDOM)      
8079
$ (echo $RANDOM)
8079
```
For some reason that doesn't trigger a renewal of the `$RANDOM` value. That's actually what that mailing list thread says, I just skimmed it :joy:

**Comment by apjanke** [comment] 2015-08-18 00:39
Doing `$RANDOM` in the subshell does trigger advancing of the `$RANDOM` variable... but only in the subshell that has been `fork`ed from the main shell, with a copy of the current RNG state. Since `$RANDOM` is not called in the parent process, it doesn't advance. You can see this by using `$RANDOM` multiple times in the subshell.

```
$ echo $( echo $RANDOM $RANDOM $RANDOM )
5791 16520 16787
$ echo $RANDOM $RANDOM $RANDOM
5791 16520 16787
```

You can advance $RANDOM in a precmd or postcmd hook function, like Marc suggests. I don't think putting `: $RANDOM` in the helper function will work. I tried that and it's still returning the same emoji each time. I'm guessing maybe you still have `precmd()` defined somewhere and it's advancing `$RANDOM`.

But there's a larger problem. Since `random_emoji` outputs the character, and the usual `zsh` way of capturing arbitrary function output is with a capturing subshell, this will affect basically any practical use of the function.

```
$ fruit=$(random_emoji fruits)
$ echo $fruit
🍇
$ fruit=$(random_emoji fruits)
$ echo $fruit
🍇
```

Oops. This is a flaw in the design of `random_emoji()`. There's no clean way to use it without a subshell. I overlooked this when I was testing it. ([Here's a longer version of that same discussion](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=131337) about `$RANDOM` and subshells.)

The `random_emoji()` function should probably modified to fix this. Hmmm.

`random_emoji()` could be expanded to optionally take the name of a variable to assign the character to instead of writing it to stdout, so you can use it to set a variable without a subshell. Then you could call that in a `$precmd_functions` hook, assign it to a variable like `$AGNOSTER_PROMPT_FRUIT` and use that variable inside the prompt string instead of calling `$(random_emoji)` directly.

As a hack. you could also make a wrapper function that re-seeds `$RANDOM`, for use in subshell calls.

```
function randomer_emoji() {
   # Extra subshell layer to ensure this always runs in its own subshell to
   # avoid polluting parent shell $RANDOM sequence
   ( RANDOM=<new random seed>; random_emoji $@ )
}
```

It should *only* be used in subshell calls that are calling only it, though, and I'm hesitant to do it: if called outside a subshell, it would pollute `$RANDOM`'s seed in the main shell, and it would break reproducibility of runs using `$RANDOM` regardless.

Problem: I can't figure out a good, highly portable way to get the `<new random seed>` value. Using seconds + milliseconds of current time would work, but that's not available on all systems or all versions of `zsh`. `$SECONDS` is too coarse. `print -P "%D{%S%.}` works, but that `%.` support only showed up some time after Zsh 5.0.2. BSD and OS X `/bin/date` doesn't support milliseconds. `$$` reports the parent PID when used in subshells. `/dev/random` should probably be treated as a scarce resource and not used for prompt decoration. Any ideas?

I guess you could just require a `zsh` new enough for `%D{%.}` and error out otherwise. Or, for just your prompt, fall back to just getting a new fruit once a second.

**Comment by idlem1nd** [comment] 2015-08-18 10:30
Thanks @apjanke for the detailed explanation. You're right - I hadn't sourced my `.zshrc` after removing `precmd()`. I'm now re-seeding random as shown below, which as you say, can only give one new fruit per second on OS X. Which will do for now! 😐

```zsh
prompt_status() {
  local symbols=
  symbols=()
  [[ $RETVAL -ne 0 ]] && symbols+="💥 "
  [[ $UID -eq 0 ]] && symbols+="⚡️ "
  [[ $(jobs -l | wc -l) -gt 0 ]] && symbols+="⏳ "

  if [[ -n "$symbols" ]]; then
    prompt_segment white default "$symbols"
  else
    RANDOM=$(print -P "%D{%S}")                                                                                                                      
    prompt_segment white default "$(random_emoji fruits) "
  fi  
}
```

**Comment by mcornella** [comment] 2015-08-18 11:58
If your system supports it, [you can use `%.` instead of `%S` to get milliseconds](zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Date-and-time). Bummer that there's no other solution besides the `precmd()` trick to get random numbers...

**Comment by idlem1nd** [comment] 2015-08-18 15:18
Unfortunately `%.` and `%N` aren't supported on my platform (OS X). I guess I could `brew install coreutils` and use `gdate` but that seems like overkill. I'm happy with what I've got for now, didn't realise what a can of worms I was opening with this! Thanks both for your help :+1:

**Comment by apjanke** [comment] 2015-08-18 17:48
I think the `%D{%.}` isn't a platform thing; it's a Zsh version thing. E.g. the system zsh 5.0.5 that ships with OS X Yosemite doesn't support it, but the Homebrew-provided zsh 5.0.8 on Yosemite does. The [zsh Release Notes](http://zsh.sourceforge.net/releases.html) say that `%D{%.}` was added in zsh 5.0.6.

*Smacks forehead*. Here's a way you could get distinct fruit for every call, portably. Make a counter to use as "salt" for the random seed, increment it in a `precmd_functions` hook, and use it inside the prompt code to re-seed `$RANDOM` (so it's incremented in the top shell and persists, but doesn't affect `$RANDOM` except in the subshell).

```
THEME_FRUIT_COUNTER=1

function _increment_fruit_counter() {
  (( THEME_FRUIT_COUNTER = THEME_FRUIT_COUNTER + 1 ))
}

function _reseed_fruit() {
  local secs=$(print -P "%D{%S}")
  local next_seed="$THEME_FRUIT_COUNTER$secs"
  (( RANDOM = next_seed % 32767 ))
}

precmd_functions+=_increment_fruit_counter

prompt_status() {
  _reseed_fruit  # <-- here's where $RANDOM gets reset inside the subshell
  local symbols
  symbols=()
  [[ $RETVAL -ne 0 ]] && symbols+="%{%F{red}%}✘"
  [[ $UID -eq 0 ]] && symbols+="%{%F{yellow}%}⚡"
  [[ $(jobs -l | wc -l) -gt 0 ]] && symbols+="%{%F{cyan}%}⚙"

  if [[ -n "$symbols" ]]; then
    prompt_segment black default "$symbols"
  else
    prompt_segment black default "$(random_emoji fruits) "
  fi
}
```

Now you get a new fruit on every prompt, regardless of how often one is issued.

**Comment by idlem1nd** [comment] 2015-08-18 19:29
Haha nice that works brilliantly. One heck of a work-around! I feel like I should release this "fruit theme" after all the hard work we've put into it.

I think the lack of `%.` probably is platform specific. I updated my zsh using homebrew and it still doesn't work correctly. I think this is because the BSD `/bin/date` that OS X uses [doesn't have any precision beyond seconds](http://apple.stackexchange.com/questions/135742/time-in-milliseconds-since-epoch-in-the-terminal). Using `gdate` from `coreutils` does, but that's not exactly a portable approach. In other words, I think you've done the best that can be expected, thanks again!

```
 🍓   ~  zsh --version
zsh 5.0.7 (x86_64-apple-darwin14.0.0)
 🍍   ~  print -P %D{%S%.}
43.
```

**Comment by apjanke** [comment] 2015-08-18 19:48
Thanks!

Check your `$ZSH_VERSION` instead of doing `zsh --version`. The `zsh` you're in isn't necessarily the `zsh` that gets called. Homebrew's `zsh` is first on your path, so that's what you get when you call it from the command line in an already-running `zsh` session that has added `/usr/local/bin` to the front of the path. But your default shell is still OS X's `/bin/zsh`, and new terminal windows or other login sessions will start with that unless you've gone out of your way to configure them to use Homebrew's `zsh` instead.

E.g., here's what I get in a fresh Terminal window.

```
➜  ~  zsh --version
zsh 5.0.8 (x86_64-apple-darwin13.4.0)
➜  ~  echo $ZSH_VERSION
5.0.2
➜  ~  print -P "%D{%S.%.}"
26..
➜  ~  zsh -l
➜  ~  echo $ZSH_VERSION   
5.0.8
➜  ~  print -P "%D{%S.%.}"
35.567
➜  ~  
```

Zsh's `%D{%.}` does not care about `/bin/date` or other external commands. It just uses the POSIX `gettimeofday` system call. ([Fixed link to doco.](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Date-and-time))

**Comment by idlem1nd** [comment] 2015-08-18 20:10
(facepalm) you're totally right. I've learnt a lot from what started out as mucking about with the emoji plugin :+1:

**Closed** 2015-08-31 04:38 UTC
