### ISSUE TITLE
Tab completion for the 'debian' plugin

### ISSUE THREAD

**Issue by balasankarc** [robbyrussell/oh-my-zsh#3686] opened 2015-03-12 17:41 UTC
When using apt- commands normally, I can get tab completion to automatically complete the package name OR list the packages matching pattern. Is it possible to get that with the debian plugin?
Like while using acs.

**Comment by ncanceill** [comment] 2015-04-05 20:10
Completion for the `acs` alias should be identical to a regular `apt-cache search`. Is it not the case?

In order to help us help you, please answer the following three questions about your completion issue:
* How can we reproduce the issue?
* What should be the correct behavior?
* What happens instead?

**Comment by balasankarc** [comment] 2015-04-07 04:59
When I use `apt-get install` , after I type `apt-get install iceweasel` and press tab, I get a list of all the packages starting with 'iceweasel'. But, that doesn't happen with `ai iceweasel`. 

But when I am using `sudo ai`, tab completion works. It should be made to support without sudo also.

**Comment by apjanke** [comment] 2015-09-28 13:56
The Debian plugin [already has support for completion on those `sudo` commands](https://github.com/robbyrussell/oh-my-zsh/blob/b05ef1034fffd7b0c29f1558a8a357ccce7ae74b/plugins/debian/debian.plugin.zsh#L118-L134). It dynamically defines completion wrappers for them.

```
    alias ai='sudo $apt_pref install'

[...snip...]

apt_pref_compdef() {
    local f fb
    f="_apt_pref_${2}"

    eval "function ${f}() {
        shift words; 
	service=\"\$apt_pref\"; 
	words=(\"\$apt_pref\" '$2' \$words); 
	((CURRENT++))
	test \"\${apt_pref}\" = 'aptitude' && _aptitude || _apt
    }"

    compdef "$f" "$1"
}

[...snip...]

apt_pref_compdef ai  "install"
apt_pref_compdef ail "install"
```

But it doesn't seem to be working.

I think the problem is that unless you have the `complete_aliases` option set, aliases are expanded before locating the completion function to use. So these special completions are never actually invoked. Maybe they were written before 5b75cc7880de1931a0507800d90eb77ed659fa46 when `complete_aliases` was turned back off by default.

Also, the `test \"\${apt_pref}\" = 'aptitude' && _aptitude || _apt` test is broken because `$apt_pref` holds the complete path to the program, not just its basename.

Normally, `zsh` is smart enough to do completion for a command that starts with `sudo`. But because these aliases are using `$apt_pref` instead of the raw command name. That seems to be enough to break the completions.

If you don't need to support changing `$apt_pref` during the course of a session, we can probably just change the aliases to eager-evaluate `$apt_pref` at plugin load time, remove all the special completion code, and things will probably just work. Or you could turn the aliases in to functions, and the custom completion wrappers might start working.

**Comment by isomerase** [comment] 2016-01-31 04:50
I'm also experiencing this. @apjanke Where do I set `complete_aliases` option?

**Comment by mcornella** [comment] 2016-02-01 09:25
In your zshrc file should be enough, with a simple `setopt complete_aliases`

**Comment by balasankarc** [comment] 2016-02-01 10:12
`setopt completealiases` fixed my issue. Should I close it or leave it open for you guys to investigate (if there is something to investigate) ?

**Comment by apjanke** [comment] 2016-02-02 06:19
The problem is that setting `complete_aliases` will break completion for other things, and most users will want it off, per #4407. I think this is effectively a bug in the `debian` plugin and we should leave this open.

**Comment by okapia** [comment] 2017-01-07 07:19
You should make `complete_aliases` the default. If that breaks completion for other things then change those other things to be functions instead of aliases.

**Comment by NellyWhadsDev** [comment] 2017-12-18 08:36
@apjanke Any thougths on a fix for this? I've been scowering the corners of the web hoping someone has found a solution I could use (the setopt mentioned here isn't working for me)

**Comment by okapia** [comment] 2017-12-21 01:05
@NellyWhadsDev: if setopt complete_aliases isn't working for you then you must have some other issue. To begin with is completion after 'apt-cache search ' working for you? Where are you setting the option: could it be getting reset?

**Comment by NellyWhadsDev** [comment] 2017-12-22 05:46
@okapia I'm setting it at the very end of my .zshrc, using `antigen` as my framework (the `setopt complete_aliases` is done after `antigen apply`, after a few other `setopt`'s that all work correctly.

**Comment by NellyWhadsDev** [comment] 2017-12-24 21:18
@okapia here's a little update:
1. tab-autocompletion *works* after `sudo apt-get install` (for searching through package names)
2. tab-autocompletion does *not* work after `apt-cache search` (tried with sudo as well)
3. `bash-completion` *is* installed

**Comment by NellyWhadsDev** [comment] 2018-01-18 05:54
Bumping this, any thoughts?

**Comment by okapia** [comment] 2018-01-18 10:55
NellyWhadsDev: based on what you say, your problem has nothing to do with aliases which is what this bug was originally opened to handle. What it comes down to is that the apt-cache completion is explicitly defined to not complete anything after "apt-cache search" because search terms can be literally anything. But it will prompt for a "search term". Similarly, nothing is completed after grep: you're just prompted for a "pattern".

If you want completion of an acs alias to prompt for a "search term", this bug is relevant. If you want to complete packages instead of search terms, you'll need to use a modified _apt. If you want the default _apt function to do this, it'll probably need to be configurable because packages are not search terms.

**Comment by mcornella** [comment] 2019-03-25 15:39
I've submitted #7698 which should take care of this issue, please test and +1 if it works.

**Closed** 2019-06-11 13:02 UTC
Labels: Area: plugin, Topic: alias, Topic: completion
