### ISSUE TITLE
Installer claims git not installed

### ISSUE THREAD

**Issue by tscheckenbach** [robbyrussell/oh-my-zsh#6697] opened 2018-03-28 11:19 UTC
I've a zsh installer script which also installs oh-my-zsh and other zsh related stuff this worked for years. It's part of a series of provisiong scripts for a vagrant box, the first provisioning script installs git on the system.

Since today it says "Error: git is not installed" (Line 53 installer.sh) the next step of the script clones powerlevel9k which proves git is already installed on the system. I can see the target dir of the prowerlevel9k clone command.

Here my first two steps of the zsh provining:
```bash
echo ">>> Install Oh-My-ZSH"
sudo apt-get install -y zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

echo ">>> Install powerlevel9k theme"
git clone https://github.com/bhilburn/powerlevel9k.git /home/vagrant/.oh-my-zsh/custom/themes/powerlevel9k
sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="powerlevel9k\/powerlevel9k"/' /home/vagrant/.zshrc
```

As I can see the installer.sh hasn't changed since 10.2017 any ideas why the git check could fail though git is installed?

**Comment by tscheckenbach** [comment] 2018-03-28 13:26
Additional information. If I first download the install script and execute it it works.

**Comment by prometheas** [comment] 2018-04-01 15:40
I'm seeing the same thing, as well, in the course of building a Docker container. Here's the (super simple) Dockerfile:

```Dockerfile
FROM node:8.9.4-alpine

RUN apk add --update \
  bash \
  curl \
  git \
  less \
  openssh \
  'py-pip' \
  rsync \
  'ruby>2.4' \
  zsh

RUN pip install \
  awscli \
  'docker-compose==1.8.0'

RUN npm install -g \
  @storybook/cli \
  commitizen \
  conventional-changelog-cli \
  cz-conventional-changelog \
  lerna

ENV TERM "xterm-256color"
ENV OH_MY_ZSH_INSTALL_URL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh

# install oh-my-zsh (removed the "|| true" so that this error kills container build
RUN curl -fsSL ${OH_MY_ZSH_INSTALL_URL} | zsh
```

This will fail on the last line.

**Comment by giuspe** [comment] 2018-04-03 07:12
quick workaround:

1. download the install script 
`wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh`
2. edit the script, and comment out or delete the part saying 
```
hash git >/dev/null 2>&1 || {
    echo "Error: git is not installed"
    exit 1
  }
```
3. run the script thru zsh:
zsh ./install.sh

it should now install without problems.

**Comment by prometheas** [comment] 2018-04-03 12:47
Yes, agree—same has worked for me, @giuspe.

**Comment by prometheas** [comment] 2018-04-12 20:58
That's actually a fantastic workaround, @shark0der, as I can scrap my installer script modifications. Nice find!

**Comment by mcornella** [comment] 2018-04-13 16:42
That's a weird bug. Any ideas why `hash git` might fail? Please post the following:

1. Shell with which you ran the installer (with platform and version if possible).
2. The output of `which hash` with the shell from point 1.
3. The output of `command -v git && echo found || echo not found` with the same shell.

Just trying to figure it out. Thanks!

**Comment by prometheas** [comment] 2018-04-15 18:13
@mcornella - using the Dockerfile I've posted above, you'll be able replicate my _exact_ environment. The error occurs during `docker build`. To really narrow down the variables, you can even merely use this file to reproduce the error:

```Dockerfile
FROM node:8.9.4-alpine

RUN apk add --update zsh curl

ENV INSTALL_URL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh

# install oh-my-zsh (removed the "|| true" so that this error kills container build
RUN curl -fsSL ${INSTALL_URL} | zsh
```

**Comment by iceydee** [comment] 2018-04-17 10:45
Running into same problem. I've found a temporary workaround, if using `bash` rather than `zsh` to run the install-script it works. Maybe the built-in `hash` shell-command in zsh on alpine has changed.

**Comment by mcornella** [comment] 2018-04-17 20:18
Fixed on 4fec0a4. Thanks for the Dockerfile, it helped!

**Closed by mcornella** 2018-04-17 20:18 UTC

**Comment by miladmofidi** [comment] 2023-12-13 11:54
i had this issue when i wanted to install ohmyzsh, i think the problem was about the git, because when I removed and reinstalled it by this command the problem was solved:
`sudo apt remove git && sudo apt install git`
and then i could install OhMyZsh with this command:
`sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzs...)"`

**Comment by elmoteroloco** [comment] 2025-04-10 17:44
windows 11 (wsl2) 

after `sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"` 
Debian give same: **`Error: git is not installed`**

solved by `miladmofidi` (`sudo apt remove git && sudo apt install git` then run installer) method up here, flawless

gratitude!
