### ISSUE TITLE
Bira theme breaks slightly on non-zero return value

### ISSUE THREAD

**Issue by anthropomorphic** [robbyrussell/oh-my-zsh#7778] opened 2019-04-17 21:28 UTC
![Screen Shot](https://user-images.githubusercontent.com/2002883/56321979-afec7a80-611c-11e9-8eb2-f67a9b6775ca.png)

As you can see, when I run a command with a non-zero exit, the cursor is placed over the `$` character, and the next command I type overwrites it.

Running iTerm 2 on MacOS

**Comment by anthropomorphic** [comment] 2019-04-18 03:56
**Update:** I realized this doesn't happen on my mac itself. When I install `bira` locally, it works fine. It's only when `ssh`ing into my FreeBSD (FreeNAS) server that this happens.

**Comment by mcornella** [comment] 2019-04-18 15:14
Duplicate of #7761: use a UTF-8 locale.

**Closed by mcornella** 2019-04-18 15:14 UTC
