### ISSUE TITLE
How does one suppress rum-prompt or battery-prompt type errors?

### ISSUE THREAD

**Issue by Noffica** [robbyrussell/oh-my-zsh#4272] opened 2015-08-21 22:46 UTC
With certain themes, every new line is preceded by an error such as

```
zsh: no such file or directory: /Users/username/.rvm/bin/rvm-prompt
```

How does one suppress these errors?

**Comment by apjanke** [comment] 2015-08-21 23:01
This is caused by themes calling RVM commands without checking to see if RVM prompt is installed. The themes should be fixed to only do RVM stuff if RVM if `rvm-prompt` exists. An easy way to do this is to switch to using the `rvm_prompt_info()` function provided by core OMZ in `lib/prompt_info_functions.zsh`, which does check whether `rvm-prompt` exists, and is silent if it's absent.

Go ahead and report this as a bug against the individual theme that's doing it. (Doing a search first to see if it's already been reported.)

**Comment by apjanke** [comment] 2015-11-06 22:24
I put in a PR #4588 that changes all the themes using naive `rvm-prompt` calls to use the graceful `ruby_prompt_info` instead, which just displays a blank when you have no Ruby version manager installed.

**Closed** 2019-05-08 06:55 UTC
Labels: Area: theme, Type: bug
