### ISSUE TITLE
Tab completion segfault with zsh 5.1.1

### ISSUE THREAD

**Issue by jonathonf** [robbyrussell/oh-my-zsh#4346] opened 2015-09-13 20:14 UTC
With a recent update to zsh 5.1.1 in Arch/Manjaro, and with OMZ sourced in .zshrc, tab completion leads to a segfault in zsh (even with no loaded plugins). Commenting the source line lets tab completion work correctly. Tab completion worked perfectly with zsh 5.0.8.

strace of tab completion event:

```
poll([{fd=4, events=POLLIN}, {fd=6, events=POLLIN}, {fd=7, events=POLLIN}, {fd=10, events=POLLIN}], 4, 30) = ? ERESTART_RESTARTBLOCK (Interrupted by signal)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=17320, si_uid=1000, si_status=SIGSEGV, si_utime=10, si_stime=3} ---
write(13, "\1\0\0\0\0\0\0\0", 8)        = 8
rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)
write(6, "\1\0\0\0\0\0\0\0", 8)         = 8
write(12, "\n\0\0\0", 4)                = 4
write(12, "\300\305\252\1\0\0\0\0", 8)  = 8
write(12, "\v\0\0\0", 4)                = 4
read(12, "\0", 1)                       = 1
close(11)                               = 0
close(10)                               = 0
write(6, "\1\0\0\0\0\0\0\0", 8)         = 8
futex(0xe3ff50, FUTEX_WAKE_PRIVATE, 2147483647) = 0
close(12)                               = 0
kill(17319, SIGTERM)                    = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=17319, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
write(13, "\1\0\0\0\0\0\0\0", 8)        = 8
rt_sigreturn({mask=[]})                 = 15236864
exit_group(1)                           = ?
+++ exited with 1 +++
```

``` bash
$ zsh --version
zsh 5.1.1 (x86_64-unknown-linux-gnu)
```

**Comment by apjanke** [comment] 2015-09-16 20:19
How did you install zsh on Arch? Was this via a package or a build from source?

This'll probably be something to report upstream; nothing in OMZ should be able to make `zsh` segfault.

**Comment by jonathonf** [comment] 2015-09-17 10:21
It's the repo package: https://www.archlinux.org/packages/extra/x86_64/zsh/ . That in turn is built from the zsh source (I'm running Manjaro but it uses the Arch packages).

I tried again with an entirely clean profile (new OS install in a VM) and after running the OMZ installer there's no problem with tab completion. The issue exists somewhere in my existing set-up; it could be user error, but the configuration hasn't changed and it did work fine previously... I'll have a dig through and try to find out the cause.

**Comment by jonathonf** [comment] 2015-09-17 16:48
Alrighty. The line in my configuration that triggers the issue is ```setopt all_export```.

When **set** and OMZ **enabled**, zsh will segfault.
When **set** and OMZ **not enabled**, zsh is fine.
When **unset** and OMZ **enabled**, zsh is fine.

It doesn't seem to matter the position of ```setopt all_export``` relative to ```source $ZSH/oh-my-zsh.sh```, its mere presence is enough. :)

**Comment by apjanke** [comment] 2015-09-17 17:44
Good repro case; thanks. I'll try to get this reproduced on my Arch box and narrow it down further, see if there's a workaround.

(This'll still have an upstream report, though: nothing in "userland" `zsh` settings should be able to cause a segfault in the shell itself.)

**Comment by apjanke** [comment] 2015-09-18 10:18
Also, would you mind running the `omz_diagnostic_dump()` function from [here](https://github.com/apjanke/oh-my-zsh/blob/diagnostic-dump-function/lib/diagnostics.zsh), and posting the output as a gist?

**Comment by jonathonf** [comment] 2015-09-19 15:43
https://gist.github.com/jonathonf/6f94d2baaaba9d4108f5

**Comment by apjanke** [comment] 2015-10-04 08:07
Ugh, I can't even get `zsh` and `git` installed on my Arch Linux box.

If anyone can tell me how to fix this, or has a public-facing Arch box I can log in to, I'll try to reproduce again. I don't have time to track this down right now.

```
[root@archie ~]# pacman -Sy
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
[root@archie ~]# pacman -S zsh
resolving dependencies...
looking for conflicting packages...

Packages (1) zsh-5.1.1-2

Total Installed Size:  5.12 MiB

:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                     [######################] 100%
downloading required keys...
error: key "7F2D434B9741E8AC" could not be looked up remotely
error: required key missing from keyring
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
[root@archie ~]#
```

In the mean time, @jonathonf, you've got some custom files living in your main Oh My Zsh directory. This won't cause any actual problems (probably), but they should really live in a separate custom directory, either `custom/` under `~/.oh-my-zsh`, or a separate directory you create and point `$ZSH_CUSTOM` at. That way they won't show up up as spurious changes in the `git status` output, and if you keep them in a separate directory tree, you can blow away and reinstall the main OMZ installation without hurting your customizations. I like to keep them in [my own oh-my-zsh-custom repo](https://github.com/apjanke/oh-my-zsh-custom) and clone it to `~/.oh-my-zsh-custom`. That makes sure my customizations are tracked and backed up, can be synced across multiple machines easily, and can be shared with other OMZ devs for debugging help. Just don't stick any passwords in 'em.

**Comment by apjanke** [comment] 2015-10-04 08:08
BTW, do you have a specific command string completion operation that will consistently segfault?

**Comment by jonathonf** [comment] 2015-10-07 14:50
This sounds like a classic keyring issue... it's probably something like

```bash
sudo pacman-key --populate archlinux
sudo pacman-key --refresh
```

https://wiki.archlinux.org/index.php/Pacman-key

I hadn't realised I had custom files... no idea how long they've been there. :)

No particular operation, any character(s)->tab->segfault.

I can tar up my config if you want - I don't think there's anything particularly sensitive in there and at least it should make reproducing the issue possible. On the other hand, this may all be more work than is really needed - if I'm the only one affected, and seeing as a fresh install has no issue, I'm quite happy for you to close this 'won't fix' or 'can't reproduce'.

**Comment by vwong** [comment] 2015-10-08 01:19
You're not the only one!  This has been bugging me lately too.  

Fortunately, I have been able to reproduce this:
  * enable `autoenv` plugin
  * cd into a directory with a `.env` file (or use `z`, `autojump`, etc.)
  * try autocomplete

The crashes still occur even if you cd into another directory without a `.env`, after cd-ing into the first one with `.env`.  This makes sense given how `autoenv` is supposed to work.

The crashes don't occur if you never cd into a directory with `.env`

Perhaps this is one for autoenv, rather than oh-my-zsh?

**Comment by jonathonf** [comment] 2015-10-08 16:50
I don't have `autoenv`. I do use `rbenv` and have used `rvm` previously, but no associated plugin is enabled.

**Comment by vwong** [comment] 2015-10-08 22:11
Wonder if it is an unrelated issue then?  I can't get reproduce your case!

**Comment by vwong** [comment] 2015-10-09 22:55
@jonathonf, you're right.  The clue is `allexport`.

Here's a snippet from autoenv's source..  You can see `allexport` being used.  

````
autoenv_source() {
  typeset allexport
  allexport=$(set +o | grep allexport)
  set -a
  source "$1"
  eval "$allexport"
}
````

I further experimented with autoenv and OMZ independently.  And found that autoenv without OMZ works fine, and OMZ without autoenv works fine, but the combination of autoenv and OMZ crashes. 

In other words, `allexport` plus OMZ is the likely the culprit.  Hope that narrows it down!

**Comment by apjanke** [comment] 2015-10-10 00:52
Now that's interesting. I wonder if that code is leaving `allexport` enabled by mistake when run under `zsh`. It looks like it's written for bash: there's a `#!/usr/bin/env bash` at the top. (Though this file is meant to be sourced, not run as a script, so the shebang shouldn't get used.)

Under bash, `set +o` reports the state of all options. Under zsh, I think `set +o` will only report the state of ones which have been changed from their default values. Which means that if `allexport` is off, `set +o | grep allexport` will be empty, `set -a` will turn on `allexport`, and then `eval "$allexport"`, which looks intended to restore the old state of `allexport`, will do nothing, and `allexport` will be left on.

```
$ set +o | grep export
$ autoenv_source no-such-file
autoenv_source:source:4: no such file or directory: no-such-file
$ set +o | grep export
set -o allexport
$
# now *everything* new gets exported, including everything from plugins loaded after autoenv
```

So once you activate a `virtualenv` by `cd`ing in to something with an `.env`, you could end up exporting a lot of stuff to the environment, which could cause problems. The environment is of limited size; it's not like the heap where you can just keep allocating more. I think it still shouldn't segfault - that's a bug; it should just report an out-of-space error for the environment, I think. But somewhat understandable.

The fix here might be to get the autoenv author to add a `zsh` portability fix there. (Just detecting `zsh` and doing an `emulate -L bash` should be sufficient.) It looks like this code is only in recent versions of autoenv (the Homebrew-installed release doesn't have it), so it might be ripe for fixing. Or the autoenv plugin could probably defend against this by wrapping the autoenv code in `emulate -L bash` wrappers. But that's a little fussier.

**Comment by vwong** [comment] 2015-10-10 11:17
@apjanke, thanks for that investigation.  My shell knowledge (bash or zsh) isn't good enough to suggest a fix.  Meanwhile, I've locally commented out all the `allexport` stuff in my copy of `autoenv` (I use a git checkout), and I no longer get crashes.

You're right though, ZSH should be robust enough to this sort of "abuse".

**Comment by achimnol** [comment] 2016-02-25 15:37
I just ran into the same issue, where my environment is Ubunt 15.10 amd64 + zsh 5.1.1 (installed via apt-get) + autoenv. Is there any workaround for this?
In my case, the plain user shell does not crash, but the sudo shell (`sudo -s`) does. (maybe there are some duplicate internal states when spawning a new sudo shell)

**Comment by glittershark** [comment] 2017-10-10 15:23
Has anyone reported this upstream yet? If so, could they link it here so I can follow that discussion?

**Comment by mbellgb** [comment] 2017-10-27 13:25
I started getting this bug after installing [RVM](https://rvm.io).

I've included omz_diagnostic_dump results, coredump and gdb backtrace in [this](https://gist.github.com/mbellgb/e151e6699b3b9be41befec6ccdd6b4c2) gist.

Hopefully this extra bit of data helps :)

**Comment by winny-** [comment] 2018-04-08 18:33
See also:

- sorin-ionescu/prezto#6
- rvm/rvm#4214
- https://www.zsh.org/mla/users/2018/msg00273.html

**Comment by mcornella** [comment] 2019-05-25 20:39
Even though this is really old, if any of you who happened to stumble into this bug can still reproduce it let me know. I couldn't reproduce it in any way I tried. In the meantime I'm closing this since we know the culprit and that it's an upstream bug.

@mbellgb your bug seems different. Try following https://github.com/rvm/rvm/issues/4214 instead.

**Closed by mcornella** 2019-05-25 20:39 UTC
Labels: Type: bug
