### ISSUE TITLE
Autocomplete doesn't update when new apt is installed or removed

### ISSUE THREAD

**Issue by maxjf1** [robbyrussell/oh-my-zsh#8314] opened 2019-10-24 20:01 UTC
**Describe the bug**
When an apt is added, the terminal doesn't update the autocomplete to check for the new command (it's ZSH only, because i tried bash and it works fine)

**To Reproduce**
I will use the package `colortest` as an example:

1. Install the package (`sudo apt install colortest`)
2. type `colorte` and Hit `TAB`. It should show `colortest-16, colortest-256`, etc, but it doesn't show nothing.
3. Close the terminal and open an new one and repeat STEP 2. Now it will work
4. Remove the package (`sudo apt purge colortest`)
5. Repeat the STEP 2. It will autocomplete the command, even with the package removed.
6. Repeat STEP 3, now it won't autocomplete the removed package. 

**Expected behavior**
It should update the autocomplete when packages are added and removed

**System:**
 - OS: Deepin 15.11 (Debian based)
 - zsh Version 5.3.1 (x86_64-debian-linux-gnu)
 - Terminal emulator Deepin Terminal V3.2.7.1

**Comment by keithbrianptomo** [comment] 2019-10-25 04:53
?

**Comment by mcornella** [comment] 2019-10-25 10:55
Duplicate of #3440. Run `rehash` (or `hash -rf`) after a command is installed so that commands in `$path` are scanned again. You can also add this setting but note that it comes with a possible performance cost: https://github.com/robbyrussell/oh-my-zsh/issues/3440#issuecomment-68165443.

**Closed by mcornella** 2019-10-25 10:55 UTC

**Comment by maxjf1** [comment] 2019-10-25 16:05
> Duplicate of #3440. Run `rehash` (or `hash -rf`) after a command is installed so that commands in `$path` are scanned again. You can also add this setting but note that it comes with a possible performance cost: [#3440 (comment)](https://github.com/robbyrussell/oh-my-zsh/issues/3440#issuecomment-68165443).

Thanks, but is there a reason that bash automatically updates and zsh don't?
