### ISSUE TITLE
duplicate or obsolete history options

### ISSUE THREAD

**Issue by warlorck** [robbyrussell/oh-my-zsh#5573] opened 2016-10-25 15:44 UTC
Hi everyone,

I'm new to github and this repo and I was wondering about few points while exploring the source code.

In the file _lib/history.zsh_:

``` zsh
HISTSIZE=10000
SAVEHIST=10000
```

First, we have the same value by default for those variables.
But the man says:

> You should be sure to set the value of HISTSIZE to a larger number than SAVEHIST in order to give you some room for the duplicated events, otherwise this option will behave just like HIST_IGNORE_ALL_DUPS  once  the  history fills up with unique events.

Another point:

``` zsh
setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups # ignore duplication command history list
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history # share command history data
```

Seems like **append_history** and **inc_append_history** duplicate.

Finally, the man says about **share_history**:

> This  option  both imports new commands from the history file, and also causes your typed commands to be appended to the history file (the latter is like specifying INC_APPEND_HISTORY, which should be turned off if this option is in effect).

What do you think?

**Comment by mcornella** [comment] 2018-04-22 13:40
> First, we have the same value by default for those variables.

> Seems like append_history and inc_append_history duplicate.

Both fixed in #3422.



> Finally, the man says about share_history:

In case `share_history` is disabled, `inc_append_history` will still work as intended, and it doesn't cause any harm to have it enabled, regardless of what the man says.

**Closed by mcornella** 2018-04-22 13:40 UTC
