### ISSUE TITLE
cask.plugin.zsh sourcing wrong path

### ISSUE THREAD

**Issue by deanishe** [robbyrussell/oh-my-zsh#3629] opened 2015-02-23 11:38 UTC
`cask.plugin.zsh` tries to source `/usr/local/etc/cask_completion.zsh`, but in my homebrew, it's located at `/usr/local/share/zsh/site-functions/cask_completion.zsh`.

Perhaps because I have `zsh-completions` installed?

At any rate, it'd be cool if the plugin checked that the file exists before sourcing it.

**Comment by apjanke** [comment] 2015-02-24 03:51
Kinda related. The `zsh-completions` probably isn't relevant... now. That `cask_completion.zsh` is part of the default homebrew Cask install.

    [@ in ~/.oh-my-zsh on ⇄ master]
    $ brew ls cask | grep completion
    /usr/local/Cellar/cask/0.7.2/share/zsh/site-functions/cask_completion.zsh

Since version 0.7.2, the zsh completions were removed from Cask added to the separate zsh-completion project. But since you installed it from homebrew, which is using release 0.7.2, you got the completions as part of Cask.

It looks like the issue is the homebrew vs non-homebrew installation of Cask. In the Cask distribution itself, the completions are in `etc/`. And that's where you find them if you do a non-homebrew installation of Cask. Homebrew keeps its zsh completion files for any formula under `/usr/local/share/zsh`, and that's where it links Casks' completion file during the installation. This changes the relative location of the completion files compared to where the `cask` executable ends up.

Sounds like the `cask` plugin was written based on a normal, non-Homebrew Cask installation, and isn't aware of the rearrangements that Homebrew makes. I suspect the solution is to check both the regular and Homebrew-specific locations for the zsh completions (including the `zsh-completion` version, since that's what will provide it as of Cask's next release) for the file. @akatov, looks like you're the Cask plugin author. Can you comment on this?

**Comment by apjanke** [comment] 2015-02-24 16:57
(Note for newbies like myself: this is an issue with the interaction of [Homebrew](http://brew.sh/) and the emacs tool [Cask](http://cask.readthedocs.org/en/latest/), which is unrelated to  [Homebrew cask](http://caskroom.io/), a Homebrew extension for managing UI apps.)

**Comment by mcornella** [comment] 2016-08-25 16:37
Merged on f258083.

**Closed by mcornella** 2016-08-25 16:37 UTC
