### ISSUE TITLE
parse error near `then'

### ISSUE THREAD

**Issue by babolivier** [robbyrussell/oh-my-zsh#4067] opened 2015-06-19 08:57 UTC
Hi,

Since the last time I updated oh-my-zsh, I always get this error whenever I open a new terminal: 

`/home/brendan/.oh-my-zsh/lib/misc.zsh:3: parse error near 'then'`

**Comment by tailer35** [comment] 2015-06-19 09:30
Same here.

**Comment by ZhaoMiing** [comment] 2015-06-19 12:50
just run ```upgrade_oh_my_zsh``` and it fixed

**Comment by tailer35** [comment] 2015-06-19 13:43
nope

**Comment by apjanke** [comment] 2015-06-19 15:26
Duplicate of #4034. The Jira error is a duplicate of #4027.

Could you close this and report under those original bugs if you're still having the issue?

**Closed** 2015-07-06 16:33 UTC
