### ISSUE TITLE
git error

### ISSUE THREAD

**Issue by qiulin** [robbyrussell/oh-my-zsh#4059] opened 2015-06-18 03:04 UTC
I got a wired git error, after I updated my oh-my-zsh today.

    [.oh-my-zsh]                                             11:00:29  ☁  599831b ☀
    git_prompt_ahead:1: command not found: current_branch

I searched, and found this issue #1166, but it doesn't work for me.

ps. My OS is Mac OSX Yosemite.

**Comment by ncanceill** [comment] 2015-06-18 06:14
Are you using custom files? Since a28dbc83937cbe624ec726199b4bbe7b65b2b2a0, custom files are loaded before plugins.

**Comment by apjanke** [comment] 2015-06-23 19:32
Possible dupe of #4084.

Do you have the `git` plugin loaded? If not, then some themes will break like this because some of the theme-related functions in `lib/git.zsh` depend on `current_branch()`, but `current_branch()` is only defined in the `git` plugin.

**Closed** 2015-12-02 13:45 UTC
