### ISSUE TITLE
Completion moves the current line up deleting older command output 

### ISSUE THREAD

**Issue by lezed1** [robbyrussell/oh-my-zsh#3396] opened 2014-12-11 23:24 UTC
I am running the latest Oh My Zsh on Ubuntu 14.04. Here is a screenshot of the bug.

From left to right, then top to bottom: Normal command output, start one auto completion, start and finish one auto completion, start and finish one auto completion and then start another.

![image](https://cloud.githubusercontent.com/assets/2121068/5404208/76ae6042-8162-11e4-82c3-621d247c0ac2.png)

If more command had been completed, the terminal would completely overwrite everything.

**Comment by mcornella** [comment] 2015-02-21 22:44
**TL;DR** you're implementation of the multiline prompt is buggy. What theme are you using? I recall having problems of that sort but I'd have to freshen up on my multiline prompt knowledge...

**Comment by lezed1** [comment] 2015-02-21 22:57
I actually created my own theme based off of the [josh](https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/josh.zsh-theme) theme. The modified version is here: http://paste.ubuntu.com/10347952/

The same bug happens on the original josh theme, but does not happen another another randomly chosen multiline prompt (candy). I'll update my theme to be based off of candy.

Thank you for your help! I think there is a bug to be addressed here, at the very least the josh theme is buggy, so I'll leave this issue open.

**Comment by mcornella** [comment] 2015-02-21 23:24
I had to mess around that when I was modifying a theme from Nettuts+. I remember it took me a long time to figure out, and a lot of googling around. As I said, I don't remember what worked exactly, but you can take a look at [my current theme](https://github.com/mcornella/oh-my-zsh/blob/dev/custom/themes/doubleend.zsh-theme) and compare.

**Comment by apjanke** [comment] 2015-04-01 04:04
I'm unable to reproduce, with either the `josh` theme, or the one you posted at http://paste.ubuntu.com/10347952/. I set up a fresh oh-my-zsh installation for a user on Ubuntu 14.04, added that to my custom themes, and did autocompletion in the terminal using both themes, but never saw the text-moving-upward behavior.

Is this still happening?

Maybe it was a setting from `.zshrc` or somewhere outside the theme definition that was causing it?

**Comment by jsirex** [comment] 2017-02-23 15:04
I'm having the same issue using any "multi-line" theme
zsh 5.3.1 (x86_64-debian-linux-gnu)

**Comment by jsirex** [comment] 2017-02-23 15:36
UPD: I've found  this - https://github.com/robbyrussell/oh-my-zsh/issues/5767
And this is my case - turning off dots fixes issue

**Comment by mcornella** [comment] 2019-04-07 13:12
Ok, closing this as the culprit is COMPLETION_WAITING_DOTS.

**Closed by mcornella** 2019-04-07 13:12 UTC
