### ISSUE TITLE
deactivate:unset:1: no such hash table element: pydoc

### ISSUE THREAD

**Issue by Namita26** [robbyrussell/oh-my-zsh#4861] opened 2016-02-20 08:45 UTC
I have upgraded oh my zsh to the latest version. Still, when I activate my virtual environment, I get this line after opening a new terminal or tab. Please suggest a solution.

**Comment by apjanke** [comment] 2016-02-21 07:33
Which OMZ plugins are you using, and which version of virtualenv are you running?

**Comment by Namita26** [comment] 2016-02-22 05:38
I am using virutalenv==14.0.1 and zsh 5.0.2 (x86_64-pc-linux-gnu).

**Comment by aaronireland** [comment] 2016-02-25 03:29
I'm experiencing this too.
I'm running virtualenv version 14.1.0.dev0 and zsh 5.0.8 (x86_64-apple-darwin15.0)
plugins=(git brew dirhistory docker history jsontools pylint python virtualenvwrapper)

**Comment by spapanik** [comment] 2016-04-14 09:13
This bug has nothing to do with zsh, the problem is with virtualenv. It is fixed in version 15.0.0, but it will persist for venvs created with an earlier venv. You can change in the deactivate function the line ```unset -f pydoc``` to ```unset -f pydoc >/dev/null 2>&1```.

**Closed** 2018-05-09 15:56 UTC
