### ISSUE TITLE
Error after upgrading

### ISSUE THREAD

**Issue by levisbakalinsky** [robbyrussell/oh-my-zsh#4034] opened 2015-06-15 13:23 UTC
Upgraded last night to the latest version, and received the following error:

/Users/levisbakalinsky/.oh-my-zsh/lib/misc.zsh:3: parse error near `then'

zsh 5.0.8 (x86_64-apple-darwin14.3.0)

**Comment by alvincrespo** [comment] 2015-06-15 13:26
:+1: Getting this as well

**Comment by oshybystyi** [comment] 2015-06-15 13:29
the [pr for this](https://github.com/robbyrussell/oh-my-zsh/pull/4002), it will be merged soon.

**Comment by nick4fake** [comment] 2015-06-15 13:54
Same here.

why there is no "stable" branch?

**Comment by ncanceill** [comment] 2015-06-15 14:35
This was already reported multiple times and the fix should be merged ASAP.

@nick4fake currently our upgrade process is very poor but we will be working on it in the near future.

**Comment by tehmaspc** [comment] 2015-06-15 15:56
duplicate of https://github.com/robbyrussell/oh-my-zsh/pull/4002

please close.

**Comment by ncanceill** [comment] 2015-06-15 21:25
This should be fixed now, @levisbakalinsky please confirm and close.

**Closed** 2015-07-06 16:33 UTC
