### ISSUE TITLE
Error beeps and echoing of the last command in ZOC

### ISSUE THREAD

**Issue by dandv** [robbyrussell/oh-my-zsh#3331] opened 2014-11-19 07:22 UTC
How to reproduce:

1. git clone https://github.com/reciprocity/ggrc-core
2. librarian-chef install; vagrant up; vagrant ssh  # precise64 box
3. ssh into the machine using [ZOC](https://en.wikipedia.org/wiki/ZOC_(software))
4. sudo apt-get install zsh
5. passwd  # set it to something
6. chsh -s $(which zsh) vagrant
7. curl -L http://install.ohmyz.sh | sh
8. re-login

Now, type some commands and notice how they're echoes before execute. Additionally, the terminal beeps in about half the cases. I've been using ZOC for 5+ years and never had this problem.

![image](https://cloud.githubusercontent.com/assets/33569/5102100/bbd1d140-6f79-11e4-9eea-96f367f80469.png)

**Comment by mcornella** [comment] 2015-02-10 22:16
Can you check again after upgrading oh-my-zsh? It might be a bug in how oh-my-zsh sets the encoding to utf-8...

**Comment by dandv** [comment] 2015-02-11 06:32
Yep, still beeps and odd characters:

![image](https://cloud.githubusercontent.com/assets/33569/6142909/947a7d44-b174-11e4-8a8a-bee9e410ba68.png)

**Comment by mcornella** [comment] 2015-02-11 06:36
Try again after restarting the terminal. If it still fails, please post the output of `locale` and `infocmp`.

**Comment by dandv** [comment] 2015-02-11 06:40
Opened a new tab in ZOC; still beeps.

```
~$ zsh
➜  ~
➜  ~
➜  ~
➜  ~
➜  ~
➜  ~
➜  ~
➜  ~  locale
;localeLANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
➜  ~  infocmp
;infocmp#       Reconstructed via infocmp from file: /lib/terminfo/x/xterm
xterm|X11 terminal emulator,
        am, bce, km, mc5i, mir, msgr, npc, xenl,
        colors#8, cols#80, it#8, lines#24, pairs#64,
        acsc=``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
        bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
        clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=^M,
        csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
        cud=\E[%p1%dB, cud1=^J, cuf=\E[%p1%dC, cuf1=\E[C,
        cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
        cvvis=\E[?12;25h, dch=\E[%p1%dP, dch1=\E[P, dl=\E[%p1%dM,
        dl1=\E[M, ech=\E[%p1%dX, ed=\E[J, el=\E[K, el1=\E[1K,
        flash=\E[?5h$<100/>\E[?5l, home=\E[H, hpa=\E[%i%p1%dG,
        ht=^I, hts=\EH, ich=\E[%p1%d@, il=\E[%p1%dL, il1=\E[L,
        ind=^J, indn=\E[%p1%dS, invis=\E[8m,
        is2=\E[!p\E[?3;4l\E[4l\E>, kDC=\E[3;2~, kEND=\E[1;2F,
        kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D, kNXT=\E[6;2~,
        kPRV=\E[5;2~, kRIT=\E[1;2C, kb2=\EOE, kbs=\177, kcbt=\E[Z,
        kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
        kdch1=\E[3~, kend=\EOF, kent=\EOM, kf1=\EOP, kf10=\E[21~,
        kf11=\E[23~, kf12=\E[24~, kf13=\E[1;2P, kf14=\E[1;2Q,
        kf15=\E[1;2R, kf16=\E[1;2S, kf17=\E[15;2~, kf18=\E[17;2~,
        kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~, kf21=\E[20;2~,
        kf22=\E[21;2~, kf23=\E[23;2~, kf24=\E[24;2~,
        kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R, kf28=\E[1;5S,
        kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~, kf31=\E[18;5~,
        kf32=\E[19;5~, kf33=\E[20;5~, kf34=\E[21;5~,
        kf35=\E[23;5~, kf36=\E[24;5~, kf37=\E[1;6P, kf38=\E[1;6Q,
        kf39=\E[1;6R, kf4=\EOS, kf40=\E[1;6S, kf41=\E[15;6~,
        kf42=\E[17;6~, kf43=\E[18;6~, kf44=\E[19;6~,
        kf45=\E[20;6~, kf46=\E[21;6~, kf47=\E[23;6~,
        kf48=\E[24;6~, kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q,
        kf51=\E[1;3R, kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
        kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
        kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
        kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
        kf8=\E[19~, kf9=\E[20~, khome=\EOH, kich1=\E[2~,
        kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
        kri=\E[1;2A, mc0=\E[i, mc4=\E[4i, mc5=\E[5i, meml=\El,
        memu=\Em, op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM,
        rin=\E[%p1%dT, rmacs=\E(B, rmam=\E[?7l, rmcup=\E[?1049l,
        rmir=\E[4l, rmkx=\E[?1l\E>, rmso=\E[27m, rmul=\E[24m,
        rs1=\Ec, rs2=\E[!p\E[?3;4l\E[4l\E>, sc=\E7,
        setab=\E[4%p1%dm, setaf=\E[3%p1%dm,
        setb=\E[4%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m,
        setf=\E[3%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m,
        sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
        sgr0=\E(B\E[m, smacs=\E(0, smam=\E[?7h, smcup=\E[?1049h,
        smir=\E[4h, smkx=\E[?1h\E=, smso=\E[7m, smul=\E[4m,
        tbc=\E[3g, u6=\E[%i%d;%dR, u7=\E[6n, u8=\E[?1;2c, u9=\E[c,
        vpa=\E[%i%p1%dd,
➜  ~
```

BTW you can get a trial version of ZOC for free at http://www.emtec.com/download.html. I've been using it for years; it's great.

**Comment by mcornella** [comment] 2015-02-11 06:44
Maybe it's the autotitle functionality, try running `DISABLE_AUTO_TITLE=true`

**Comment by dandv** [comment] 2015-02-11 07:51
That works! No more beeps or odd characters.

**Comment by mcornella** [comment] 2015-02-11 13:31
Ok, try running `print -Pn "\e]2;a:q\a"` and `print -Pn "\e]1;a:q\a" to see which one beeps.

**Comment by apjanke** [comment] 2015-07-05 08:32
I can reproduce with ZOC 7.05.0 on OS X. Looks like it supports the "\e]2;$name\a" window title sequence but not the print -Pn "\e]1;$name\a" icon title; that one causes a beep and normal text to be echoed to the screen.

Looks like we could add a workaround to this by detecting ZOC using the ZOCINSTANCE environment variable it sets. Use that to turn off the icon setting attempt.

```
➜  ~  set | grep -i -a zoc
ZOCINSTANCE=1                  
```

**Comment by mgoemmel** [comment] 2015-07-07 10:53
Hello!

A user made us aware of the problem (and these posts) and we were just looking into it.  

apjanke is right, we currently (as of 7.05.0 and earlier) ignore the 1; sequence and redirect it to the screen.  This will be fixed in the next ZOC release (7.05.1 or 7.06.0) with about the next 4 weeks.

Btw, in Options>Program Settings>Tabs, there is an option that will allow/prevent the change of tab title.  It currently needs to be enabled to allow the 2; sequence to change the tab title as well.

Thanks

Markus Goemmel
(Co-Developer of ZOC)

**Comment by apjanke** [comment] 2015-07-07 17:57
Excellent. Thanks for being responsive.

While it would probably be nice to have independent tab control, I think it's probably more important for compatibility that ZOC detect and swallow *all* "OSC" sequences, not just the ones it implements functionality for. Basically, an xterm will treat any sequence of the form `\e]Ps;Pt\a` as a control sequence meant for the terminal, and not to be displayed on the screen. (Where `\e` is ESC, `Ps` is any number, `Pt` is any string of printable characters, and `\a` is BEL.)

For example, in iTerm2, OS X `xterm`, and Terminal.app, you can do this with any number, and you won't get visible junk on the screen.

```
➜  ~  printf "\e]0;whatever\a"
➜  ~  printf "\e]1;whatever\a"
➜  ~  printf "\e]2;whatever\a"
➜  ~  printf "\e]9;whatever\a"
➜  ~  printf "\e]12345;whatever\a"
➜  ~  printf "\e]999999999;whatever\a"
```

(That `\a` is a literal ASCII BEL character, which is why the terminal beeps when this stuff gets echoed to the screen.)

I sent your colleague Markus Schmidt a detailed email about this.

OMZ folks, if there's a fix for this coming out soon, and the `DISABLE_AUTO_TITLE=false` workaround works, let's not put in any special cases for ZOC in the OMZ code.

**Comment by mcornella** [comment] 2016-01-16 10:26
Do we have any updates to this? Was ZOC updated to handle this?

**Comment by mgoemmel** [comment] 2016-01-18 11:31
Marc,

I'm not sure what the status of this is, but I remember some changes 
about "zsh".

Our version 7.05.0 has a version entry which I think was related to it:

   xterm icon title request now changes tab title (requires option from 
program settings > tabs)

If you still have specific problems after this version, feel free to 
email me directly.

Regards


Markus Schmidt



Telnet, SSH, Modem ... our product ZOC will do it all (and more).


EmTec, Innovative Software
http://www.emtec.com/
m.schmidt@emtec.com
Phone: +49 911 7406856
Mobile: +49 171 2350608
Fax: + 49 911 7406857

**Comment by mcornella** [comment] 2016-01-18 14:19
Ok thanks Markus, I'm closing this then. If a problem like this happens again we'll add a special case for ZOC. Cheers!

**Closed by mcornella** 2016-01-18 14:19 UTC
