### ISSUE TITLE
command not found: __git_aliased_command

### ISSUE THREAD

**Issue by azer** [robbyrussell/oh-my-zsh#4553] opened 2015-10-27 21:39 UTC
Fresh install breaks git auto-completion, and causes terminal to crash. 

![](https://cldup.com/aGNJNnpGl6.png)

**Comment by apjanke** [comment] 2015-10-31 19:08
Looks like something going wrong with the `gitfast` plugin. Possibly that the `git-completion.bash` script is not getting sourced.

```
$ grep -r git_zsh_bash_func *
plugins/gitfast/_git:__git_zsh_bash_func ()
plugins/gitfast/_git:		__git_zsh_bash_func $command
$ grep -r git_aliased_command *
plugins/gitfast/_git:	local expansion=$(__git_aliased_command "$command")
plugins/gitfast/git-completion.bash:# __git_aliased_command requires 1 argument
plugins/gitfast/git-completion.bash:__git_aliased_command ()
plugins/gitfast/git-completion.bash:	local expansion=$(__git_aliased_command "$command")
$
```

I can't reproduce on my OS X 10.9.5 box. What OS and theme are you using?

Could you run `omz_diagnostic_dump` and post the results [as a gist](https://gist.github.com/) so we can get debugging info for this?

**Comment by mcornella** [comment] 2015-12-02 00:34
Closing for the time being for not responding. Reopen if necessary.

**Comment by tdyer-aio** [comment] 2015-12-02 17:01
im not running gitfast, but here is a omz_diagdump for you to look at: https://gist.github.com/tdyer-aio/b3e8d9f794b521f2fd81

**Comment by tdyer-aio** [comment] 2015-12-02 17:02
also, this seems like it may be related to a recent upgrade to `el capitan`.

**Comment by apjanke** [comment] 2015-12-02 17:23
Interesting. I had thought the problem was confined to the `gitfast` plugin. Will take another shot at reproducing this on el cap.

**Comment by apjanke** [comment] 2015-12-02 17:24
@mcornella or @azer, can you reopen this issue since we have another lead and report of ongoing breakage?

**Comment by tdyer-aio** [comment] 2015-12-02 18:56
```
➜  .oh-my-zsh git:(master) ✗ grep -r __git_aliased_command *
plugins/gitfast/_git:	local expansion=$(__git_aliased_command "$command")
plugins/gitfast/git-completion.bash:# __git_aliased_command requires 1 argument
plugins/gitfast/git-completion.bash:__git_aliased_command ()
plugins/gitfast/git-completion.bash:	local expansion=$(__git_aliased_command "$command")
➜  .oh-my-zsh git:(master) ✗ 
```

**Comment by azer** [comment] 2015-12-02 20:32
I disabled git autocomplete plugin and things began working again. I think zsh is conflicting with manually installed git autocomplete plugin.

**Comment by mcornella** [comment] 2018-06-18 18:19
Is this still relevant? @azer when you say `git autocomplete plugin` you mean `gitfast`?

**Closed by mcornella** 2018-06-18 18:19 UTC
