### ISSUE TITLE
PROMPT for git repository is low on big repo

### ISSUE THREAD

**Issue by jonnyzzz** [robbyrussell/oh-my-zsh#5837] opened 2017-02-01 18:12 UTC
On macOS with latest Git and latest oh-my-zsh
On https://github.com/JetBrains/intellij-community repository checkout. It took about a second for the shell to write prompt after I press enter.

**Comment by nonchip** [comment] 2017-06-03 22:39
quote from `~/.zshrc`:

    # Uncomment the following line if you want to disable marking untracked files
    # under VCS as dirty. This makes repository status check for large repositories
    # much, much faster.
    # DISABLE_UNTRACKED_FILES_DIRTY="true"

**Comment by Jahhein** [comment] 2017-06-04 04:33
Further elaborating on @nonchip response..

The repository is very large and your prompt will only be as fast as your computer can process checking all the files for changes.

**Comment by nonchip** [comment] 2017-06-04 08:19
what @Jahhein said. there's simply no way your repository can be auto-checked faster without disabling some of the functionality (so it just asks git instead of actively scanning) because some repos are just too big. happens for me with the epicgames/unrealengine repo, where it can take up to a minute with untracked files checking.

**Comment by Jahhein** [comment] 2017-06-04 09:20
And some more information to help inform anyone reading.. Those git prompts have to check all the files in the git repository directory after every set of commands your run to unsure they prompt is correct.

**Comment by dyatlov** [comment] 2018-12-13 10:03
Solution is to go to your theme file in `~/.oh-my-zsh/themes/`, find there prompt_git() function and replace there:

```
zstyle ':vcs_info:*' check-for-changes true
```

with

```
zstyle ':vcs_info:*' check-for-changes false
```

Also, you should add the following line to git config so that dirtyness wont be checked:

```
git config --add oh-my-zsh.hide-dirty '"1"'
```

**Comment by mcornella** [comment] 2019-04-09 11:18
Duplicate of #3009. See solutions there.

**Closed by mcornella** 2019-04-09 11:18 UTC
