### ISSUE TITLE
Rename rg alias from rails plugin (conflict with ripgrep)

### ISSUE THREAD

**Issue by stevensonmt** [robbyrussell/oh-my-zsh#6972] opened 2018-07-08 14:27 UTC
In the rails plugin please remove or rename the "rg" alias for rails generate as it overrides the CLI command for [rip-grep](https://github.com/BurntSushi/ripgrep).

**Comment by hjpotter92** [comment] 2018-07-19 07:29
Yes. Although I've now gotten used to using `\rg` for rip-grep...

**Comment by mcornella** [comment] 2018-08-09 19:54
You can `unalias rg` to delete the alias. If more people have this problem I'll consider renaming it to `rge`.

**Comment by stevensonmt** [comment] 2018-08-11 15:33
Yes that's what I've been doing. It's just mildly annoying to have to do it every new session.

**Comment by mcornella** [comment] 2018-08-11 16:02
You can just put it in your zshrc file.

**Comment by jounathaen** [comment] 2018-09-27 15:58
Probably a duplicate of #6385

**Comment by mcornella** [comment] 2018-09-27 17:09
Follow the discussion there, thanks.

**Closed by mcornella** 2018-09-27 17:09 UTC
