### ISSUE TITLE
Cannot using home/end key after install oh-my-zsh

### ISSUE THREAD

**Issue by linlinlinlin** [robbyrussell/oh-my-zsh#3061] opened 2014-08-26 15:05 UTC
I using a pure Ubuntu:14.04 env.
After I install oh-my-zsh by curl.
I cannot using home/end key anymore.
I didn't change any settings in .oh-my-zsh folder.

**Comment by damijanc** [comment] 2015-04-13 14:31
I can confirm that keys HOME and END do not work on MACOS Yosemite 10.10.3. Home key scrolls the console screen to the first line of output and End scrolls to the last line on output.

**Comment by ncanceill** [comment] 2015-04-13 15:31
This looks similar to #3757.

Before discussing this any further, it would be nice to figure out, in that order:
- what you guys think the behavior of Home and End keys should be;
- what exactly is happening instead;
- and why.

***

For those of you who think it should work (Home to the beginning of line, End to the end of line), it probably depends on your OS/desktop-env/term-emulator.

Vanilla Zsh does not provide any binding for the Home and End keys. FYI, the usual terminal shortcuts for beginning and end of line are respectively Ctrl+A and Ctrl+E.

For instance, the behavior @damijanc is experiencing is correct. Jumping to beginning or end of terminal output is what Home and End are supposed to do in default-configured Terminal.app with vanilla Zsh and OMZ without plugins.

If you really want Home and End to move the cursor to the beginning or end of line, you can use the settings of your terminal emulator to bind them to ^A and ^E.

***

For those of you who used to have it working but do not anymore, then if it is OMZ's fault it means the behavior was broken by a particular update. In that case, please help us tracking that update down, using `git bisect` or something.

**Comment by jgrar** [comment] 2015-04-14 13:31
@ncanceill It appears OMZ sets home and end keys to behave this way by default: https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/key-bindings.zsh#L37

However, those keys may not be set in `$terminfo` which could be leading to the trouble here. It's worth any user experiencing this problem to run `autoload zkbd` and go through the steps in `zkbd`. Source the file generated and then bind them how you want. 

Speaking of which; does OMZ load files from `~/.zkbd/` ?

@damijanc could you provide output of `infocmp` please?

**Comment by linlinlinlin** [comment] 2015-04-14 13:45
It's my infocmp

      #	Reconstructed via infocmp from file: /lib/terminfo/x/xtermxterm|xterm-debian|X11 terminal emulator,	am, bce, km, mc5i, mir, msgr, npc, xenl,
	colors#8, cols#80, it#8, lines#24, pairs#64,
	acsc=``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
	bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
	clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=^M,
	csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
	cud=\E[%p1%dB, cud1=^J, cuf=\E[%p1%dC, cuf1=\E[C,
	cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
	cvvis=\E[?12;25h, dch=\E[%p1%dP, dch1=\E[P, dl=\E[%p1%dM,
	dl1=\E[M, ech=\E[%p1%dX, ed=\E[J, el=\E[K, el1=\E[1K,
	flash=\E[?5h$<100/>\E[?5l, home=\E[H, hpa=\E[%i%p1%dG,
	ht=^I, hts=\EH, ich=\E[%p1%d@, il=\E[%p1%dL, il1=\E[L,
	ind=^J, indn=\E[%p1%dS, invis=\E[8m,
	is2=\E[!p\E[?3;4l\E[4l\E>, kDC=\E[3;2~, kEND=\E[1;2F,
	kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D, kNXT=\E[6;2~,
	kPRV=\E[5;2~, kRIT=\E[1;2C, kb2=\EOE, kbs=\177, kcbt=\E[Z,
	kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
	kdch1=\E[3~, kend=\EOF, kent=\EOM, kf1=\EOP, kf10=\E[21~,
	kf11=\E[23~, kf12=\E[24~, kf13=\E[1;2P, kf14=\E[1;2Q,
	kf15=\E[1;2R, kf16=\E[1;2S, kf17=\E[15;2~, kf18=\E[17;2~,
	kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~, kf21=\E[20;2~,
	kf22=\E[21;2~, kf23=\E[23;2~, kf24=\E[24;2~,
	kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R, kf28=\E[1;5S,
	kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~, kf31=\E[18;5~,
	kf32=\E[19;5~, kf33=\E[20;5~, kf34=\E[21;5~,
	kf35=\E[23;5~, kf36=\E[24;5~, kf37=\E[1;6P, kf38=\E[1;6Q,
	kf39=\E[1;6R, kf4=\EOS, kf40=\E[1;6S, kf41=\E[15;6~,
	kf42=\E[17;6~, kf43=\E[18;6~, kf44=\E[19;6~,
	kf45=\E[20;6~, kf46=\E[21;6~, kf47=\E[23;6~,
	kf48=\E[24;6~, kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q,
	kf51=\E[1;3R, kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
	kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
	kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
	kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
	kf8=\E[19~, kf9=\E[20~, khome=\EOH, kich1=\E[2~,
	kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
	kri=\E[1;2A, mc0=\E[i, mc4=\E[4i, mc5=\E[5i, meml=\El,
	memu=\Em, op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM,
	rin=\E[%p1%dT, rmacs=\E(B, rmam=\E[?7l, rmcup=\E[?1049l,
	rmir=\E[4l, rmkx=\E[?1l\E>, rmso=\E[27m, rmul=\E[24m,
	rs1=\Ec, rs2=\E[!p\E[?3;4l\E[4l\E>, sc=\E7,
	setab=\E[4%p1%dm, setaf=\E[3%p1%dm,
	setb=\E[4%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m,
	setf=\E[3%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m,
	sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
	sgr0=\E(B\E[m, smacs=\E(0, smam=\E[?7h, smcup=\E[?1049h,
	smir=\E[4h, smkx=\E[?1h\E=, smso=\E[7m, smul=\E[4m,
	tbc=\E[3g, u6=\E[%i%d;%dR, u7=\E[6n, u8=\E[?1;2c, u9=\E[c,
	vpa=\E[%i%p1%dd,

**Comment by jgrar** [comment] 2015-04-15 01:57
@linlinlinlin In your case this seems to be a common issue with putty, can you provide the terminal type string that putty is configured to use? Does following this http://superuser.com/a/104016 help?

**Comment by linlinlinlin** [comment] 2015-04-15 15:29
@jgrar  In putty, I try to set  Terminal-type from **xterm** to  **putty**. It works.

But actually I am using **XShell** on Windows. Terminal-type options in XShell are *xterm/vt100/vt102/vt220/vt320/linux/scoansi/ansi*. I do not know what should I type for XShell.

Few more questions: 
 * Why does bash didn't have to change terminal-type on client side?
 * is it possible to modify settings on server to solve this issue? Instead of change client options in every client side.

**Comment by jgrar** [comment] 2015-04-15 17:36
@linlinlinlin 
 
* As per my understanding, setting the type to *linux* should work, if it doesn't could you try all of them and report back?
 * I don't know what bash does differently to zsh in this regard but I'm looking into it
 * The terminal type string that the client gives the server indicates which terminfo database is to be used, so you need to make sure you're setting your client up correctly, in this case providing the best terminal type string.

In my opinion; if using bash in putty maps keys as you'd expect but using ZSH & OMZ in putty doesn't (can you confirm that?), then we can compare the difference at these two points and should be able come up with a fix. I'm investigating it at the moment because I have my own similar issue with mosh and ZSH & OMZ, but it would be a great help if others can join in and give more detail.

**Comment by linlinlinlin** [comment] 2015-04-19 11:36
If I change to *linux* in Xshell software, it works for home/end key but the shell color getting weird. So, I change back to default *xterm*.

![linux](https://cloud.githubusercontent.com/assets/8558312/7218901/b16ecfee-e6b8-11e4-8616-d986774c0605.png)

if using bash in putty maps keys as you'd expect but using ZSH & OMZ in putty doesn't.
* Confirmed.

**Comment by hu6360567** [comment] 2015-05-14 03:14
When I change to bash, the HOME/END key works fine, but oh-my-zsh not.
My SSH Client is Xshell

**Comment by donnykurnia** [comment] 2015-07-08 04:58
I have same problem and fixed with this answer: http://superuser.com/a/104001/24760

**Comment by candrew34** [comment] 2015-08-31 07:33
@linlinlinlin This problem by default zsh does not have key bindings for Home and End keys. Try using the following commands to set bindings:

bindkey "\033[1~" beginning-of-line
bindkey "\033[4~" end-of-line

**Comment by linlinlinlin** [comment] 2015-09-01 02:23
What is the reason does not set these bindkey as default in zsh?

Also, I have to set keypad bindkey by myself:
```
# Keypad
# 0 . Enter
bindkey -s "^[Op" "0"
bindkey -s "^[Ol" "."
bindkey -s "^[OM" "^M"
# 1 2 3
bindkey -s "^[Oq" "1"
bindkey -s "^[Or" "2"
bindkey -s "^[Os" "3"
# 4 5 6
bindkey -s "^[Ot" "4"
bindkey -s "^[Ou" "5"
bindkey -s "^[Ov" "6"
# 7 8 9
bindkey -s "^[Ow" "7"
bindkey -s "^[Ox" "8"
bindkey -s "^[Oy" "9"
# + -  * /
bindkey -s "^[Ok" "+"
bindkey -s "^[Om" "-"
bindkey -s "^[Oj" "*"
bindkey -s "^[Oo" "/"


```

**Comment by eskohen** [comment] 2015-10-14 21:00
This is certainly related to oh-my-zsh themes, and not oh-my-zsh directly.  

Observations:
Home/End Keys work fine in: Vanilla ZSH and robbyrussel work fine.
Using Bitvise SSH client, and gnome-terminal &

Issues:
For example, the:POWERLEVEL9K theme does not work in this way.

**Comment by ncanceill** [comment] 2015-10-16 20:29
Hum, this is starting to go very wide.

I think we need to exhibit a clean configuration procedure to reproduce the issue.

**Comment by mickk-on-cpp** [comment] 2015-10-19 05:50
@ncanceill For me on Ubuntu 15.04 with gnome-terminal, if I have an entirely empty `.zshrc` (i.e. not even pointing to omz) then Home/End 'work', by which I mean I have the following:

    $ bindkey $key[Home]
    "^[OH" beginning-of-line
    $ bindkey $key[End] 
    "^[OF" end-of-line

and using Home/End does move the cursor to the beginning/end of line. If on the other hand `.zshrc` solely consists of:

    function zle-line-init {} # Note absence of `zle -N zle-line-init`

then `bindkey` reports the same, but using Home/End does not move the cursor. In practice this means that using a plugin which sets or requires `zle-line-init` to be set (e.g. vi-mode, or external plugin zsh-autosuggestions) prevents me from using Home/End.

**Comment by JimmyAx** [comment] 2015-10-20 20:27
I can confirm that the home/end buttons are breaking with a `.zshrc` as @mickk-on-cpp  described. It was tested by starting zsh with `ZDOTDIR=/the/new/dir/ zsh` and only a `.zshrc` in that folder with this:
```zsh
function zle-line-init {}
```

In my zsh installation it also broke the history searching when tapping the up button and having written some command already. For example having run `adb devices`, running some other non-`adb` commands in-between and then writing `ad` and hitting the up button would auto-complete to `adb devices`. (I don't know what plugin is doing this.) If I disabled the theme I use ([bhilburn/powerlevel9k](https://github.com/bhilburn/powerlevel9k)) then it would suddenly work again. I found this bug after doing a `git bisect` and ending up with [bhilburn/powerlevel9k@b31d0f](https://github.com/bhilburn/powerlevel9k/commit/b31d0ff3950c091cb5f0aa34abc664a4790affc8) as the commit that broke it. Not sure if this is a bug in zsh, oh-my-zsh or powerlevel9k (if it even is a bug and not a feature).

I use Konsole 5 on Debian Stretch.

**Comment by dritter** [comment] 2015-10-27 14:39
This is related to https://github.com/bhilburn/powerlevel9k/issues/131. I hope #2735 fixes that, but I haven't got time to check that.

**Comment by ncanceill** [comment] 2015-10-29 13:23
Thanks @mickk-on-cpp, I will try to look into it this week-end.

**Comment by apjanke** [comment] 2015-10-30 18:26
Yeah, this sure looks like the "keypad transmit" aka "application" mode (`smkx`/`rmkx`) issue from #2735: the code setting up the key bindings, and the code controlling the terminal behavior during ZLE line editing have different expectations about what character sequences the keypad keys will be sending. (And @dritter, yes, I believe #4191 or #4192 will fix this for you.)

It's a bug in the overall system setup, but it's hard to pinpoint exactly where the bug lies: the problem is getting several layers of a complicated, finicky system all in sync. (And the original cause is a series of unfortunate design choices and historical bugs going all the way back to the original terminals of the '70s.) And for OMZ/zsh, we want to get it in sync not just for one computer, but in a portable, reproducible way that works across multiple machines and operating systems.

The system configuration needs to determine whether keypad transmit mode is going to be used during ZLE editing, and configure everything to be consistent with that. OMZ has been heading toward "yes" the past couple years, and Zsh itself seems to have settled on that, based on their developer mailing list activity. I think that's the right answer, too, because that's what makes it work with `terminfo`, which lets you define key bindings portably across different terminals and operating systems (and is more readable). What makes it difficult is that not everybody agrees, or even understands the problem in the same way. And that goes all the way up to distribution packagers: OpenSUSE doesn't even recognize the transmit vs local mode distinction for some of the term definitions they ship.

I think @ncanceill is right: this goes really wide, and needs to be settled by considering all the related issues at once, instead of doing quick fixes for each. Have a look at #4344, the terminal-related tracking issue. I think that literally at least a dozen of the issues listed there are variants of this one, having to do with keypad transmit mode and closely related terminal settings. We probably need to decide on a behavior, get everything consistent in OMZ, and then document this in a Wiki page for future reference.

### Debugging Notes ###

Folks, when you're trying to reproduce, an empty `~/.zshrc` is not enough to get a "clean" shell session. There are also system-level `/etc/z*` files that set up key bindings and terminal behavior, and these vary widely between systems in ways that will affect this issue. (E.g. different OSes, and different versions of OSes, may be very different, including changes in default transmit/local keypad settings.) To get a really clean shell session, you need to run `zsh -f` (the `-f` skips startup files), probably run it under `env -i` (to get a really clean environment), and run it under a fresh terminal session (to make sure there's no terminal state left over from a prior process issuing control sequences). To do this, set up a new "profile" in your terminal emulator which runs `env -i zsh -l -f` instead of the default login shell. OMZ isn't going to work under that, but it will be about the closest you can get to "clean, stock zsh under a clean terminal".

**Comment by tshrjn** [comment] 2015-11-13 15:20
I'm also using a pure Ubuntu:14.04 env.
But after I installed oh-my-zsh by curl.
I cannot using home/end key anymore while I'm using the omz but works absolutely fine with bash.
Also, my Home and end keys are on the numpad which work when NumLock is disabled.
Moreover, I too didn't change any settings in .oh-my-zsh folder.

**Comment by apjanke** [comment] 2015-11-16 22:45
@tshrjn: Could you run `omz_diagnostic_dump` and post the results [as a gist](https://gist.github.com/), so we can see the details of your system configuration?

**Comment by apjanke** [comment] 2015-11-17 03:34
Ubuntu users, especially @mickk-on-cpp and @JimmyAx: take a look at `/etc/zsh`, and in particular, `/etc/zsh/zshrc`. I just looked at my own Ubuntu 14 box, and it comes with an extensive system-wide config file.

The Ubuntu `/etc/zsh/zshrc` defines its own `zle-line-init` and `zle-line-finish` functions, which emit `smkx`/`rmkx`. This means that by default (no `.zshrc`, but not running `zsh -f`), under stock Ubuntu 14.04, you're in keypad application mode when editing the command line, and `terminfo`-based bindings work. When you make a `~/.zshrc` that defines an empty `zle-line-init` function, you are clobbering the existing one and redefining it to not emit `smkx`, leaving it in "keypad local" mode when editing the command line. In this mode, the arrow keys and home and end send different character sequences so the "regular" terminfo-based key bindings won't work.

This is consistent with #2735.

The way the code is now, this is how the startup sequence works:

* Ubuntu's `/etc/zsh/zshrc` defines `zle-line-*` to do `[sr]mkx`
* OMZ's `lib/key-bindings` redefines `zle-line-*`, to still do `[sr]mkx`
* If you load `vi-mode`, it will redefine `zle-line-*` with broken ones that don't do `[sr]mkx`
* If you load the old Powerlevel9K theme, it would redefine `zle-line-*` with broken ones that don't do `[sr]mkx`. (Though this just got fixed recently, in bhilburn/powerlevel9k#136.)

If `[sr]mkx` is happening, then key bindings (or other things) based on `terminfo` entries for the keypad keys may not work. (Depending on exactly which keys and which terminal you're using.)

----------------------------

Home and End specifically don't break for me this way in `gnome-terminal` or iTerm2 for me. But those emulators seem to send the same sequences for Home/End in both keypad-application and keypad-local mode. Different emulators may act differently.

PuTTY in particular may complicate this because its behavior with respect to keypad application/local mode is *itself* user configurable.

<img width="444" alt="screen shot 2015-11-16 at 10 20 00 pm" src="https://cloud.githubusercontent.com/assets/2618447/11201880/5175c1b2-8cb0-11e5-9bed-b28212203f9b.png">

**Comment by apjanke** [comment] 2015-11-17 03:39
@damijanc:

> I can confirm that keys HOME and END do not work on MACOS Yosemite 10.10.3. Home key scrolls the console screen to the first line of output and End scrolls to the last line on output. 

This may also be an issue with the specific terminal emulator you are using. Are you using Terminal.app or iTerm2? By default, Terminal.app is configured to capture Home and End keystrokes itself and use them to scroll the window, instead of passing them along as character sequences to the shell running inside it.

<img width="751" alt="screen shot 2015-11-16 at 10 27 22 pm" src="https://cloud.githubusercontent.com/assets/2618447/11201962/384d3188-8cb1-11e5-9edd-f7ea766038cd.png">

If you're set up this way, the key bindings are irrelevant because those keystrokes will never make it to the shell. If you want to use the Home, End, PgUp, or PgDown keys to control your programs inside Terminal.app, you must reconfigure your Terminal.app profile. Unfortunately, there's no easy way to do this. It doesn't give you any presets like "act like xterm" or whatever; you'll need to enter the escape sequences manually, or find a source for a profile file out on the internet.

**Comment by apjanke** [comment] 2015-11-17 03:45
Also, setting `$TERM` to `linux` is probably the wrong approach for everybody. The `linux` term entry refers specifically to the [Linux virtual console](http://www.tldp.org/HOWTO/Keyboard-and-Console-HOWTO-7.html), the command line terminal that appears on a Linux machine's local monitor when you are not running X Windows, or you press Ctrl-Alt-*N* to switch to one. It does not mean a generic terminal emulator running on Linux. The Linux virtual console's key mappings and control sequences are different in some ways from `xterm` and many other popular terminal emulators, so if you set `TERM=linux`, it will probably break something or other for you.

**Comment by mickk-on-cpp** [comment] 2015-11-18 10:32
@apjanke I can confirm that if I do e.g. `printf '%s' ${terminfo[smkx]}`, then Home/End works as expected. Until the next time I switch to Command mode and go back to Insert mode, which I suppose is expected as well.

I'm not sure yet how I will act on it, I suppose I can always scour all those configuration files and brew my own zle-line-* hooks.

**Comment by apjanke** [comment] 2015-11-18 10:57
@mickk-on-cpp: Thanks for checking. That's kind of a good sign; it means you're probably running in to a known issue that we might be able to sort out.

You might look through them and see if you can find what's defining the `zle-line-*` hooks that don't do the `[sr]mkx` right and fix that. There aren't that many things which define these hooks. If it's only in OMZ that this breaks for you, it might be the `vi-mode` plugin that's doing it, in which case you could push for #4191 to be merged, or just merge that in to a copy of `vi-mode` in your `$ZSH_CUSTOM` directory. And the fact that it stops working when you switch between Command and Insert mode makes it sound like you have hooks which unconditionally emit `rmkx` upon `zle-keymap-select` (otherwise I think your terminal would stay in application mode until you were done editing the line). That's expected if it's the `vi-mode` plugin that's doing this to you.

You could also just add additional bindings to your `~/.zshrc` using the hardcoded sequences for the transmit-mode Home/End sequences your terminal sends, as a temporary workaround. Might also be a good safety precaution, because it might fix the issue where those keys do destructive things to your command line when this isn't working. (Because otherwise the unrecognized escape sequence is treated as an `Esc` and then some other keys, which looks like a `vi` editor command sequence.)

If you wanted to make your own hooks, you could copy `-start` and `-finish` from `lib/key-bindings.zsh`, and grab `zle-keymap-select` from [here](https://github.com/apjanke/oh-my-zsh/blob/53dc64e0501f2a6718dd3474e2ac98b828fff860/plugins/vi-mode/vi-mode.plugin.zsh#L2-L5) and I think it'd work fine. (Stick 'em in your `~/.zshrc` after loading OMZ.) Powerlevel9k is the only thing I've seen in these threads that needs additional custom behavior.

**Comment by apjanke** [comment] 2015-11-30 23:19
Hey folks, #4191 got merged, which should fix this. Want to update your OMZ and see if things are working for you now?

**Comment by silverhook** [comment] 2015-11-30 23:43
@apjanke Still seems to be buggy in both pure tty and Konsole (TERM=xterm)

**Comment by apjanke** [comment] 2015-12-01 00:56
> On my Mageia laptop in Zsh in pure TTY the [End] and [Home] keys work in emacs mode, but don’t in vi mode. In Konsole (KDE’s terminal emulator) they just don’t work properly in Zsh at all.

Okay. At this point, what isn't working? Are Home and End working in emacs mode in Konsole for you yet? That should have been fixed by #4191, unless there's something else going on.

Unless you've added extra bindings for Home and End in `vi` mode, they won't work there by default. There are no bindings for them in zsh by default, and Oh My Zsh only defines bindings for them in `emacs` mode. See #3435 for related discussion, if that's it.

For maintainers: Maybe it would be nice to add bindings for Home/End/PgUp/PgDn in the `vi-mode` plugin. They don't have default bindings that we'd be clobbering. And since their character sequences start with Esc for many terminals, if those sequences are unbound, they could be interpreted as possibly-destructive `vi` key sequences which switch to `vi` command mode and then do something.

**Comment by apjanke** [comment] 2015-12-01 01:01
> @jgrar In putty, I try to set Terminal-type from xterm to putty. It works.

One other thing about Putty: the `putty` terminfo entry in OS X, and probably other OSes, says that the terminal does not support keypad application mode switching (even though Putty actually does), and it uses the keypad local mode character sequences in its entries for the cursor keys and other keypad capabilities. So switching your `$TERM` to `putty` effectively disables keypad application mode and sets up key bindings to work in keypad local mode.

```
$ infocmp xterm putty | grep '[sr]mkx\|cuu1\|cud1\|cub1'
	cud1: '^J', '\ED'.
	cuu1: '\E[A', '\EM'.
	kcub1: '\EOD', '\E[D'.
	kcud1: '\EOB', '\E[B'.
	kcuu1: '\EOA', '\E[A'.
	rmkx: '\E[?1l\E>', NULL.
	smkx: '\E[?1h\E=', NULL.
```

**Comment by mickk-on-cpp** [comment] 2015-12-04 09:14
I’ve got rid of the previous workaround and everything works as expected. I had some quirks when I was using the workaround and they’re now gone, so this is a tremendous improvement on my end.

**Comment by mcornella** [comment] 2015-12-13 22:51
Ok I'm officially closing the issue. If someone still has issues, please comment and I'll open it again.

**Closed by mcornella** 2015-12-13 22:51 UTC
Labels: platform-linux, testers needed

**Comment by linlinlinlin** [comment] 2015-12-16 02:48
I am still have same issue without setting 
```
bindkey "\033[1~" beginning-of-line
bindkey "\033[4~" end-of-line
```

**Comment by apjanke** [comment] 2015-12-16 05:05
@linlinlinlin: Could you run `omz_diagnostic_dump` and post the results [as a gist](https://gist.github.com/) so we can see the details of your configuration? Unfortunately, this is a matter of dealing with a lot of moving parts and getting them all lined up with each other.

**Comment by linlinlinlin** [comment] 2015-12-16 12:23
@apjanke My ``omz_diagnostic_dump`` output
https://gist.github.com/linlinlinlin/c17ce49480ec1e0792f4

**Comment by apjanke** [comment] 2016-02-09 10:22
@linlinlinlin Is that broken home/end happening when you're connecting from Putty? This is probably a Putty-specific issue. After some testing, I found Putty is emitting different sequences for Home and End than most other terminals. By default, it sends those `^[[1~` and `^[[4~` sequences.

This probably isn't going to be fixed for putty in OMZ itself any time soon, if at all. You can either configure Putty to declare its `$TERM` as `putty` instead of `xterm` (if all your target hosts have a `putty` terminfo entry), or you can just leave this workaround in your `~/.zshrc`. It'll get Putty's default Home/End behavior working, and shouldn't hurt anything.

```
bindkey "\033[1~" beginning-of-line
bindkey "\033[4~" end-of-line
```

**Comment by linlinlinlin** [comment] 2016-02-09 15:44
@apjanke : Yes, I am using Putty or XShell software to connect to my host. The way to change ``xterm`` or bindkey methods both are works for me. I will using workaround method. Thanks!

**Comment by liquiddandruff** [comment] 2016-03-08 04:55
I also seem to be having some issues with home/end/delete keys not doing what they're supposed to.

I'm running arch linux with uxvrt, zsh, and oh-my-zsh, with git and vi-mode plugins, on the agnoster theme. 

Pressing the any of these keys (delete/home/end), capitalizes/lowercases words instead of doing what they're supposed to. Everything's fine though once I explicitly set their bindings using beginning-of-line end-of-line etc.

**Comment by apjanke** [comment] 2016-03-08 19:38
OMZ's default key bindings are applied to `emacs` mode, so they're not available in `vi` mode by default. The `vi-mode` plugin provides some bindings for the `vi` keymaps, but these don't currently include Home or End.

If you're in `vi-mode`, an unbound character sequence can be interpreted as a sequence of `vi` command key strokes, since they begin with an `Esc` (`^[`) character. That's probably why the capitalization/lowercase is happening.

The `vi` insert and command modes use two different keymaps. Key bindings are per-keymap. The default map in `vi` mode is `viins` (insert mode), so `bindkey` calls without an explicit keymap get applied to it, and not to `vicmd`. So to get your keys working fully in `vi` mode, you'll need to bind the keys in both in the `vicmd` and `viins` keymaps, using `bindkey`'s `-M <keymap>` option. Something like this.

```
if [[ "${terminfo[khome]}" != "" ]]; then
  bindkey -M viins "${terminfo[khome]}" beginning-of-line      # [Home] - Go to beginning of line
  bindkey -M vicmd "${terminfo[khome]}" beginning-of-line
fi
# ... and so on for each key ...
```

**Comment by imranmunshi** [comment] 2017-04-26 10:01
I use emacs mode and have bash as my shell.
Whenever I start zsh in my login shell, I experience this issue.
Even with num lock enabled, I don't get any key presses from the num pad and after I exit from zsh (back into my login shell bash) I don't get any key presses from num pad there either.
Num pad then just stops working on that tty once I use zsh in login shell, no matter how many times I logout-login, it doesn't work on that tty lgin shells anymore unless rebooted. It however works fine after startinx X session. But then back to login shell, it doesn't work again.

Because of this issue I had to change my shell to bash

**Comment by cono** [comment] 2017-11-13 13:37
I have this issue when enabling vi-mode plugin, here is the difference in key bindings:
```
grep "beginning-of-line" omz_diagdump_20171113-153* | grep -v ":#"
omz_diagdump_20171113-153207.txt:"^A" beginning-of-line
omz_diagdump_20171113-153207.txt:"^[OH" beginning-of-line
omz_diagdump_20171113-153321.txt:"^A" beginning-of-line
```

First file `153207` w/o vi-mode, second `153321` with.

**Comment by roachsinai** [comment] 2018-11-01 16:46
@cono Have this issue when enabling vi-mode plugin, too! And seems "^[OH" not binding to beginning-of-line!

Here is my [omz_diagnostic_dump for Home and End key work wierd.](https://gist.github.com/roachsinai/e3888907e5ae098ce4571a10adc031bb)

**Comment by roachsinai** [comment] 2018-11-01 16:57
Details at https://github.com/robbyrussell/oh-my-zsh/issues/7330.
