### ISSUE TITLE
sudo -s is throws warnings

### ISSUE THREAD

**Issue by stucki** [robbyrussell/oh-my-zsh#4388] opened 2015-09-23 13:39 UTC
I just updated to the latest version. It works fine until I want to open a root shell:

```
ws01 ➜  ~ $  sudo -s
[sudo] password for user: 
[oh-my-zsh] Insecure completion-dependent directories detected:
drwxr-xr-x 1 user user   200 Sep 23 15:28 /home/user/.oh-my-zsh
drwxrwxr-x 1 user user    38 Mar 18  2015 /home/user/.oh-my-zsh/custom/plugins
drwxrwxr-x 1 user user    46 Mar 18  2015 /home/user/.oh-my-zsh/custom/plugins/docker-enter
drwxrwxr-x 1 user user  2892 Sep 23 15:00 /home/user/.oh-my-zsh/plugins
drwxrwxr-x 1 user user    56 Feb 11  2015 /home/user/.oh-my-zsh/plugins/command-not-found
drwxrwxr-x 1 user user    34 Jun 16 10:28 /home/user/.oh-my-zsh/plugins/debian
drwxrwxr-x 1 user user    32 Sep  8 14:15 /home/user/.oh-my-zsh/plugins/docker
-rw-rw-r-- 1 user user 14844 Sep  8 14:15 /home/user/.oh-my-zsh/plugins/docker/_docker
drwxrwxr-x 1 user user    46 Sep  8 14:15 /home/user/.oh-my-zsh/plugins/git
drwxrwxr-x 1 user user    40 Sep 23 15:00 /home/user/.oh-my-zsh/plugins/gnu-utils
drwxrwxr-x 1 user user    12 May 16  2014 /home/user/.oh-my-zsh/plugins/knife
-rw-rw-r-- 1 user user  6360 May 16  2014 /home/user/.oh-my-zsh/plugins/knife/_knife
drwxrwxr-x 1 user user    34 Dec  2  2012 /home/user/.oh-my-zsh/plugins/screen
drwxrwxr-x 1 user user    28 Sep 23 15:00 /home/user/.oh-my-zsh/plugins/svn
drwxrwxr-x 1 user user    16 Sep 23 15:00 /home/user/.oh-my-zsh/plugins/vagrant
-rw-rw-r-- 1 user user  3881 Sep 23 15:00 /home/user/.oh-my-zsh/plugins/vagrant/_vagrant
[oh-my-zsh] For safety, completions will be disabled until you manually fix all
[oh-my-zsh] insecure directory permissions and ownership and restart oh-my-zsh.
[oh-my-zsh] See the above list for directories with group or other writability.

[oh-my-zsh] Insecure completion caches also detected:
-rw-rw-r-- 1 user user 35238 Sep 23 15:29 /home/user/.zcompdump
-rw-rw-r-- 1 user user 35438 Sep 23 15:29 /home/user/.zcompdump-ws01-5.0.2
[oh-my-zsh] Moving to "/home/user/.oh-my-zsh/cache//zcompdump-bad/"...
```

I do think that the first part (wrong permissions for .oh-my-zsh/ directory) is wrong and should be fixed. These permissions are ok and root can use the files too.

I'm not sure about the 2nd part however. Is it a bug or expected? I do understand that caches of one user (esp. root) should not be visible to other users. So maybe the change is fine and users should not use `sudo -s` any longer (use `sudo -i` to force a login instead).

If `sudo -s` should be supported still, it may help to create personalized .zcompdump files.

On a related note, there's a similar problem already documented in PR #3891.

**Comment by apjanke** [comment] 2015-09-23 19:17
Duplicate of #4383; probably caused by #3889. See discussion over there.

**Comment by stucki** [comment] 2015-09-23 19:23
See my comment in #4383 - this contains two problems in one ticket, and I've suggested to split them up.

**Comment by mcornella** [comment] 2015-09-24 21:50
This is the same problem as in #4383, as @apjanke says. The `compdef` error is actually a side effect of `compinit` not being able to load properly, since [it is `compinit` that defines `compdef`](http://zsh.sourceforge.net/Doc/Release/Completion-System.html#Functions-4).

**Closed** 2015-09-28 08:52 UTC
