### ISSUE TITLE
omz_urlencode conflicts with alias from common_aliases

### ISSUE THREAD

**Issue by neglectedvalue** [robbyrussell/oh-my-zsh#5243] opened 2016-07-21 14:30 UTC
Hi there!

common_aliases.plugin.zsh contains this line:

```sh
alias -g P="2>&1| pygmentize -l pytb"
```

At the same time there is the function `omz_urlencode`:

```sh
function omz_urlencode() {
  emulate -L zsh
  zparseopts -D -E -a opts r m P
```

The last letter `P` expands as an alias and causes errors `omz_urlencode:2: command not found: pygmentize`.

As a quick solution I commented out the alias, but I think there is a more elegant solution for it.

**Comment by apjanke** [comment] 2016-07-24 03:41
Aliases could be disabled within the function by sticking a `setopt no_aliases` after the `emulate -L zsh`. That `emulate -L` makes options local, so the effect would be limited to the function. For full hygiene, should probably be done in any function that has one- or two- character tokens in it, if we're going to protect against all the global aliases in common-aliases, including ones that might be added later.

**Comment by apjanke** [comment] 2016-08-11 23:03
After thinking about this for a while, I think removing global aliases and prohibiting them on OMZ plugins is probably the best way to handle this. Otherwise, protecting against them would mean adding `emulate -L zsh; setopt no_aliases` to every other function in OMZ, which sounds like a big pain.

Do you actually want use that `P` global alias?

**Comment by mcornella** [comment] 2016-08-17 20:45
I haven't been able to reproduce this:

```zsh
$ alias -g P="| echo hihihi"
$ functions -t omz_urlencode   # debug function
$ omz_urlencode -P asdf     
+omz_urlencode:1> emulate -L zsh
+omz_urlencode:2> zparseopts -D -E -a opts r m P
+omz_urlencode:4> local in_str=asdf
+omz_urlencode:5> local url_str=''
+omz_urlencode:6> local spaces_as_plus
+omz_urlencode:7> [[ -z -P ]]
+omz_urlencode:8> local str=asdf
+omz_urlencode:11> local encoding=UTF-8
+omz_urlencode:12> local safe_encodings
+omz_urlencode:13> safe_encodings=( UTF-8 utf8 US-ASCII ) 
+omz_urlencode:14> [[ -z UTF-8 ]]
+omz_urlencode:23> local i byte ord LC_ALL=C
+omz_urlencode:24> export LC_ALL
+omz_urlencode:25> local reserved=';/?:@&=+$,'
+omz_urlencode:26> local mark='_.!~*()-'
+omz_urlencode:27> local dont_escape='[A-Za-z0-9'
+omz_urlencode:28> [[ -z '' ]]
+omz_urlencode:29> dont_escape+=';/?:@&=+$,' 
+omz_urlencode:32> [[ -z '' ]]
+omz_urlencode:33> dont_escape+='_.!~*()-' 
+omz_urlencode:35> dont_escape+=']' 
+omz_urlencode:39> local url_str=''
+omz_urlencode:40> i = 1
+omz_urlencode:40> i <= 4
+omz_urlencode:41> byte=a 
+omz_urlencode:42> [[ "$byte" -regex-match "$dont_escape" ]]
+omz_urlencode:43> url_str+=a 
+omz_urlencode:40> ++i 
+omz_urlencode:40> i <= 4
+omz_urlencode:41> byte=s 
+omz_urlencode:42> [[ "$byte" -regex-match "$dont_escape" ]]
+omz_urlencode:43> url_str+=s 
+omz_urlencode:40> ++i 
+omz_urlencode:40> i <= 4
+omz_urlencode:41> byte=d 
+omz_urlencode:42> [[ "$byte" -regex-match "$dont_escape" ]]
+omz_urlencode:43> url_str+=d 
+omz_urlencode:40> ++i 
+omz_urlencode:40> i <= 4
+omz_urlencode:41> byte=f 
+omz_urlencode:42> [[ "$byte" -regex-match "$dont_escape" ]]
+omz_urlencode:43> url_str+=f 
+omz_urlencode:40> ++i 
+omz_urlencode:40> i <= 4
+omz_urlencode:53> echo -E asdf
asdf
```

**Comment by apjanke** [comment] 2016-08-19 03:49
Reproducing it is a bit trickier. The alias needs to be in effect at the time the function is defined, because that's when alias substitution happens, not when it's run.

If you just define the alias interactively, and then call `omz_urlencode` which was previously defined during startup, it won't break.

But if I put `alias -g P="2>&1| pygmentize -l pytb"` in your `.zshrc` before loading OMZ, then it reproduces for me.

```
➜  ~ omz_urlencode "foo bar"
omz_urlencode:2: command not found: pygmentize
foo+bar
➜  ~ omz_urlencode "foo bar" -P
omz_urlencode:2: command not found: pygmentize
foo+bar
➜  ~
```

But normally, plugins are loaded after all the library files, including `lib/functions.zsh` which defines `omz_urlencode`. So just enabling `common-aliases` doesn't cause this breakage for me, and won't for a normal OMZ user. It's a question why it is for @neglectedvalue here.

When I enable the `common-aliases` plugin myself, I do get some errors in my custom startup files. Custom files are loaded after plugins.

```
/Users/janke/.oh-my-zsh-custom/lscolors.zsh:49: parse error near `|'
/Users/janke/.oh-my-zsh-custom/themes/apjanke-01.zsh-theme:18: command not found: omz_lscolors_bsd_to_gnu
[~]
```

That line 49 is:

```
function omz_lscolors_bsd_to_gnu() {
  emulate -L zsh
 ...
  fg_map=(
    x 0       # default
  ...
    G "36;1"  # bold cyan
  ...
```

No `'|'` in sight. But that `G` is aliased. And in a way that breaks stuff on the command line, too.

```
$ alias
...
G='| grep'
...
$ alias | grep G
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
       	[-e pattern] [-f file] [--binary-files=value] [--color=when]
       	[--context[=num]] [--directories=action] [--label] [--line-buffered]
       	[--null] [pattern] [file ...]
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
       	[-e pattern] [-f file] [--binary-files=value] [--color=when]
       	[--context[=num]] [--directories=action] [--label] [--line-buffered]
       	[--null] [pattern] [file ...]
[✘ ~]
$
```

@neglectedvalue, do you have any custom files defined? Are you loading OMZ multiple times in a single shell session?

Could you run `omz_diagnostic_dump` and post its output as a Gist, so we can have a close look at your configuration?

**Comment by mcornella** [comment] 2016-10-13 21:53
@neglectedvalue you seem to be running `source ~/.zshrc` to reload the session, which is not a good practice. If you want to restart zsh without closing your terminal use `exec zsh`.

We'll keep thinking about this particular issue but it doesn't seem to be that common.

**Closed by mcornella** 2016-10-13 21:53 UTC
Labels: alias, bug, not our issue

**Comment by toddmbloom** [comment] 2016-10-26 14:22
I came across this in a Google search and I read through the issue and using exec zsh seems to work great. I just wanted to mention that the zsh_reload plugin does use ```source ~/.zshrc```, which gives me the error described in this issue. Is using the zsh_reload plugin discouraged?

**Comment by mcornella** [comment] 2016-10-26 18:37
@toddmbloom `source ~/.zshrc` is not the proper way to restart the zsh session. I'll change that to `exec zsh` or similar, and you should do to.

**Comment by toddmbloom** [comment] 2016-10-26 18:44
Great! Thank you! I'll update my aliases/plugins.

**Comment by BobHood** [comment] 2023-07-17 17:24
Just installed Rust using Homebrew on Mac OS X, and I now get this error. I'm assuming the installation of Rust is preempting the .zshrc start up and thus OMZ is not starting before, but after Rust in the sequence, and thus a collision of aliases. Any idea the solution in this case??

**Comment by jpbriggs408** [comment] 2023-08-29 11:22
Also running into this on OS X.
