### ISSUE TITLE
Prompt slow to appear in git directories with agnoster theme due to slow 'pwd -P' command

### ISSUE THREAD

**Issue by davidheijkamp** [robbyrussell/oh-my-zsh#6880] opened 2018-06-01 10:50 UTC
1.  **How to reproduce the problem**
    1. Configure zsh to use the `agnoster` theme in `~/.zshrc`
    1. Make a new directory and initialize it with git:
        ```zsh
        mkdir test-git-ohmyzsh
        cd test-git-ohmyzsh
        git init
        ```
    1. Perform any command like a trivial `ls` or `tree` from within the directory

1. **What the correct behavior should be**
    The prompt should immediately appear after completing the command.
     
1. **What the actual behavior is**
   It takes almost 10 seconds for the prompt to appear.

I've tried troubleshooting the problem according to the [oh-my-zsh guidelines](https://github.com/robbyrussell/oh-my-zsh/wiki/Troubleshooting).

I've logged the output of zsh using the agnoster theme [here](https://gist.github.com/davidheijkamp/403fcf07f9b4e4c05e7d76a4e30cd77c). The output of the same command using the robbyrussel theme can be viewed [here](https://gist.github.com/davidheijkamp/80735f854844deef2fd91680a4b42842)

The delay of 10 seconds is always experienced when performing the `pwd -P` command (see [this line in the output](https://gist.github.com/davidheijkamp/403fcf07f9b4e4c05e7d76a4e30cd77c#file-agnoster-git-log-L496).

Running this command in zsh with the robbyrussel theme (or a few others) leads to the same delay (check the output [here](https://gist.github.com/davidheijkamp/f7216e430ea3b6e16b2a3353fdb97efa)). In bash the `pwd -P` is running just fine.

I'm running Ubuntu 18.04 with the [current master of oh-my-zsh version](https://github.com/robbyrussell/oh-my-zsh/commit/ebda8af870acc295388ed187f0139a8bffa83196). The problem also appears when I'm checking out older versions of the repo.

**Comment by piksu** [comment] 2018-08-19 07:15
Hey, I took a quick look at agnostic theme. The performance within a git repo directory is a well known problem and actually is stated on the readme.

> It's currently hideously slow, especially inside a git repo. I guess it's not overly so for comparable themes, but it bugs me, and I'd love to hear ideas about how to improve the performance.

**Comment by mcornella** [comment] 2018-08-19 16:12
I can't reproduce on zsh 5.1.1. What version are you using?

@piksu he specified using an empty git repository which doesn't (and shouldn't) take long to process.

**Comment by davidheijkamp** [comment] 2018-08-27 14:39
Sorry for the late response: I'm currently using zsh 5.4.2, but I can't reproduce the issue with this zsh version either. Might be updated in the meantime.

**Comment by mcornella** [comment] 2018-08-29 13:13
If you can't reproduce the issue you might want to narrow down what has changed between your first encounter with the bug and now. Are you using a different zsh version? A different directory? (check that you're in the same partition / file system)... If `pwd -P` is the issue you should experience the same bug consistently by running it under the same conditions.

I'll close the issue in the meantime because it seems to be zsh related instead of OMZ related.

**Closed by mcornella** 2018-08-29 13:13 UTC
