### ISSUE TITLE
Loading custom completions after a28dbc8?

### ISSUE THREAD

**Issue by deanishe** [robbyrussell/oh-my-zsh#4048] opened 2015-06-16 07:35 UTC
Since a28dbc8 (which moves custom *.zsh file sourcing before plugins), I'm getting loads of `command not found: compdef` errors from my custom completions file (including `completion.zsh.inc` from the Google Cloud SDK).

Any idea how I go about fixing this?

**Comment by eyenx** [comment] 2015-06-16 07:36
+1

**Comment by mcornella** [comment] 2015-06-16 08:25
You should convert those files that need completion to custom plugins, and then add them to your `plugins=()` array in the zshrc file. 
The reason behind moving that logic was that it was necessary to enable people to override oh-my-zsh lib files. But it's a work in progress, in the future we may move the `compinit` statement to let lib files (default or custom ones) to use completion features.

**Comment by deanishe** [comment] 2015-06-16 10:05
That's not a solution as the files are typically from 3rd-party libraries. Editing them would break updating.

Is it possible to write a plugin that would source the files instead?

**Comment by ncanceill** [comment] 2015-06-16 10:13
@deanishe you need not edit the files to convert them as plugins; simply move-rename them like so:
* `$ZSH_CUSTOM/plugins/<name>/<name>.plugin.zsh` for scripts
* `$ZSH_CUSTOM/plugins/<name>/_<name>` for completion files

**Comment by deanishe** [comment] 2015-06-16 11:00
I'm afraid that won't work as I have different files on different systems, so there'd be dangling symlinks all over the place. I need to test if the files exist first.

Can I add a script at, say `$ZSH_CUSTOM/plugins/mycompletion/mycompletion.plugin.zsh`, and source the files from within there?

**Comment by scott-joe-williams** [comment] 2015-06-16 15:19
I'm having issues where the git plugin is overwriting aliases I've set in my `custom/`
Commenting out the offending alias in the git plugin appears to be the only solution for now, but that's not really ideal. Solution?

**Comment by azmd** [comment] 2015-06-16 15:54
Same issue is hitting me with the vi-mode plugin now overriding custom keybindings set in my custom/keybindings.zsh file (C-A and C-R et al).

So the way forward is converting most (all?) your custom .zsh files to plugins and adding them in correct order to the plugins array? Did I get that right?

**Comment by scott-joe-williams** [comment] 2015-06-16 16:07
I was under the impression that adding one there would overwrite the whole plugin. my git aliases are significantly smaller in number to the plugin. so i'd only want to overwrite a few. but perhaps that's the wrong way of thinking about it

**Comment by azmd** [comment] 2015-06-16 16:19
@scott-joe-williams The way I am looking at it right now is that I'd do a custom my-keybindings plugin and put it sort of last in my plugins array. That would (should) override the aliases set by former plugins. But then again, I could be totally wrong.

**Comment by scott-joe-williams** [comment] 2015-06-16 16:27
Yeah. I guess they could be considered a plugin. Thanks @azmd

**Comment by ncanceill** [comment] 2015-06-17 08:44
@azmd this is a good solution, would you consider documenting it in the [wiki](https://github.com/robbyrussell/oh-my-zsh/wiki/Customization#overriding-and-adding-plugins)?

**Comment by azmd** [comment] 2015-06-17 09:42
Sure, gladly. I'll try to find some time later in the week.

**Comment by apjanke** [comment] 2015-07-07 08:59
Caused by #3617 (merged under #3809). (Just putting this here so there's a link between the issues.)

**Comment by mcornella** [comment] 2015-09-01 18:51
Fixed in #4230

**Closed** 2015-10-18 14:21 UTC
