### ISSUE TITLE
Compass watch compile error "Invalid US-ASCII character "\xE2""

### ISSUE THREAD

**Issue by jorgvm** [robbyrussell/oh-my-zsh#3531] opened 2015-01-30 08:59 UTC
ZSH is messing with my compass watch task, it creates an error "Invalid US-ASCII character "\xE2"

More info here:
https://github.com/csswizardry/inuit.css/issues/270

**Comment by alekspetrov** [comment] 2015-02-07 14:35
+1

**Comment by remkodejong** [comment] 2015-02-11 09:55
Same here, uninstalled ZSH and now I don't get the error anymore. Shame though, really like ZSH.

**Comment by mcornella** [comment] 2015-02-11 13:33
Can you try upgrading oh-my-zsh? We recently fixed a unicode problem...

**Comment by alekspetrov** [comment] 2015-02-11 14:52
Nope, I've just updated oh-my-zsh, but still get an Error: Invalid US-ASCII character "\xE2"

**Comment by mcornella** [comment] 2015-02-11 14:58
Ok, can you post the output of `locale`?

**Comment by alekspetrov** [comment] 2015-02-12 07:08
`$ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=`

**Comment by mcornella** [comment] 2015-02-12 10:28
Ok that's a weird combination... can you post your zshrc file. Also, try restarting the terminal with [lines 19 to 22 of `lib/misc.zsh`](https://github.com/robbyrussell/oh-my-zsh/blob/ef7e53a78d0e4196c2d1e6e5b268209759d51753/lib/misc.zsh#L19-L22) deleted, then run `locale` again..

**Comment by apjanke** [comment] 2015-02-24 04:16
Would it also be possible to provide code or commands to reproduce the error? I don't know what a "compass watch task" is, and this could be easier to fix if we could reproduce it ourselves.

**Comment by stenmuchow** [comment] 2015-03-13 13:37
@apjanke compass is a compiler for sass to css, i produced the error using grunt to compile my sass, it crapped out on the css wizardry grid system. If this helps lettuce know, or if i can do any thing else.

**Comment by apjanke** [comment] 2015-03-13 15:33
What operating system are you folks getting the error on?

**Comment by apjanke** [comment] 2015-03-13 15:58
Can anyone provide an example file and `compass` command line to reproduce this problem?

**Comment by apjanke** [comment] 2015-03-13 16:28
At any rate, I think what's going on here is that this is a bad locale setup. In particular, with `LC_CTYPE="UTF-8"`: `"UTF-8"` on its own is not a valid locale. It's just a character encoding, and locales with encodings specified need to be in the form "`<region>.<encoding>`". You probably want `LC_CTYPE="en_US.UTF-8"`.

On OS X, you can get away with plain `UTF-8` as a locale with some programs even though it's not strictly valid. (Linux seems stricter.) But maybe ruby and compass are being more fussy about it. I think that a strict locale-aware program will see `"UTF-8"` as a region without a specified encoding (because there's no "." in it) or just see that it's not in the list of valid locales (which you can get with `locale -a`), and fall back to the default encoding, which is US-ASCII, which is why you're seeing an error about ASCII even though there's a mention of UTF-8 in your locale state.

Oh-my-zsh on its own doesn't directly set `LC_CTYPE` to `UTF-8`, so the thing to do is probably to check through your rc files and terminal configuration to determine how the locale is getting set like that, and correct it. (Those lines mcornella referenced will set `LC_CTYPE` from `LANG`, which appears to be unset for you.)

**Comment by vm6bj6xup6** [comment] 2015-07-07 06:06
Got this error few hours ago.

Then I add two lines in my `~/.zshrc` and then compass work well~!!
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

**Comment by apjanke** [comment] 2015-07-07 06:26
Great. You should have a look at your terminal or OS setup to see why a bad locale was being set in the first place. That could be causing you other problems as well.

**Comment by apjanke** [comment] 2015-09-11 07:30
@jorgvm: Is this still broken for you? Can this issue be closed?

**Comment by stenmuchow** [comment] 2015-09-14 16:06
@apjanke - I havent seen this error anymore so I think imo it can be closed...

**Comment by mcornella** [comment] 2015-10-18 14:11
Thanks @stenmuchow. Closing.

**Closed by mcornella** 2015-10-18 14:11 UTC
