### ISSUE TITLE
jira.plugin.zsh:52: parse error near `else'

### ISSUE THREAD

**Issue by arnoldnedap** [robbyrussell/oh-my-zsh#4027] opened 2015-06-15 12:11 UTC
Two else branches in this if......

**Comment by apjanke** [comment] 2015-06-15 20:51
I'll be darned. Reproduces for me on OS X if I just add `jira` to my plugins list.

```
Last login: Mon Jun 15 16:43:18 on ttys001
/Users/janke/.oh-my-zsh/plugins/jira/jira.plugin.zsh:52: parse error near `else'
[@ in ~]
$
```

Looks like it was caused by [a recent commit](https://github.com/robbyrussell/oh-my-zsh/commit/8652fd64efe7bcf950494856fd10ef1f5627a9ea) for #2898, probably as a result of bad merge conflict resolution with the jira-prefix support introduced in #2955. (The fact those are out of order makes me think we're looking at merge conflict problems and not a bad individual PR.)

**Comment by ncanceill** [comment] 2015-06-15 21:10
Agreed, now idea how a conflict resulted that way but this is bad.

**Comment by apjanke** [comment] 2015-06-15 21:48
I think it's that #2898 just had the bug in the first place after it was rebased after 2955 was merged (see its comment history), and wasn't re-tested after the rebase. So the "merge conflict" happened inside #2898 when it was rebased, not when you pulled it in to `easymerge` or anything after that. The bug's present in `tsldh/master` if you check that out on its own and the diffs are clear.

**Comment by ncanceill** [comment] 2015-06-15 22:22
Oh yes, good catch! So indeed the merge conflict was triggered (and improperly solved) during the rebase.

**Comment by tresni** [comment] 2015-06-16 16:50
Taking a look, I'll see if #4041 solves it...

**Comment by tresni** [comment] 2015-06-16 17:11
#4041 tests good, let's get that reopened and pulled in.

**Comment by xyalan** [comment] 2015-06-18 09:04
I have same problem.

**Comment by JohnSmithX** [comment] 2015-06-23 06:21
@tresni gj

**Comment by feiyan35488** [comment] 2015-06-23 06:58
I have same problem

**Comment by ladyborg** [comment] 2015-06-24 17:14
Also experiencing the same issue.

**Comment by francisbautista** [comment] 2015-06-25 02:28
I've been getting this same issue since the last zsh update I had.

**Comment by diwu1989** [comment] 2015-06-25 06:33
is there unit tests on oh-my-zsh?

**Comment by ncanceill** [comment] 2015-06-25 10:38
To all: #4041 should fix this issue.

@diwu1989 not at all, but we are working on improving the update/release process, and any suggestion or contribution is welcome.

**Comment by ericop** [comment] 2015-06-25 18:56
Sad, also having this issue still.

**Comment by Schrank** [comment] 2015-06-26 17:54
Same here:
```
-> % upgrade_oh_my_zsh --help
Upgrading Oh My Zsh
From https://github.com/robbyrussell/oh-my-zsh
 * branch            master     -> FETCH_HEAD
Current branch master is up to date.
[...]
-> % zsh
/Users/fabian/.oh-my-zsh/plugins/jira/jira.plugin.zsh:52: parse error near `else'
```

**Comment by hasannawaz** [comment] 2015-06-30 12:03
Unit tests with some build tool would be a good option.
```
oh-my-zsh/plugins/jira/jira.plugin.zsh:52: parse error near `else'
```

**Comment by JohnCaza** [comment] 2015-07-01 10:50
Did the fix never get pushed to master?

**Comment by mcornella** [comment] 2015-07-01 11:42
Hi all, this will be merged later today. Sorry for the long wait!

**Closed** 2015-07-06 16:33 UTC
