### ISSUE TITLE
echo/cat/all out doesn't work correctly with one symbol

### ISSUE THREAD

**Issue by rawmind** [robbyrussell/oh-my-zsh#7465] opened 2018-12-10 04:47 UTC
```
echo -n "0"
```
<img width="161" alt="akovrov_ _akovrov_sphinx-2_ _-zsh_ _solarized_dark_ansi_2_ _132x35" src="https://user-images.githubusercontent.com/3339076/49711253-67ddb880-fc4f-11e8-918d-74261c54456d.png">

With pure bash:

<img width="197" alt="akovrov_ _exit_ _bash_ _solarized_dark_ansi_2_ _132x35" src="https://user-images.githubusercontent.com/3339076/49711283-893ea480-fc4f-11e8-953b-00b42c8b3aeb.png">

Terminal Version 2.8.3 (404.1)

uname -v 
```
Darwin Kernel Version 17.7.0: Wed Oct 10 23:06:14 PDT 2018; root:xnu-4570.71.13~1/RELEASE_X86_64

```

**Comment by respencer** [comment] 2019-02-04 15:25
I can't reproduce what you get under zsh [5.5.1]. Under bash [4.4.19(1)] I get the same result as you.

Kubuntu 18.10

**Comment by rawmind** [comment] 2019-02-04 16:13
@respenser Yes, I also tryed reproduce it on Linux. But I guess the bug related to Mac Terminal only

**Comment by respencer** [comment] 2019-02-06 07:20
I was hoping someone else with a Mac could confirm, alas that doesn't look like it's happening any time soon.

Since it appears to be a Mac Terminal issue rather than an oh-my-zsh issue, can you please close this ticket? Or supply additional information if you disagree.

**Comment by rawmind** [comment] 2019-02-06 07:56
I guess it's not Mac Terminal issue because on sh and bash I can't reproduce it. I'll try to investigate it deeper and provide information after.

**Comment by mcornella** [comment] 2019-02-06 11:15
What `echo $ZSH_VERSION` do you get? Post your zshrc file as well.

**Comment by rawmind** [comment] 2019-02-12 08:53
➜ echo $ZSH_VERSION 
5.3

[.zshrc](https://gist.github.com/rawmind/5356640629a659108a2be5c89f6ba5e8)

**Comment by mcornella** [comment] 2019-02-12 22:12
I can't reproduce with OMZ and zsh 5.3, and the zshrc you posted. Try commenting out parts of the zshrc file and running `exec zsh` to reload, see if you can narrow down the culprit that way. I'm closing this since it's not an OMZ problem.

**Closed by mcornella** 2019-02-12 22:12 UTC
