### ISSUE TITLE
Failing on completing docker container names

### ISSUE THREAD

**Issue by dpolicastro** [robbyrussell/oh-my-zsh#7553] opened 2019-01-27 17:40 UTC
Hello, I noticed that zsh is not completing my docker images after using specific flags, for example:

If I try to press tab after writing the following command, it completes with the word `jenv_prompt_info` that I dont know what it is.
```sh
docker exec -it jen -> docker exec -it jenv_prompt_info
```

But, if I try to press tab in the following case, it auto completes correctly to jenkins, that is my container name.
```sh
docker exec -i -t jen -> docker exec -it jenkins
```

**Comment by mcornella** [comment] 2019-01-30 15:20
Duplicate of #6710

**Closed by mcornella** 2019-01-30 15:20 UTC
