### ISSUE TITLE
please do not enter into zsh after installation

### ISSUE THREAD

**Issue by earlzo** [robbyrussell/oh-my-zsh#6795] opened 2018-05-05 18:54 UTC
i am trying to build vagrant box automatically by using packer and i want to install oh-my-zsh when provisioning, but i am stucked because oh-my-zsh will enter into zsh after installation.

this behavior is bad for automation

**Comment by earlzo** [comment] 2018-05-05 19:00
#6537

**Comment by mcornella** [comment] 2018-06-12 20:12
Duplicate of #5873.

**Closed by mcornella** 2018-06-12 20:12 UTC
