### ISSUE TITLE
Git checkout branch-name tab completion does not work on a dirty repository

### ISSUE THREAD

**Issue by tallen1983** [robbyrussell/oh-my-zsh#7133] opened 2018-09-12 12:22 UTC
If you have a dirty repository (ie a file has been edited) tab completion no longer works for git checkout's branch name. Full reproduction steps:

```
mkdir git_checkout_tab_completion
cd git_checkout_tab_completion
git init
touch README
git add README
git commit -m "README"
git branch topic/foo
# this works and sets the command line to "git checkout topic/foo"
git checkout topic/<tab>
git checkout master
echo "a" >README
# this one resets the command line back to "git checkout topic"
git checkout topic/<tab>
```

The `Ctrl+x` `?` completion debug is [here](https://gist.github.com/tallen1983/9f5ba79102a039cde03e3b83227002c9)

**Comment by mcornella** [comment] 2018-09-12 13:05
I can't reproduce this. Can you try to generate the trace again? You should see something like
```
Trace output left in /tmp/zsh26561 (up-history to view)
```
meaning, the trace is saved in file `/tmp/zsh26561`.

**Comment by tallen1983** [comment] 2018-09-12 13:28
Ok so it does create a new file in tmp, it just doesn't tell me that it put it there. I'll upload it to gist. One sec.

**Comment by mcornella** [comment] 2018-09-12 20:57
What plugins do you have installed?

**Comment by tallen1983** [comment] 2018-09-12 21:04
I can reproduce it with only the git plugin installed.

**Comment by tallen1983** [comment] 2018-09-14 00:14
@mcornella yes sorry I guess GitHub didn't notify you of the edit to the original issue. The link is in there.

**Comment by tallen1983** [comment] 2018-09-19 16:49
@mcornella were you able to glean any information from the trace file I posted?

**Comment by mcornella** [comment] 2018-09-20 15:40
I haven't no, I can't understand why the completion just stops suddenly. Perhaps if you trace both the working and the broken command I can compare and understand why.

**Comment by mcornella** [comment] 2018-09-20 20:03
Ok I did just reproduce this. 

The key is checking out the branches, otherwise the bug isn't triggered. The checkouts create commits in the reflog, which is in turn used by `__git_recent_branches` to generate a list of recently checked-out branches. Here's a partial diff between a normal completion and the one with the bug in it:
```diff
-             +__git_recent_branches__names:13> reply=( )
-            +__git_recent_branches:9> branches=( )
-            +__git_recent_branches:12> ((  0  ))
-            +__git_recent_branches:15> return 1
+             +__git_recent_branches__names:13> reply=( topic/foo master )
+            +__git_recent_branches:9> branches=( topic/foo master )
+            ....
```

Eventually the execution that obtains recent branches will run `compadd` with the names of the found branches and the commit subject as a description. But another part of the completion execution also compadds information about available heads: `__git_recent_commits`:

```
    [...]
   +__git_recent_commits:65> j=master
   +__git_recent_commits:66> [[ master == tag:\ * ]]
   +__git_recent_commits:69> heads+=( master )
   +__git_recent_commits:65> j=topic/foo
   +__git_recent_commits:66> [[ topic/foo == tag:\ * ]]
   +__git_recent_commits:69> heads+=( topic/foo )
    [...]
   +__git_recent_commits:81> _wanted heads expl head compadd -a - heads
```

This means that there are now duplicate branches suggested:

```
$ git checkout topic/<TAB>
topic/foo  -- Initial commit
topic/foo
```

The same happens if we're in `topic/foo` and try to checkout master:
```
Switched to branch 'topic/foo'
$ git checkout master<TAB>
master  -- Initial commit
master
```

The bit about modifying README is irrelevant; this behavior is triggered anyhow. The only change is that, as you said, the trailing slash after `topic/` disappears. But that's a side effect that won't matter if we solve the fundamental issue, which is that there are duplicate completion entries.

I'm not familiar enough with zshcompsys to know if this is intended behavior or a bug. I'll let you know once I investigate further. In the meantime, I'm closing this since it seems to be an issue with zsh completion, not OMZ.

**Closed by mcornella** 2018-09-20 20:03 UTC
Labels: completion

**Comment by tallen1983** [comment] 2018-09-20 23:32
@mcornella thanks! Is there somewhere to report the bug to zsh or will you do that after you investigate further?

**Comment by mcornella** [comment] 2018-09-21 14:59
There's the [mailing list](https://www.zsh.org/mla/), but I want to test this behavior in multiple zsh versions and see if I can narrow down the culprit. You're free to report it though.

**Comment by mcornella** [comment] 2018-09-21 18:03
So running a `git bisect` I've narrowed down the issue to this first commit: https://github.com/zsh-users/zsh/commit/e869952200852a414debc6475a652e04e3b03641#diff-64ad373b9ca8d63aba051ba03245fd9e, which corresponds to zsh 5.4. On zsh 5.3.1 and older the branches aren't duplicated in the completion suggestions.

But, after https://github.com/zsh-users/zsh/commit/4dddf3aa6e446cef6e0ea720aa20bcf71d6107b1#diff-64ad373b9ca8d63aba051ba03245fd9eR6535 (versions 5.6 and newer), the completion system is able to see that the duplicate entries match so the branch name is completed. The entries still appear twice though, so the cursor doesn't end up one space after the completed branch name, but right after `topic/foo`:

```
zsh-5.6$ git checkout topic/<TAB> # completes to topic/foo[CURSOR]
topic/foo  -- Initial commit
topic/foo
```

Should be:
```
zsh-5.6$ git checkout topic/<TAB> # completes to topic/foo [CURSOR]
```

I'll report this bug myself, but you can see that the user experience is much better in the newer versions. So in the meantime, you can manually copy the latest version of the git completion to a folder which you have added to your `$fpath`. 
For example:
```shell
mkdir $ZSH_CUSTOM/completions
curl -L -o $ZSH_CUSTOM/completions/_git https://github.com/zsh-users/zsh/raw/zsh-5.6.2/Completion/Unix/Command/_git
```

Then add at the top of your zshrc, before OMZ is sourced:
```zsh
fpath=(${ZSH_CUSTOM:-$ZSH/custom}/completions $fpath)
```
