### ISSUE TITLE
my zsh doesn't work after auto update

### ISSUE THREAD

**Issue by onedou** [robbyrussell/oh-my-zsh#6966] opened 2018-07-04 01:17 UTC
![image](https://user-images.githubusercontent.com/3422640/42251606-d694f502-7f6a-11e8-98fa-39ce34534019.png)

**Comment by onedou** [comment] 2018-07-04 01:39
![image](https://user-images.githubusercontent.com/3422640/42252194-0b48d52c-7f6e-11e8-9815-3d85093ade72.png)

**Comment by onedou** [comment] 2018-07-04 03:14
when I reinstall again
![image](https://user-images.githubusercontent.com/3422640/42254855-69cc4180-7f7b-11e8-9156-14e7bdfab7d4.png)

**Comment by MrWhoami** [comment] 2018-07-04 23:28
Same here. I'm using the ubuntu subsystem of windows 10. After auto update, I get the following error.

```
/home/user/.oh-my-zsh/lib/correction.zsh:15: parse error near `\n'
/home/user/.oh-my-zsh/lib/functions.zsh:21: parse error near `in^M'
/home/user/.oh-my-zsh/lib/misc.zsh:22: command not found: env_default
/home/user/.oh-my-zsh/lib/misc.zsh:23: command not found: env_default
/home/user/.oh-my-zsh/plugins/git/git.plugin.zsh:2: not an identifier: _omz_git_git_cmd^M
```

**Comment by mcornella** [comment] 2018-07-05 18:00
Duplicate of https://github.com/robbyrussell/oh-my-zsh/issues/6764. See https://github.com/robbyrussell/oh-my-zsh/issues/6764#issuecomment-384045008

**Closed by mcornella** 2018-07-05 18:00 UTC
Labels: bug
