### ISSUE TITLE
Hostname Autocompletion Ignores Completion for Included SSH Configuration Files

### ISSUE THREAD

**Issue by paulcalabro** [robbyrussell/oh-my-zsh#5788] opened 2017-01-17 03:23 UTC
It's possible to include multiple SSH configuration files at once (e.g. to organize your SSH config file into smaller modules):

>      Include
>              Include the specified configuration file(s).  Multiple pathnames may be specified and each pathname may contain glob(3) wildcards and, for
>              user configurations, shell-like ``~'' references to user home directories.  Files without absolute paths are assumed to be in ~/.ssh if
>              included in a user configuration file or /etc/ssh if included from the system configuration file.  Include directive may appear inside a Match
>              or Host block to perform conditional inclusion.

If you choose to do this, however, hostname autocompletion no longer works for any hostnames in the included configuration files.

**Comment by austinbutler** [comment] 2017-03-12 18:17
Seem to be a duplicate of: https://github.com/robbyrussell/oh-my-zsh/issues/5662

**Comment by oxff** [comment] 2017-08-04 08:43
For the record, the following works rather well in ArchLinux with `extra/zsh 5.3.1-2` installed:

```bash
$ cd /usr/share/zsh/functions; curl -s https://github.com/zsh-users/zsh/commit/5ded0ad96740b62ea0214387ee260b515726a05e.patch | sudo patch -p1
…
can't find file to patch at input line 29
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/Completion/Unix/Command/_ssh b/Completion/Unix/Command/_ssh
|index 6763e24e7..28d2c38e7 100644
|--- a/Completion/Unix/Command/_ssh
|+++ b/Completion/Unix/Command/_ssh
--------------------------
File to patch: Completion/Unix/_ssh
patching file Completion/Unix/_ssh
```

**Closed** 2018-09-25 05:51 UTC
