### ISSUE TITLE
Inside screen over ssh, the default prompt not showing ➜ but ?

### ISSUE THREAD

**Issue by donnykurnia** [robbyrussell/oh-my-zsh#3665] opened 2015-03-04 06:24 UTC
I use zsh as default screen shell. In my laptop, the prompt is normal. If I ssh to remote server and execure zsh, the prompt still normal. But if I run screen in remove over ssh, the prompt is showing question mark instead of arrow to right. I don't change any default settings, only enable few plugins. Before upgrade to latest zsh, it still showing normal prompt in both local and remote screen session.

**Comment by apjanke** [comment] 2015-03-05 07:32
Possibly a locale issue? What's the remote OS and the output of `locale` on the remote server, under normal ssh and under screen? Which version of screen?

**Comment by donnykurnia** [comment] 2015-03-05 19:27
In local (via homebrew)

    ➜  ~  screen --version
    Screen version 4.00.03 (FAU) 23-Oct-06
    ➜  ~  locale
    LANG="en_US.UTF-8"
    LC_COLLATE="en_US.UTF-8"
    LC_CTYPE="UTF-8"
    LC_MESSAGES="en_US.UTF-8"
    LC_MONETARY="en_US.UTF-8"
    LC_NUMERIC="en_US.UTF-8"
    LC_TIME="en_US.UTF-8"
    LC_ALL=

In remote server via ssh: (ubuntu 14.04)

    ?  ~  screen --version
    Screen version 4.01.00devel (GNU) 2-May-06
    ?  ~  locale
    LANG=en_US.UTF-8
    LANGUAGE=
    LC_CTYPE="en_US.UTF-8"
    LC_NUMERIC="en_US.UTF-8"
    LC_TIME="en_US.UTF-8"
    LC_COLLATE="en_US.UTF-8"
    LC_MONETARY="en_US.UTF-8"
    LC_MESSAGES="en_US.UTF-8"
    LC_PAPER="en_US.UTF-8"
    LC_NAME="en_US.UTF-8"
    LC_ADDRESS="en_US.UTF-8"
    LC_TELEPHONE="en_US.UTF-8"
    LC_MEASUREMENT="en_US.UTF-8"
    LC_IDENTIFICATION="en_US.UTF-8"
    LC_ALL=en_US.UTF-8

**Comment by apjanke** [comment] 2015-03-05 23:09
That locale stuff looks fine to me. It differs from my own in that `LC_ALL` looks like it's explicitly set, but that should be fine.

I'm unable to reproduce so far, via logging in to Debian 7 and Ubuntu 14.04 boxes from my OS X 10.9.5 laptop. The arrow prompt looks normal under both regular `zsh` and `zsh` under `screen`. The Ubuntu is a fresh install with all upgrades applied as of today, and I'm using the latest oh-my-zsh, also a fresh install.

Can you give us some more info to help reproduce?

What plugins do you have enabled for oh-my-zsh? Even better, could you post your entire `~/.zshrc` file (from the Linux side), preferably as a gist?

What OS X version and terminal program (e.g. Terminal.app, iTerm2) are you using on the local Mac laptop side? What's the value of `$TERM` locally and in your ssh session? And what font are you using in your local terminal?

**Comment by apjanke** [comment] 2015-03-06 00:59
One other diagnostic: inside the `screen` `zsh` session that looks wrong, do this:

    script bad.txt
    echo hello world
    exit

And then post the `bad.txt` file somewhere we can see it (the file itself, not copying its contents to a gist or comment here). That'll show the exact characters that are being produced by zsh so we can track down whether it's an output or interpretation issue, and if it's output, maybe produce leads on what's going wrong.

**Comment by donnykurnia** [comment] 2015-03-09 04:59
@apjanke Here is the bad.txt file: http://donny.frzma.com/bad.txt

Thanks,

**Comment by apjanke** [comment] 2015-03-09 06:29
I'm afraid I'm still unable to reproduce, even with setting up a new user on my 14.04 box to use your `.zshrc` and `.screenrc`. Prompt in screen looks fine to me.

![screen shot 2015-03-09 at 2 27 40 am](https://cloud.githubusercontent.com/assets/2618447/6550781/eae900a8-c603-11e4-9965-eddebd74de13.png)

And that `bad.txt` sure looks like it has the '`➜`' Unicode character in it; when I cat it in terminal, it looks like a session with a good prompt.

A couple last questions:

Can you also post the contents of your `$HOME/bin/uptime-status`? It's referenced from your `.screenrc`, and screen is complaining about not finding it for me. That's one variable we haven't eliminated yet. The screen `backtick` command interacts with escape sequences, so maybe it's related.

What version of OS X are you running? And what terminal program (e.g. iTerm2, Terminal.app) are you using locally on your laptop?

**Comment by transacid** [comment] 2015-03-10 16:30
wild guess: could you start screen with "-U"

**Comment by donnykurnia** [comment] 2015-03-11 12:46
uptime-status only format the uptime to be shown in the footer:

    ?  sites-enabled  cat ~/bin/uptime-status
    #!/bin/bash

    uptime | awk '{ print $2" "$3" "$4" "$5" "$8" "$9" "$10" "$11" "$12 }'

I haven't restart the screen sessions since I upgrade the screen in my Mac via HomeBrew, and upgrading oh-my-zsh. I'll try to restart all session and see if it will fix this problems.

**Comment by apjanke** [comment] 2015-03-11 16:55
Aha! I can reproduce now. Kind of.

On the local Mac:
* `export LC_CTYPE=UTF-8`
* ssh to the Linux server
* Run `screen` on the remote Linux server inside that ssh session

![screen shot 2015-03-11 at 12 44 50 pm](https://cloud.githubusercontent.com/assets/2618447/6601520/7bc4cf46-c7ec-11e4-872b-d41143c808f2.png)

As @transacid suspected, doing `screen -U` fixes it: the arrow character gets rendered correctly.

I think what's going on is that `"UTF-8"` on its own is not a valid locale, at least not on Linux; you need to prefix it with a region/language code and not just put a character encoding. And the `screen` program on the Linux side is not recognizing it, and thus not running in UTF-8 mode. Looks like [older versions of iTerm2 had a related issue](https://code.google.com/p/iterm2/issues/detail?id=1667).

If this is the case, this might be just a configuration issue with your machine. I think the next step is to figure out where your `LC_CTYPE="UTF-8"` is getting set, and fix that so it's `en_US.UTF-8` instead.

**Comment by donnykurnia** [comment] 2015-03-12 03:33
@apjanke yes, I got the same result after closing all old screen sessions in the remote server and create a new one without -U options. When I close and re-create using -U, I got a normal prompt again.

I'll fix the locale settings on my remote servers.

Thanks for the help and insights.

**Comment by donnykurnia** [comment] 2015-03-12 03:52
I also confirm that after setting the correct locale on the remote server, I can get the correct prompt without using -U options when starting screen.

**Comment by apjanke** [comment] 2015-03-12 04:20
Great. Want to close this issue? I don't think there's anything for oh-my-zsh to do here.

**Closed** 2015-03-12 06:58 UTC

**Comment by transacid** [comment] 2015-03-12 09:47
you don't have to start with -U all the time. just do this:
```
echo -e 'defutf8 on\nutf8 on' >> ~/.screenrc
```

**Comment by donnykurnia** [comment] 2015-03-13 06:14
@transacid after I set a correct locale in `/etc/environment` file, I can start screen without -U and without additional setting. Here is what I add:

    ➜  ~  cat /etc/environment
    LC_ALL=en_US.UTF-8
    LANG=en_US.UTF-8
    LANGUAGE=en_US.UTF-8
    PATH=...

**Comment by ernestobarros** [comment] 2016-08-04 09:45
Different setup in Win10 (initiate ssh in PowerShell)
Solved with ConEmu which uses ANSI character set.
See http://davestewart.io/setup/fix-windows-broken-ssh-console/

**Comment by cloudbow** [comment] 2021-05-02 15:00
> @transacid after I set a correct locale in `/etc/environment` file, I can start screen without -U and without additional setting. Here is what I add:
> 
> ```
> ➜  ~  cat /etc/environment
> LC_ALL=en_US.UTF-8
> LANG=en_US.UTF-8
> LANGUAGE=en_US.UTF-8
> PATH=...
> ```

Did not work for me without -U
