### ISSUE TITLE
install.sh doesn't work on FreeBSD

### ISSUE THREAD

**Issue by matthewp** [robbyrussell/oh-my-zsh#4404] opened 2015-09-25 12:33 UTC
It exits after this line: https://github.com/robbyrussell/oh-my-zsh/blob/master/tools/install.sh#L1

I'm not sure what `-e` does, it's hard to search for this command.  Removing this line and the installer works fine.  Wish I had more specific information about why this fails.

**Comment by ibgorton** [comment] 2015-09-25 15:00
Same thing here, and the script didn't exit when done, had to Ctrl-C it. But seems to have installed and generated a proper .zshrc again. I'm running FreeBSD 10.2, didn't have this problem on earlier version.

**Comment by apjanke** [comment] 2015-09-28 01:33
`set -e` causes any error (as indicated by a nonzero exit status for a command) to abort the rest of the script and exit the shell, and is intentional. It's a built-in shell command in Bourne-style shells. To look up shell commands and options like this, do `man sh` and search for "-e".

How do you know it is exiting at that line? Normally the shell doesn't tell you what line it exits after, or even which command errored. Perhaps what is going on is that some other command is erroring at a different point, and removing the `set -e` causes that error to no longer terminate the script.

What is the output you get when you run `install.sh`? Does it include any error messages? Can you post the full output here?

The installer works for me on PC-BSD 10.1, which is based on FreeBSD 10.1. Sounds like something changed for 10.2. I'll set up a 10.2. machine and try to reproduce.

**Comment by matthewp** [comment] 2015-09-28 11:41
I don't recall exactly when it exited but I was doing some echos and they stopped after the first couple of fis, I'd say no later than here: https://github.com/robbyrussell/oh-my-zsh/blob/master/tools/install.sh#L23

**Comment by apjanke** [comment] 2015-09-28 12:26
You can turn on shell tracing with `-x` to see exactly where it's going wrong. I'm able to reproduce it on PC-BSD 10.2, and this is what I'm seeing.

```
[~] $ sh -xc "$(cat local/opp/omz/oh-my-zsh/tools/install.sh)"
+ set -e
+ which tput
+ tput=/usr/bin/tput
+ [ -n /usr/bin/tput ]
+ /usr/bin/tput colors
+ ncolors=80
+ [ -t 1 ]
+ [ -n 80 ]
+ [ 80 -ge 8 ]
+ tput setaf 1
+ RED=''
[~] $
```

Looks like `tput setaf 1` is erroring out. I poked around a bit, and it looks like this is because the FreeBSD `tput` is using the `termcap` database instead of `terminfo`, so it supports short `termcap` style capability names. `tput AF` is required here instead of `tput setaf`.

The `tput colors` doesn't work right here either. It's being interpreted as `tput co`, which is actually `tput columns`, so it will always return a larger number (like 89) even if the `$TERM` doesn't support color.

Probably caused by #3664, which switched the coloring code from hardcoded xterm escape sequences to the `tput` calls.

We'll need to add an additional check for `tput` portability. But in the meantime, just moving that `set -e` down below the color-picking stuff should work. The color stuff is just cosmetic, so it doesn't matter if it fails. And as a hack to get it to run, you can just do `sh -c $(wget ...) | cat` to run the installer: piping the output to `cat` means it's no longer outputting to a tty, so it won't attempt the colorization and won't run in to that `tput` error.

We really ought to change the installer so that if it runs in to an error and that `set -e` is triggered, it actually prints out an error message instead of just quitting. Users may not notice the nonzero exit status and may not understand what's happening.

**Comment by apjanke** [comment] 2015-09-30 05:24
There's a fix in #4419. Could you try it out and see if it fixes your issue?

**Comment by matthewp** [comment] 2015-09-30 11:52
It works, thanks!

**Comment by matthewp** [comment] 2015-10-01 13:31
@apjanke can this issue be closed or do you keep them open to wait for a release?

**Comment by apjanke** [comment] 2015-10-01 21:45
Leave it open until the fix is merged. That'll make it less likely for duplicate reports to come in.

**Closed** 2015-10-20 06:30 UTC

**Comment by gyaaniguy** [comment] 2019-06-06 21:51
Getting the same behaviour in freebsd 12.0

**Comment by mcornella** [comment] 2019-06-06 23:01
Can you post the log of your installation attempt?
