### ISSUE TITLE
OSX docker plugin not autocomplete 

### ISSUE THREAD

**Issue by dontcontactme** [robbyrussell/oh-my-zsh#3438] opened 2014-12-25 20:47 UTC
OSX version: 10.10.1
install docker way: official
addtional .zshrc script:
```bash
PROMPT='fan@macbook:%d$ '

export DOCKER_HOST=tcp://192.168.59.103:2376
export DOCKER_CERT_PATH=/Users/fanpei/.boot2docker/certs/boot2docker-vm
export DOCKER_TLS_VERIFY=1

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

**Comment by manonthemat** [comment] 2015-03-20 16:46
same issue here

**Comment by Dynasty9** [comment] 2015-04-15 03:52
:+1:

**Comment by ncanceill** [comment] 2015-04-15 09:07
Hi guys, and thanks for reporting the issue.

In cases like such where the issue is directly tied to a plugin, please notify the maintainer, like so: @AeonAxan.

@old-woman > when you say _"addtional `.zshrc` script"_, your `~/.zshrc` still contains `source $ZSH/oh-my-zsh.sh`, right?

**Comment by old-woman** [comment] 2015-04-15 14:49
@ncanceill  yes, my `~/.zshrc` still contains `source $ZSH/oh-my-zsh.sh`.

**Comment by ncanceill** [comment] 2015-04-15 14:52
OK, just checking. Let us see what @AeonAxan has to say about the issue.

**Comment by leifcr** [comment] 2016-09-20 07:46
@dontcontactme, @manonthemat  or @Dynasty9  Does this work for you if you use the file from #5060 ?

**Comment by mcornella** [comment] 2016-09-20 18:38
This should be fixed.

**Closed by mcornella** 2016-09-20 18:38 UTC

**Comment by leifcr** [comment] 2016-09-22 13:12
@mcornella Thanks!
