### ISSUE TITLE
[bug] zsh can not mush ipv6 address ?

### ISSUE THREAD

**Issue by Jack-Kingdom** [robbyrussell/oh-my-zsh#6100] opened 2017-05-22 09:13 UTC
Under zsh, sftp cannot much ipv6 adress like this:
`sftp root@[2607:8723:107:f2ad::]`
output will print:
`zsh: no matches found: root@[2607:8700:107:f2ad::]`
But, if I run this command under Bash, It works very well.

Is this a bug for Zsh? What reason caused this ?
Anyone has ideas ?

**Comment by Shea690901** [comment] 2017-05-22 20:17
Perhaps a globbing problem?
Try to escape at least the opening `[` if not the whole argument...
If it works then check your globbing options...

**Comment by Jack-Kingdom** [comment] 2017-05-23 01:30
Yeah, It works. Just modified it into:
`sftp root@\[2607:8723:107:f2ad::\]`

**Comment by xshotD** [comment] 2017-05-26 00:54
Just found this issue upon searching for issues - you may wanna close this issue because the problem is solved.

**Closed** 2017-05-26 01:15 UTC

**Comment by louwers** [comment] 2024-09-18 21:22
Thanks.
