### ISSUE TITLE
termsupport.zsh breaks `ls` command result of FAT32 partition

### ISSUE THREAD

**Issue by honnix** [robbyrussell/oh-my-zsh#4161] opened 2015-07-15 08:07 UTC
This sounds a bit of weird, but setting window name of iTerm2 breaks `ls` command result.

Environment:
- OS X 10.10.4
- iTerm2 2.1.1
- OMZ latest master branch
- USB key with FAT32 partition

How to reproduce:
1. Plug in the USB key that will be mounted automatically by OS X to, say `/Volumes/USB`
2. Start iTerm2 (zsh as default shell and OMZ loaded, `TERM` is `xterm-256color`)
3. `cd /Volumes/USB` and `ls` results only a `.` without any other files being listed, `ls -l` results `ls: .: Invalid argument`
4. `cd /Volumes` and `ls USB` gives correct result, so does `ls -l`
5. Comment out `print -Pn "\e]2;$2:q\a" #set window name` in termsupport.zsh, repeat above steps and problem is gone

Not sure how exactly this would happen, but feels like some escape problem.

The same issue has been reported [here](https://github.com/sorin-ionescu/prezto/issues/792) but didn't get proper handling.
#### Solution

Here's a workaround: https://github.com/robbyrussell/oh-my-zsh/issues/4161#issuecomment-153442082

**Comment by apjanke** [comment] 2015-07-16 07:58
Verrrrry curious.

Just for full reproducibility, do you know where that FAT32 USB key was formatted? (I'd like to reproduce this myself; I'm all-Apple hardware, with Windows VMs on Fusion and Parallels on 10.9 bare-metal hosts, and I have a Chromebook.)

Is [this](https://github.com/robbyrussell/oh-my-zsh/blob/a207a38d634cc10441636bc4359cd8a18c502dea/lib/termsupport.zsh#L19) the line you're referring to commenting out?

And in step 3/4, what is the expected output of the "correct result"? Are there any non-ASCII characters in the volume names in your case? Is there extra configuration required? I tried mounting a few USB keys on my 10.9 system, and no `/Volumes/USB/*` directories appeared; the USB key partitions were all mounted directly under `/Volumes`. Or is `/Volumes/USB` the mount point for your USB key?

What is the correct behavior in step 5 after you've commented out the `print -Pn [blahblah...]` statement?

**Comment by honnix** [comment] 2015-07-16 08:21
OK. I will shoot.

1. It was formatted on a Mac because me too all-Apple hardware.
2. Yes, that is the line.
3. The correct result is showing files/directories in the USB key; there is no non-ASCII characters; no extra configuration required.
4. `USB` is just used as an example. The partition is mounted under `/Volume` and `/Volumes/USB` is the mount point.
5. Correct behavior is being able to see files/directories in the USB key.

**Comment by apjanke** [comment] 2015-07-16 08:29
Gotcha. I will try to reproduce. (I have a 10.10 partition around here somewhere, if I can't make it happen on 10.9...)

**Comment by apjanke** [comment] 2015-07-17 04:47
I can reproduce, using the same environment. (On OS X 10.10.4, with iTerm 2.1.1, latest OMZ (a207a38d634cc10441636bc4359cd8a18c502dea); running bare metal on my dual-boot MacBook Pro.) I'm using the default `.zshrc` from the OMZ distribution (robbyrussell theme, just git for `$plugins`.

Reproduction steps were simple: formatted a 32 GB USB key in Disk Utility as FAT32 ("MS-DOS (FAT)"), left it named "UNTITLED", opened a new iTerm2 window, and did `cd /Volumes/UNTITLED/` and `ls`. I get the same results.

```
➜  ~  cd /Volumes/UNTITLED
➜  UNTITLED  ls
.
➜  UNTITLED  ls -la
ls: .: Invalid argument
```

It only seems to happen with this particular combination as far as I can tell. It doesn't happen on OS X 10.9. It doesn't happen if I use the Homebrew 5.0.8 `zsh` instead of the Yosemite system 5.0.5 `zsh`. It doesn't happen with exFAT or HFS+ formatted drives. It doesn't happen with Terminal.app or `xterm` or `urxvt`, even using the same `xterm-256color` setting, so the same title-setting code is being run. I built zsh 5.0.5 from source on OS X 10.9, and it doesn't happen there either. (Though I don't know how different my compiled 5.0.5 is from Apple's from 10.10.) For comparison, I built zsh 5.0.5 from source on OS X 10.10, too, and that zsh 5.0.5 on 10.10 also showed the broken behavior.

Still breaks with iTerm2 2.0 or 2.9.20150626 beta.

The path doesn't seem to matter. It still happens if I symlink a different path to the mounted USB drive.

```
➜  ~  mkdir -p tmp/links
➜  ~  ln -s /Volumes/UNTITLED tmp/links/my-usb-drive
➜  ~  cd tmp/links/my-usb-drive
➜  my-usb-drive  ls
.
➜  my-usb-drive  ls -a
.
➜  my-usb-drive  ls -l
ls: .: Invalid argument
➜  my-usb-drive
```

Commenting out that line as you did, or just changing the `2;` in `"\e]2;` to a `1;` or a `3;` fixes it.

It doesn't seem like a quoting issue. I added some debugging code to print the titles it was setting, and they seem fine. And the iTerm2 window title appears as expected.

I am utterly baffled.

**Comment by apjanke** [comment] 2015-07-17 05:05
It can also be reproduced using a DMG disk image with a FAT32 filesystem in it, instead of a USB key. More convenient for debugging.

**Comment by apjanke** [comment] 2015-07-17 05:36
I think I was wrong about the `zsh` versions it affects, and that was just a side effect of how I was doing the testing. It seems that the breakage only happens if you `cd /Volumes/UNTITLED` in the first shell that was opened by iTerm. If I run another shell inside that (e.g. by typing `zsh -l` or `/bin/zsh -l` and then doing the `cd`), the breakage doesn't occur in the subshell.

To test it properly with different versions of `zsh`, you need to create new Profiles in iTerm and change the Command that they run to run a specific version of zsh.

If I test `zsh` 5.0.8 that way, it breaks under 5.0.8 as well.
```
➜  ~  echo $ZSH_VERSION
5.0.8
➜  ~  cd /Volumes/DISK\ IMAGE
➜  DISK IMAGE  ls
.
➜  DISK IMAGE  ls -l
ls: .: Invalid argument
```

Conversely, running a subshell fixes it with the system 5.0.5 `zsh`:
```
➜  ~  echo $ZSH_VERSION
5.0.5
➜  ~  cd /Volumes/DISK\ IMAGE
➜  DISK IMAGE  ls
.
➜  DISK IMAGE  cd
➜  ~  /bin/zsh -l
➜  ~  echo $ZSH_VERSION
5.0.5
➜  ~  cd /Volumes/DISK\ IMAGE
➜  DISK IMAGE  ls
➜  DISK IMAGE
```

**Comment by apjanke** [comment] 2015-07-17 05:43
Say, @iwoloschin: in sorin-ionescu/prezto#792, you said you could reproduce this on Funtoo Linux. What terminal emulator were you using there which displayed the breakage? I've tried this on Debian with xterm, console, gnome-terminal, etc, and couldn't reproduce it there. iTerm2 on Yosemite is the only place I've been able to reproduce it.

**Comment by mcornella** [comment] 2015-07-17 05:47
Try setting debug mode (`set - xv`) to see the code being run, maybe you'll find some command syntax being messed up.

**Comment by honnix** [comment] 2015-07-17 06:04
@apjanke Dude you have done a very good test!! Thanks!

One thing bothered me was `ls: .: Invalid argument`, and maybe we can find something here.

**Comment by apjanke** [comment] 2015-07-17 07:00
I tried `set -xv` and the syntax looks fine. (Though it's a little hard to read since it's using prompt expansion.) But we can also reproduce this with a super-simple `print -n "\e]2;hello\a"`, which AFAICT is clearly good syntax-wise.

Maybe there's some non-printable character ending up in there that I just can't see. I can't figure out how to expose that, though: can't use `script`, because then it's running in a subshell, and the breakage doesn't occur.

```
taran-yos% set -xv
taran-yos% print -n "\e]2;hello\a"
print -n "\e]2;hello\a"
+-zsh:6> print -n '\e]2;hello\a'
taran-yos% ls
ls
+-zsh:7> ls
.
taran-yos% print -n "\e]2;hello\a"
print -n "\e]2;hello\a"
+-zsh:8> print -n '\e]2;hello\a'
taran-yos% ls -l
ls -l
+-zsh:9> ls -l
ls: .: Invalid argument
taran-yos%
```

**Comment by honnix** [comment] 2015-07-17 07:17
If you do `ls > test.output`, and then inspect `test.output`, actually everything is there. It looks the output somehow creates a mess.

**Comment by apjanke** [comment] 2015-07-17 07:49
Hmmm. That works. But it seems like it only does so if you're redirecting to an output file on that same mounted drive. If I send the output to a file under my home dir instead, it's still wrong.

```
taran-yos% print -n "\e]2;hello\a"
taran-yos% ls > test_output.txt
taran-yos% cat test_output.txt
bar
foo
test_output.txt
taran-yos% rm test_output.txt
taran-yos% print -n "\e]2;hello\a"
taran-yos% ls > ~/test_output.txt
taran-yos% cat ~/test_output.txt
.
taran-yos%
```

Here's a couple other clues:

* You can find the [source for OS X's `ls` here](http://www.opensource.apple.com/source/file_cmds/file_cmds-242/), at least as of 10.10.1. I'm reading through it. It uses [fts] to traverse the files that are listed.
* The output in the breaking case is the same as the output of `ls -d`.
* The breakage only seems to happen if you're at the mount point itself, and not in a subdirectory of it.

```
➜  ~  cd /Volumes/DISK\ IMAGE
➜  DISK IMAGE  ls
.
➜  DISK IMAGE  cd subdir
➜  subdir  ls
blah
➜  subdir
```

* The breakage only happens if `.` is the first argument, or there is no argument. If you list it along with other dirs and not as the first argument, like `ls / .`, then the listing works as normal.
* `find` and `du`also break with the same "Invalid argument" error message.

**Comment by apjanke** [comment] 2015-07-17 07:58
Aha! I can reproduce this under `bash`, too. If I make a new iTerm2 profile with the Command as `/bin/bash -l` (and not `login -fp janke /bin/bash -l`), then the breakage happens under `bash` as well.

```
taran-yos:~ janke$ echo $BASH_VERSION
3.2.57(1)-release
taran-yos:~ janke$ cd /Volumes/DISK\ IMAGE/
taran-yos:DISK IMAGE janke$ ls
bar	foo	subdir
taran-yos:DISK IMAGE janke$ printf "\e]2;foobar\a"
taran-yos:DISK IMAGE janke$ ls
.
taran-yos:DISK IMAGE janke$ ls
bar	foo	subdir
taran-yos:DISK IMAGE janke$
```

This is looking like an iTerm2 issue. I'm going to put together a bug report for it.

**Comment by apjanke** [comment] 2015-07-17 08:15
I reported it as an issue to iTerm2, if you want to follow along or comment: https://gitlab.com/gnachman/iterm2/issues/3686

**Comment by iwoloschin** [comment] 2015-07-17 11:00
I think I had been using konsole-15.14?  Unfortunately it's not installed on my system anymore, and my replacement, qterminal, seems to be working fine.  I can't remember what I had done to make it fail on Funtoo.

**Comment by mcornella** [comment] 2015-08-09 21:13
Ok, @gnachman just marked the bug as closed. Can we close this one here as well?

**Comment by apjanke** [comment] 2015-08-09 21:34
Give me a chance to confirm his findings? Haven't had a chance to test it yet.

**Comment by mcornella** [comment] 2015-08-09 22:13
Sure, no rush.

**Comment by vlsd** [comment] 2015-09-02 03:39
In `zsh` under `iTerm2` this happens for me every single time. In either `Terminal` (regardless of shell) or `bash` under `iTerm2` or `zsh -f` under `iTerm2` this only happens about once every ten tries or so -- i.e. rare enough to not be annoying. The underlying issue seems to be a system bug of some sort, but it's definitely exacerbated by an interaction between `oh-my-zsh` and `iTerm2`

**Comment by mcornella** [comment] 2015-09-02 17:22
@vlsd can you check if running `title(){}` makes it better?

**Comment by vlsd** [comment] 2015-09-02 19:36
@mcornella yep, totally makes it better.

**Comment by mcornella** [comment] 2015-09-02 22:26
@apjanke maybe you can get some more information toggling the [debug mode](https://gitlab.com/gnachman/iterm2/wikis/DebugLogging). FWIW, this looks to me like a race condition of some sort, but if @gnachman and @vlsd are correct in that Terminal.app also suffers from this then Apple may be at fault here. 

Oh! You guys have `strace` available? If so, you can `strace ls` or `strace ls -l` to see the system calls being made. I don't know what else...

**Comment by apjanke** [comment] 2015-09-03 05:22
OS X has `dtrace`/`dtruss`.

Here's a gist of dtrace logs for the failure.
https://gist.github.com/apjanke/ffa0d7d7eea9e2da42cd

I created them with commands like `sudo dtruss -f -p 527 2>&1 | tee 10_10-iterm-print-and-ls-failure`, where `527` is the PID of my `zsh` process. For the scenario where I do the `print`, I start tracing after typing in the `print` command at the command line, but before hitting enter to execute it.

Scenarios:
* Normal `ls` inside iTerm: https://gist.github.com/apjanke/ffa0d7d7eea9e2da42cd#file-10_10-ls-success
* Printing and `ls` inside iTerm, showing failure: https://gist.github.com/apjanke/ffa0d7d7eea9e2da42cd#file-10_10-iterm-print-and-ls-failure
* Printing and `ls` inside Terminal.app, showing success: https://gist.github.com/apjanke/ffa0d7d7eea9e2da42cd#file-10_10-terminal-print-and-ls-success
* Blah and `ls` in bash in Terminal.app, showing failure: https://gist.github.com/apjanke/ffa0d7d7eea9e2da42cd#file-10_10-terminal-bash-blah-and-ls-failure

###  Interesting bits in the traces   ###

Here's what the `stat` call looks like in `ls` when it succeeds.

```
  605/0x171f:  stat64(".\0", 0x7FFF5B05C428, 0x7FFF5B05CBC0)		 = 0 0
  605/0x171f:  open_nocancel(".\0", 0x0, 0x0)		 = -1 Err#22
  605/0x171f:  open_nocancel(".\0", 0x1100004, 0x104BB0A00)		 = 3 0
```

And here's what it looks like when it fails after that `print`.

```
  646/0x1982:  stat64(".\0", 0x7FFF56537428, 0x7FFF56537BC0)		 = -1 Err#22
  646/0x1982:  lstat64(".\0", 0x7FFF56537428, 0x7FFF56537BC0)		 = 0 0
  646/0x1982:  open_nocancel(".\0", 0x0, 0x0)		 = 3 0
  646/0x1982:  fstat64(0x1, 0x7FFF56536C88, 0x0)		 = 0 0
```

It looks like it's behaving as though "." were a symlink instead of a normal directory.

###  Reproducing with bash  ###

I cannot regularly reproduce the error behavior under `zsh` in Terminal.app myself. But, I can reproduce it there in `bash`.

```
taran-yos:FAT32 janke$ print -n "\e]2;hello\a"
-bash: print: command not found
taran-yos:FAT32 janke$ ls
.
taran-yos:FAT32 janke$ ls
taran-yos:FAT32 janke$ 
```

Now that's interesting: I forgot that `bash` only has echo. But it still broke. That seems to mean that it's not the act of printing the string out that's doing the damage. Happens in `zsh` in iTerm2 as well.

And for that matter, just `blah` triggers it.

```
taran-yos:FAT32 janke$ ls
taran-yos:FAT32 janke$ blah
-bash: blah: command not found
taran-yos:FAT32 janke$ ls
.
taran-yos:FAT32 janke$ ls
taran-yos:FAT32 janke$ 
```

Neither `zsh` nor `iTerm2` is involved in that example; that's OS X's `bash` running in OS X's Terminal.app. Something sure looks busted in a system library somewhere.

**Comment by vlsd** [comment] 2015-09-03 14:07
I've sent in a bug report to Apple, maybe they'll look at it?

**Comment by gnachman** [comment] 2015-09-08 02:08
It's hard for me to imagine how iTerm2 could be a direct cause of this, but possibly some difference in the environment variables between Terminal and iTerm2 could affect its frequency.

**Comment by apjanke** [comment] 2015-09-10 18:04
Same here.

Here's the difference between environment variables between Terminal.app and iTerm2 on OS X 10.10.5 for me. I don't see anything interesting or suspicious there.

```
taran-yos% env | sort > env_vars-iterm2.txt
taran-yos% diff env_vars-terminal.txt env_vars-iterm2.txt
1a2
> COLORFGBG=12;8
3a5,6
> ITERM_PROFILE=Default
> ITERM_SESSION_ID=w0t0p0
13,15c16
< TERM_PROGRAM=Apple_Terminal
< TERM_PROGRAM_VERSION=343.7
< TERM_SESSION_ID=8BAD2126-BD67-4D8E-A296-7A4F6D6D2E8C
---
> TERM_PROGRAM=iTerm.app
taran-yos%
```

Since this looks like an implementation bug in a system library, it could be something as obscure as "the particular set of DLLs you have loaded is causing one of them to have its base address relocated, exposing a buffer or pointer bug somewhere". Or even the total size of the environment, which could cause other addresses or alignment to shift. Who knows.

I don't suppose Apple supplies debug versions of the libraries that implement `stat64()`?

If thjis is a system library bug, I don't know if anything could or should be done to work around it. It's not a common use case, and at the point where something like `stat` is failing, application-level software is kind of off the hook. On the other hand, Apple seems to abandon versions of OS X after one year, so this may never get fixed for 10.10.

**Comment by apjanke** [comment] 2015-09-10 18:05
BTW, I also tested this in Terminal.app and iTerm2 sessions running `bash --noprofile` as the command, so it would have an extra-clean `bash` session without even the system startup files from `/etc/*`. Same results: doing `blah` and `ls` causes the breakage under both terminal programs.

**Comment by vlsd** [comment] 2015-09-10 19:47
>On the other hand, Apple seems to abandon versions of OS X after one year, so this may never get fixed for 10.10.

Hopefully they won't propagate the offending piece of code forward to the next version of OS X

**Comment by apjanke** [comment] 2015-09-11 05:49
> Hopefully they won't propagate the offending piece of code forward to the next version of OS X

Looks like they did. I see the same erroneous behavior on the current OS X 10.11 Public Beta. (I think it's Public Beta 6.)

**Comment by hholtmann1970** [comment] 2015-11-03 17:58
so.. Is there a workaround simple fix for this for now?

**Comment by vlsd** [comment] 2015-11-03 18:17
@hholtmann1970, as far as `oh-my-zsh` goes, this might be the best option right now

> Comment out print -Pn "\e]2;$2:q\a" #set window name in termsupport.zsh, repeat above steps and problem is gone

However, the `ls` will still fail sometimes regardless of shell or emulator, and at that point the workaround is to try again. If you're running into this issue while trying to run a script, I suggest adding in a "retry on error" type of loop around the offending piece of code.

**Comment by olsonpm** [comment] 2015-11-22 02:32
Just ran into this now.

Thanks for all the information regarding this bug.  Unfortunate that osx 10.11 doesn't seem to fix this.  A pretty annoying bug :(

**Comment by andrewtchin** [comment] 2015-12-11 19:50
I'm also seeing this. OSX 10.10.5, iTerm2 2.1.4, zsh 5.2.

**Comment by andrewtchin** [comment] 2015-12-11 19:55
Workaround works a little, still not perfect:
```
CORPORATE ~ » cd /Volumes/asdf
fatal: failed to stat '.': Invalid argument
CORPORATE /Volumes/asdf » ll
total 8
-rwxrwxrwx  1 andrewchin  staff  13 Dec 11 13:37 test
fatal: failed to stat '.': Invalid argument
CORPORATE /Volumes/asdf » ls -al
ls: .: Invalid argument
fatal: failed to stat '.': Invalid argument
```

**Comment by mcornella** [comment] 2015-12-16 06:58
There's something else we haven't tried: ls is always complaining about `.` not being available, what if you specifically tell it to ls `$PWD`? Maybe it bypasses the error condition somehow for not using `.`

**Comment by apjanke** [comment] 2015-12-16 07:34
I wouldn't waste your time... I think we've established that this is an OS filesystem level bug: it futzes up in other shells and terminals and file access patterns too. And it's erratic. Trying to develop a model of the bug and high level heuristics to work around it might just lead to more complicated error patterns, and maybe a false sense of security for operations that appear to work.

If you can't trust your filesystem driver, game over, man.

**Comment by apjanke** [comment] 2015-12-16 07:35
Maybe the best thing for OMZ to do is throw a yellow warning flag on the prompt when it recognizes you're on a mounted FAT32 filesystem on OSes that have flaky behavior.

**Comment by mcornella** [comment] 2015-12-16 07:58
> If you can't trust your filesystem driver, game over, man.

Fair enough, just trying to take a deep dive into the pit :grin: 

> Maybe the best thing for OMZ to do is throw a yellow warning flag on the prompt when it recognizes you're on a mounted FAT32 filesystem on OSes that have flaky behavior.

I don't know how we'd go about doing that. Any ideas? If not, we can always put this issue center page and let people know what to do to slow down the rate of these errors.

**Comment by apjanke** [comment] 2015-12-16 08:35
> I don't know how we'd go about doing that. Any ideas?

A few, but they're all bad. Stick a system-dependent check in `precmd_functions` or similar. Ugly, and costs the user wall time at every prompt.

Yeah, imho, best thing to do is prob to just highlight this in a list of "known bugs we can't fix". :(

**Comment by ale-batt** [comment] 2016-06-23 08:45
[This Comment](https://github.com/robbyrussell/oh-my-zsh/issues/4161#issuecomment-153442082)  solve the error, but why isn't fixed on update ?

**Comment by mcornella** [comment] 2016-06-25 10:00
That's a good question. What specific code can we put forward that detects FAT32 filesystems on broken OSX versions?

**Comment by iRonin** [comment] 2016-10-12 17:15
Issue still occurs

**Comment by apjanke** [comment] 2016-10-15 06:59
The next step to take here is for someone with an Apple developer account to file a Radar bug report with Apple about this behavior, so it can be fixed in a future release of macOS. Maybe they don't even know this is broken?

And we should test this on macOS Sierra; maybe it's been fixed already.

> This Comment solve the error, but why isn't fixed on update ?

That doesn't solve the problem entirely, it just seems to reduce how often it occurs. Maybe that's enough of a win that we should add a configuration option to OMZ that allows users to turn off that output (so if you frequently use FAT32 filesystems from the command line, you can disable it, to get fewer `ls` errors, at the cost of losing the ability to update the window title). For example, introduce an `OMZ_HACK_NO_WINDOW_TITLE=true` option to simply turn this off. (I think we should have a new `OMZ_HACK` or `OMZ_WORKAROUND` namespace for option that affect compatibility or system bug-workaround behavior, as opposed to features and user preferences.)

If you wanted to get fancy, you could do a `mount` and compare that to `pwd` to detect when you're under a FAT32 filesystem on every `precmd`, and conditionally turn off the prompt then. But that would incur a performance penalty on every prompt, and there's a maintenance cost to this sort of compatibility support.

**Comment by vlsd** [comment] 2016-10-17 16:21
@apjanke I've actually already filed a bug report with Apple---and mentioned it to a friend of mine that works there, like that's going to do anything :P---but it's such a corner case for practical use that I highly doubt they'll look into it. Maybe if every single one of us submits a bug report for the same thing?

I don't think their bug tracker is public, which explains why I can't find a way to link to the bug report from here, but the bug report ID is `22557267`

**Comment by apjanke** [comment] 2016-10-21 02:05
Yeah, radar is private. There's a community-maintained public mirror at https://openradar.appspot.com/, but it doesn't look like that particular report has been copied over.

**Comment by neurogenesis** [comment] 2017-05-22 10:46
still an issue on macOS 10.12.5 (16F73)

**Comment by mcornella** [comment] 2019-04-07 20:41
Can someone confirm if this still happens?

**Comment by honnix** [comment] 2019-04-07 21:09
I can try to verify it again and report asap.

**Comment by honnix** [comment] 2019-04-07 21:29
I cannot reproduce it under the following env:

* OS X 10.14.4
* iTerm2 Build 3.2.7beta4
* OMZ latest master branch
* USB key with FAT32 partition

I'm OK closing this.

**Comment by apjanke** [comment] 2019-04-08 08:41
Works fine for me too now.

* macOS 10.14.4
* iTerm2 Build 3.3.0beta1 or Terminal.app
* mounted FAT32 disk image

Looks like this was fixed upstream, and IMHO the issue can be closed.

**Comment by mcornella** [comment] 2019-04-08 10:53
Thanks!

**Closed by mcornella** 2019-04-08 10:53 UTC
Labels: Status: not our issue

**Comment by hoylemd** [comment] 2019-06-10 20:10
I think I'm seeing this issue now.

- macOS 10.12.6
- iTerm2 Build 3.2.9 or Terminal.app
- mounted FAT disk image (I think it's FAT, since I selected that instead of FAT32)
- zsh 5.2 (x86_64-apple-darwin16.0)
- omz on up-to-date master as of this message

I will try updating macos and reporting back, but I'm on a work laptop and not 100% sure I actually can do that :/
