### ISSUE TITLE
Pasting brackets gets escaped

### ISSUE THREAD

**Issue by ctron** [robbyrussell/oh-my-zsh#6654] opened 2018-03-02 12:00 UTC
Executing shell commands from e.g. a tutorial containing something like `$(cmd ...)` always triggers
an escape of the initial `(`. This is really annoying.

Pasting: `echo $(foo bar)`
Gives: `echo $\(foo bar)`, which cannot be executed

Is there a way to disable this?

**Comment by abbi-gaurav** [comment] 2018-07-31 12:27
facing the same issue.

**Comment by mcornella** [comment] 2018-08-09 21:43
What `zsh --version` do you have and what does `zle -l | egrep '(self-insert|bracketed-paste)'` output?

**Comment by ctron** [comment] 2018-08-10 09:25
> What `zsh --version` do you have and what does `zle -l | egrep '(self-insert|bracketed-paste)'` output?

~~~
➜  ~ zsh --version
zsh 5.0.2 (x86_64-redhat-linux-gnu)
➜  ~ zle -l | egrep '(self-insert|bracketed-paste)'
self-insert (url-quote-magic)
~~~

**Comment by abbi-gaurav** [comment] 2018-08-10 10:34
> What zsh --version do you have and what does zle -l | egrep '(self-insert|bracketed-paste)' output?

```shell
$ zsh --version
zsh 5.3 (x86_64-apple-darwin17.0)

$ zle -l | egrep '(self-insert|bracketed-paste)'
bracketed-paste (bracketed-paste-magic)
self-insert (url-quote-magic)
```

**Comment by ald0n** [comment] 2018-08-15 09:43
Had the same, all is fine in bash
>➜ ~ zsh --version 
zsh 5.5.1 (x86_64-pc-linux-gnu)

>➜  ~ zle -l | egrep '(self-insert|bracketed-paste)'
bracketed-paste (_zsh_highlight_widget_bracketed-paste)
orig-bracketed-paste (bracketed-paste-magic)
orig-self-insert (url-quote-magic)
self-insert (_zsh_highlight_widget_self-insert)
self-insert-unmeta (_zsh_highlight_widget_self-insert-unmeta)

**Comment by mcornella** [comment] 2018-08-29 16:33
Does this happen when running zsh without rc files? Try that with `zsh -f`

**Comment by ctron** [comment] 2018-08-30 06:31
> Does this happen when running zsh without rc files? Try that with `zsh -f`

Running with `-f`works as expected. Nothing gets escaped in this case.

![image](https://user-images.githubusercontent.com/202474/44833646-fe511580-ac2e-11e8-9500-15649d56e820.png)

**Comment by mcornella** [comment] 2018-08-30 14:40
Ok, let's narrow down the culprit. First, comment out the `source $ZSH/oh-my-zsh.sh` line in your zshrc file to stop loading OMZ, and see if the issue persists. If not, then start sourcing files in the $ZSH/lib folder one by one, checking if it's still there.

My guess is that `lib/misc.zsh` is at fault, so if you want you can check that out directly.

**Comment by ctron** [comment] 2018-08-31 09:27
Removing the `source` line fixes the issue.

**Comment by ctron** [comment] 2018-08-31 09:32
Sourcing `misc.zsh` indeed causes the problem:

~~~
[jreimann@jreimann ~]$ zsh
[jreimann@jreimann]~% curl -X POST --insecure -T addresses.json -H "content-type: application/json" https://$(oc -n enmasse get route restapi -o jsonpath='{.spec.host}')/apis/enmasse.io/v1alpha1/namespaces/enmasse/addressspaces/default/addresses
[jreimann@jreimann]~% cd .oh-my-zsh 
[jreimann@jreimann]~/.oh-my-zsh% source lib/misc.zsh 
bash: env_default: command not found...
lib/misc.zsh:22: command not found: env_default
bash: env_default: command not found...
lib/misc.zsh:23: command not found: env_default
[jreimann@jreimann]~/.oh-my-zsh% curl -X POST --insecure -T addresses.json -H "content-type: application/json" https://$\(oc -n enmasse get route restapi -o jsonpath='{.spec.host}')/apis/enmasse.io/v1alpha1/namespaces/enmasse/addressspaces/default/addresses

~~~

**Comment by mcornella** [comment] 2018-09-01 11:29
That's expected behavior because it's inside a URL (pasting a quoted URL should get rid of this behavior). Can you try with your first example, `echo $(foo bar)`?

**Comment by AlmightyOatmeal** [comment] 2018-09-03 22:38
+1

**Comment by ctron** [comment] 2018-09-04 07:13
@mcornella  Well I definitely don't expect that behavior, so how can I turn this off?
@AlmightyOatmeal Sorry, that didn't work.

**Comment by AlmightyOatmeal** [comment] 2018-09-04 14:50
@ctron,

If you added it to your `~/.zshrc` file, did you `source ~/.zshrc` or load a new shell? You can otherwise run the command outright to test it like I did on my work machine:
```
$ wget https://media.giphy.com/media/t6Jlf4jIk1GbS/giphy.gif\?taco\=cat
--2018-09-04 09:47:34--  https://media.giphy.com/media/t6Jlf4jIk1GbS/giphy.gif?taco=cat
Resolving media.giphy.com (media.giphy.com)... 151.101.150.2
Connecting to media.giphy.com (media.giphy.com)|151.101.150.2|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1250157 (1.2M) [image/gif]
Saving to: ‘giphy.gif?taco=cat’

giphy.gif?taco=cat                    100%[=========================================================================>]   1.19M  1.20MB/s    in 1.0s

2018-09-04 09:47:35 (1.20 MB/s) - ‘giphy.gif?taco=cat’ saved [1250157/1250157]
```
```
$ zstyle ':urlglobber' url-other-schema
```
```
$ wget https://media.giphy.com/media/t6Jlf4jIk1GbS/giphy.gif?taco=cat
zsh: no matches found: https://media.giphy.com/media/t6Jlf4jIk1GbS/giphy.gif?taco=cat

$ wget "https://media.giphy.com/media/t6Jlf4jIk1GbS/giphy.gif?taco=cat"
--2018-09-04 09:48:06--  https://media.giphy.com/media/t6Jlf4jIk1GbS/giphy.gif?taco=cat
Resolving media.giphy.com (media.giphy.com)... 151.101.150.2
Connecting to media.giphy.com (media.giphy.com)|151.101.150.2|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1250157 (1.2M) [image/gif]
Saving to: ‘giphy.gif?taco=cat.1’

giphy.gif?taco=cat.1                  100%[=========================================================================>]   1.19M  1.09MB/s    in 1.1s

2018-09-04 09:48:08 (1.09 MB/s) - ‘giphy.gif?taco=cat.1’ saved [1250157/1250157]
```

**Comment by ctron** [comment] 2018-09-04 15:32
> If you added it to your ~/.zshrc file, did you source ~/.zshrc or load a new shell?

I did start a new shell. … 

So I tried your proposal. Executing this in the shell, works for me as well. So I re-activated it in the `.zshrc` again … still no luck. I don't know what the difference is, but putting it in the `~/.zshrc`, doesn't work for me. And it is the last active statement in that file, the rest are only comments.

**Comment by AlmightyOatmeal** [comment] 2018-09-04 15:37
@ctron,

Since the command by itself does work then your zsh may not be reading `~/.zshrc`; if zsh is reading a file other than `~/.zshrc` then add it to the respective and appropriate file for your configuration/operating system.

The other thing that may be happening is that the shell is aborting reading the entire file due to an error so only some of the variables get set and some of the commands get executed but not all. This will take a little investigation on your part but at least there is a viable solution.

**Comment by ctron** [comment] 2018-09-04 15:44
I definitely is reading this file,`.zshrc`. I did add an `echo` after this line, to check if this gets executed up until this point. And I could see the output when starting a new shell instance.

When I start `zsh -v`, then I can see my statement disable this:

~~~
…
# disable auto escape
zstyle ':urlglobber' url-other-schema
~~~

And when I run int that same shell `zstyle` I do get:

~~~
…
tag-order
        :completion:*:cd:* local-directories directory-stack path-directories
url-globbers
(eval)  :url-quote-magic 'zmodload -i zsh/parameter;
	 reply=( noglob
		 ${(k)galiases[(R)(* |)(noglob|urlglobber|globurl) *]:-}
		 ${(k)aliases[(R)(* |)(noglob|urlglobber|globurl) *]:-} )'
url-local-schema
        :urlglobber ftp file
url-metas
        :url-quote-magic:* '*?[]^(|)~#{}='
url-other-schema
        :urlglobber http https ftp
url-seps
(eval)  :url-quote-magic:* 'reply=(";&<>${histchars[1]}")'
use-cache
        :completion::complete:* 1
…
~~~

When I execute `zstyle ':urlglobber' url-other-schema` it changes to:

~~~
…
tag-order
        :completion:*:cd:* local-directories directory-stack path-directories
url-globbers
(eval)  :url-quote-magic 'zmodload -i zsh/parameter;
	 reply=( noglob
		 ${(k)galiases[(R)(* |)(noglob|urlglobber|globurl) *]:-}
		 ${(k)aliases[(R)(* |)(noglob|urlglobber|globurl) *]:-} )'
url-local-schema
        :urlglobber ftp file
url-metas
        :url-quote-magic:* '*?[]^(|)~#{}='
url-other-schema
        :urlglobber
url-seps
(eval)  :url-quote-magic:* 'reply=(";&<>${histchars[1]}")'
use-cache
        :completion::complete:* 1
…
~~~

**Comment by mlibbey** [comment] 2018-11-27 02:11
Is this a dupe of #5499 ?

**Comment by AlmightyOatmeal** [comment] 2018-11-27 02:53
That issue is very specific to two versions of OS X where-as this is not. I have had this issue on more versions of OS X than listed but seems to only be on OS X versions of zsh obtained from brew.

**Comment by ctron** [comment] 2018-11-27 07:46
And I do have it on CentOS, so this is not a Mac OS X only issue.

**Comment by shai-kappel** [comment] 2019-01-24 12:45
@AlmightyOatmeal 10x man this solved the issue for me, i wish it will be included OOB in future releases of zsh

**Closed** 2019-05-11 11:50 UTC

**Comment by mcornella** [comment] 2019-05-11 11:52
After the latest update (run `upgrade_oh_my_zsh`), you can add `DISABLE_MAGIC_FUNCTIONS=true` to your zshrc (before OMZ is sourced) to bypass the loading of the magic functions.
