### ISSUE TITLE
Install fails due to missing zsh

### ISSUE THREAD

**Issue by griffins** [robbyrussell/oh-my-zsh#5925] opened 2017-02-28 23:54 UTC
My current distro does have the /etc/shells file. can't we have another way of checking the existence of zsh other than that file's contents? maybe try checking if zsh exists in the current PATH.?

I had to manually create the file and populate it to complete the installation

In case ones stuck, here is what i did,
create a file ```/etc/shells```
add the line ```/zsh```

**Comment by belak** [comment] 2017-03-02 01:06
This would be a fairly simple fix. I've opened a PR which should resolve it.

That being said, /etc/shells is traditionally used to choose what shells can be set as user login shells... so not having it there usually means there's something odd going on.

**Comment by belak** [comment] 2017-03-02 09:44
After more investigation, it looks like this is a duplicate of #4955

**Comment by mcornella** [comment] 2018-05-05 19:16
Duplicate of #4955

**Closed by mcornella** 2018-05-05 19:16 UTC
