### ISSUE TITLE
After updating, it is not possible to view the folder where I am

### ISSUE THREAD

**Issue by joaoduartemariucio** [robbyrussell/oh-my-zsh#7649] opened 2019-03-11 11:33 UTC
Recept error:
```
Last login: Mon Mar 11 08:29:59 on ttys003
/Users/joaoduarte/.oh-my-zsh/oh-my-zsh.sh:45: parse error near `||'
Joao-Duarte%
```

<img width="575" alt="Captura de Tela 2019-03-11 às 08 32 44" src="https://user-images.githubusercontent.com/31930009/54121104-4fa94100-43d8-11e9-911d-538aab95bc28.png">

**Comment by mcornella** [comment] 2019-03-12 18:31
Duplicate of #6387. See https://github.com/robbyrussell/oh-my-zsh/issues/4870#issuecomment-187609788

**Closed by mcornella** 2019-03-12 18:31 UTC
