### ISSUE TITLE
`gem push TAB` raises error

### ISSUE THREAD

**Issue by mehdisadeghi** [robbyrussell/oh-my-zsh#7788] opened 2019-04-22 17:59 UTC
I get the following error when typing `gem push` with a tab following:

```
_arguments:comparguments:325: doubled rest argument definition: *:gem:_files -g "*.gem(-.)"
```

`gem + TAB` works fine. I'm not sure whether this is a bug, filing anyway since this may be someone else's problem too.

P.S. I initially posted this to [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions/issues/423) but according to folks over there this is not their issue.

**Comment by mcornella** [comment] 2019-04-22 19:13
Try reset the completion cache: `rm ~/.zcompdump*` and restarting the shell.

**Comment by mehdisadeghi** [comment] 2019-04-24 15:43
@mcornella I did as you suggested and the error persists.

**Comment by mcornella** [comment] 2019-05-07 19:07
I suppose you're not using the `gem` plugin, in which case the issue is within zsh's official gem completion. What `zsh --version` are you using?

**Comment by mehdisadeghi** [comment] 2019-05-15 21:55
@mcornella yes, I'm not using the gem plugin. I noticed that by enabling the gem plugin the errors go away. I don't get any suggestions for `gem push` however.

**Comment by mcornella** [comment] 2019-05-17 13:03
This was fixed 11 days ago: https://github.com/zsh-users/zsh/commit/191e05b1083d8c8ac8b2858c9278a7bd5414881f. I guess it will be in the next zsh version. In the meantime, you can download the `_gem` file and put it in some folder that's in `$fpath`. Remember to clean up the zcompdump files afterwards to reset the completion: `rm ~/.zcompdump*`.

Related: https://github.com/rubygems/rubygems/issues/2758
Related: https://github.com/zsh-users/zsh/pull/35

**Closed by mcornella** 2019-05-17 13:03 UTC
Labels: Topic: completion, Type: support

**Comment by mehdisadeghi** [comment] 2019-05-17 13:59
@mcornella thanks for your support and constructive comments. The workaround worked like charm. Much appreciated.

**Comment by mcornella** [comment] 2019-05-17 15:53
Thank you for your kind feedback!
