### ISSUE TITLE
✨, 🥕 and all Unicode 9 emoji appear as hex codes

### ISSUE THREAD

**Issue by CarrotEngineer** [robbyrussell/oh-my-zsh#5712] opened 2016-12-13 20:26 UTC
## Version information
Commit: `26aae6b5834e1342d9b95a894a5bb24159b367bf`
zsh version: `zsh 5.3 (x86_64-apple-darwin16.1.0)`
macOS version: `10.12.2`
Terminal version: Tested on iTerm 2, Terminal

## Issue
Reproduction steps:
* Paste "✨🥕🐰" a terminal of your choosing whilst using oh-my-zsh
* Observe the output is: `<2728><0001f955>🐰` instead of `✨🥕🐰`
![screen shot 2016-12-13 at 20 21 36](https://cloud.githubusercontent.com/assets/149851/21157670/0deed2ec-c172-11e6-85c7-4d59b016ead4.png)

## Other comments
I'm aware this might be a ZSH issue, but I tried searching and couldn't find anything listed, so figured I'd post here first. Could you point me in the right direction for help if it is please?

If I run `bash` and then paste, everything appears fine.
![screen shot 2016-12-13 at 20 25 11](https://cloud.githubusercontent.com/assets/149851/21157721/4629de04-c172-11e6-98a8-7920feb2203a.png)

**Comment by mcornella** [comment] 2016-12-14 16:46
I don't have zsh 5.3 nor macOS so I cannot reproduce. Try running `zsh -f`, which effectively bypasses the dot files configuration. If the issue persists, then it's not an Oh My Zsh issue.

**Comment by CarrotEngineer** [comment] 2016-12-14 18:14
When I do that, the ✨ shows up, but the Unicode 9 character still doesn't. So it seems like both Oh My Zsh and Zsh itself are at fault?
![screen shot 2016-12-14 at 18 13 31](https://cloud.githubusercontent.com/assets/149851/21194787/2217cd98-c229-11e6-8bc1-c30c99e19cd7.png)

**Comment by CarrotEngineer** [comment] 2016-12-14 18:15
Actually - that was on a server. On my local machine, it's still all wrong with the `-f`.
![screen shot 2016-12-14 at 18 15 13](https://cloud.githubusercontent.com/assets/149851/21194829/477a35d0-c229-11e6-9919-acc4d492ee38.png)

I'm even more confused than before. Is there somewhere else I should raise this?

**Comment by mcornella** [comment] 2016-12-14 18:19
You can try at the zsh-users mailing list in [zsh.org/mla](http://www.zsh.org/mla/). I'll close this for the time being since it doesn't seem to be a problem with OMZ. Thanks!

**Closed by mcornella** 2016-12-14 18:19 UTC

**Comment by dubert** [comment] 2018-09-10 15:23
@CarrotCodes I have the same issue, is there a way you fixed this?

**Comment by IonVillarreal** [comment] 2021-07-05 22:13
any news about it? I have a good time

**Comment by rwmitchell** [comment] 2021-07-05 22:40
Issue is likely with your font.  What terminal program and font(s) are you using?

**Comment by IonVillarreal** [comment] 2021-07-05 22:55
<img width="682" alt="image" src="https://user-images.githubusercontent.com/12217695/124522841-964db100-ddc2-11eb-9099-0fcadad35e76.png">

thanks for replying, i use macOS Big Sur

**Comment by rwmitchell** [comment] 2021-07-05 23:06
You answered neither of my questions.  Looks like you're using Terminal.app in OS X?  iTerm2 is better.

You also need a font that contains they glyphs at the hex codes you're expecting.

There are two main types,
nerdfont and something else.  p10k is particular about which you have installed.  I use:
```SauceCodeProNerdFontComplete-Regular```

iTerm2 is better because it allows defining two fonts; the regular font and a non-ascii font, which it uses for glyphs.
