### ISSUE TITLE
Problem with tmux plugin and Fedora 20

### ISSUE THREAD

**Issue by thomasehardt** [robbyrussell/oh-my-zsh#3345] opened 2014-11-26 16:07 UTC
Tried this with a fresh install (as in a stock F20 install from ISO) ... when I use the tmux plugin on Fedora 20, it does not load ~/.tmux.conf

Is there a way to run oh-my-zsh in debug/logging mode? If this is a bug in the tmux plugin, I'll be happy to submit a pull request, but I don't know if there's a way to log from oh-my-zsh

This _only_ happens when using gnome-terminal; xterm does not have this problem

Here's what it loks like:
![tmux-issues](https://cloud.githubusercontent.com/assets/669341/5205996/f6918b48-7561-11e4-8c72-186374d7ce93.png)

**Comment by thegcat** [comment] 2015-01-16 18:35
I'm experiencing the same issue, on OS X in the Terminal.app though. Any pointers?

**Comment by thegcat** [comment] 2015-01-16 20:18
For some reason this https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/tmux/tmux.plugin.zsh#L40 breaks havoc in the plugin.

**Comment by apjanke** [comment] 2015-07-05 07:28
I can't reproduce. On OS X 10.9.5, when running OMZ with the default `.zshrc` and the `tmux` plugin added, it's loading my `~/.tmux.conf` file. I can see the difference in the screen layout between when the file is present and absent.

What version of OS X and tmux are you on? Is this still happening with the current version of OMZ?

How do you know that it is that line that is causing problems?

**Comment by apjanke** [comment] 2015-07-05 07:59
Oh, wait, what line are you referring to there? That link is to the "master" branch, which means it always points to the latest commit. There have been changes to the file since you posted that comment, which means that lines have shifted around, and that link is probably no longer pointing to the code it was when you first post it. When posting links to lines in code, it's best to link to a specific commit, which is less likely to change over time.

**Comment by apjanke** [comment] 2015-07-05 08:00
At any rate, doing `zsh -x` or temporarily doing `setopt xtrace` will run `zsh` in debugging mode, which will echo everything it's doing. This will be a *lot* of output, though.

You can do this right before loading the plugin. Leave `tmux` off your `$plugins` list, and then do this.
```
setopt xtrace; source .oh-my-zsh/plugins/tmux/tmux.plugin.zsh; setopt noxtrace
```

You can also set it right before running tmux after the plugin is loaded.
```
setopt xtrace; tmux; setopt noxtrace
```

**Comment by thegcat** [comment] 2015-07-05 14:50
@apjanke thanks for the explanations, and thanks for following up on an oldish ticket :-)

I recently had to reinstall my system and have been running stock oh-my-zsh without any problems since then, so as this was fixed for @thomasehardt too I think it can be closed.

**Comment by apjanke** [comment] 2015-07-05 23:27
Cool. @thomasehardt, can you close this issue if it's working for you now?

**Closed** 2018-08-03 20:39 UTC
Labels: tmux
