### ISSUE TITLE
mktemp does not support --tmpdir on MacOS

### ISSUE THREAD

**Issue by millsyman** [robbyrussell/oh-my-zsh#7803] opened 2019-04-25 18:19 UTC
The colorize_via_pygmentize_less function does not work on MacOS as mktemp does not support the tmpdir option. It fails with

> mktemp: illegal option -- -
> usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
>        mktemp [-d] [-q] [-u] -t prefix
> colorize_via_pygmentize_less:13: no such file or directory:
> : No such file or directory

The function seems to work without the tmpdir option
https://github.com/robbyrussell/oh-my-zsh/blob/adade64cda7af2bb2f23b95a57f91f7010aa0cb8/plugins/colorize/colorize.plugin.zsh#L42
@fzuviria

**Comment by mcornella** [comment] 2019-04-25 18:37
Duplicate of #7789

**Closed by mcornella** 2019-04-25 18:37 UTC
