### ISSUE TITLE
Keyboard input disabled after paste

### ISSUE THREAD

**Issue by LukeMauldin** [robbyrussell/oh-my-zsh#4434] opened 2015-09-30 14:33 UTC
I updated oh_my_zsh this morning to SHA a9c8820.  If I try to paste into the terminal, the paste does not work and all keyboard input is disabled for that session.  I have to create a new session to be able to type again.  This was all working before the update.  I have duplicated the behavior on both iTerm and the OSX Terminal App.  OSX version: 10.10.5  ZSH version: 5.1.1

~/.zshrc
```
# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="lmauldin"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment following line if you want to  shown in the command execution time stamp 
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
# HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
#plugins=(git osx bower brew composer golang laravel sublime)

source $ZSH/oh-my-zsh.sh

# User configuration

export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/lmauldin/dev/lmauldin/codenvy-cli/assembly/target/codenvy-cli-2.3.0/codenvy-cli-2.3.0/bin"
# export MANPATH="/usr/local/man:$MANPATH"

# # Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

#custom configuration
source $HOME/.aliases
export HOMEBREW_BUILD_FROM_SOURCE=1
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

#Add golang path 
export GOPATH=/Users/lmauldin/dev/goexternal
export PATH="$GOPATH/bin:/Users/lmauldin/dev/gosrc/bin:$PATH"
export GOROOT=/Users/lmauldin/dev/gosrc
#export GOROOT=/usr/local/opt/google-cloud-sdk/platform/google_appengine/goroot/
export GO15VENDOREXPERIMENT=1

#Add dartlang to path
export PATH="/usr/local/opt/dart-sdk/bin:$PATH"

#Add play path
export PATH="/usr/local/opt/play-2:$PATH"

#Add composer to path
export PATH="$PATH:$HOME/.composer/vendor/bin"


# The next line updates PATH for the Google Cloud SDK.
#source /usr/local/opt/google-cloud-sdk/path.bash.inc
export PATH="/usr/local/opt/google-cloud-sdk/bin:$PATH"

# The next line enables bash completion for gcloud.
#source /usr/local/opt/google-cloud-sdk/completion.bash.inc

#Set Java GAE path (needed for GAE Gradle plugin)
export APPENGINE_HOME="/usr/local/opt/google-cloud-sdk/platform/appengine-java-sdk"

# Source PHPBrew
source $HOME/.phpbrew/bashrc

# Add aliases for Emacs
alias e='emacsclient -t'
alias ec='emacsclient -c'

# Add env variables for apps
export PMHOME="/Users/lmauldin/dev/pe/apps/pmtool"
export ERP408HOME="/Users/lmauldin/dev/pe/apps/pmtool/erp-extender/pms408"
export ERP420HOME="/Users/lmauldin/dev/pe/apps/pmtool/erp-extender/pms420"


 eval $(ssh-agent)

function cleanup {
   echo "Killing SSH-Agent"
   kill -9 $SSH_AGENT_PID
 }

trap cleanup EXIT

```

**Comment by apjanke** [comment] 2015-09-30 17:25
Possibly related to #4337. I'm unable reproduce on 10.9.5 or 10.11 beta, though, and don't have a 10.10 box around for testing.

**Comment by LukeMauldin** [comment] 2015-09-30 17:29
I did notice that I had to start putting quotes around the urls when using youtube-dl recently.  That was before zsh input broke entirely after doing a paste.  I did reboot my machine but the behavior is the same.

**Comment by apjanke** [comment] 2015-09-30 23:02
Well, that's not good.

Could you run `omz_diagnostic_dump` and post the results [as a gist](https://gist.github.com/), so we have full diagnostic info? If we can't reproduce it based on that, I'll set up a 10.10 testing box.

**Comment by LukeMauldin** [comment] 2015-10-01 10:19
https://gist.github.com/LukeMauldin/33f95073b63745cd612a

**Comment by apjanke** [comment] 2015-10-02 22:20
Hmmm. Something's not quite right. I don't see anything obvious in that gist. (The "core commands redefined" is a false alarm; `omz_diagnostic_dump` just doesn't understand the 5.1.1 implementations yet.) But with zsh 5.1.1 and the current OMZ, the `url-quote-magic` should be working to auto-escape those pasted YouTube URLs, even with no plugins loaded.

Could you add your `lmauldin.zsh-theme` file to the gist so we can see it, too? Looks like there's some terminal escape sequences in there; maybe they're interacting with something. (I'd also suggest moving that theme to `custom/themes` or an external `$ZSH_CUSTOM` directory, so it doesn't show up as a spurious untracked file in your OMZ installation.)

**Comment by apjanke** [comment] 2015-10-03 02:24
FWIW, I'm also seeing issues with bracketed paste in `vim` on OS X 10.9. (It ends up "smart indenting" stuff when it shouldn't.) Something is really not quite right here, but I can't figure out what it is yet.

**Comment by kevinburkeshyp** [comment] 2015-10-03 16:31
FWIW, I can also reproduce this issue. ZSH 5.1.1, OS X 10.10.5. Let me know if I can help debug - alternatively, any idea of mitigation steps ?

**Comment by apjanke** [comment] 2015-10-03 16:35
For mitigation, you could copy `lib/misc.zsh` to your `$ZSH_CUSTOM` and comment out [this section](https://github.com/robbyrussell/oh-my-zsh/blob/19c0b185ad9b37b448a979fb6cc995cc648e76a4/lib/misc.zsh#L1-L11) to disable the url quoting and bracketed paste support. You'd lose safe pasting but it might keep things from locking up.

**Comment by apjanke** [comment] 2015-10-03 22:12
Got another report that sounds like this: #4452. And it's not just OMZ, I just saw a similar bug report on the Zsh developers list: ["[BUG] bracketed-paste-magic breaks pasting of CJK payload"](http://www.zsh.org/mla/workers/2015/msg02680.html).

This is common enough we might need to add an option to disable bracketed paste, or detect zsh versions where it's buggy and turn it off there. Let's see what comes out on the Zsh list thread. In the mean time, knocking it out in `lib/misc.zsh` should mitigate it.

**Comment by apjanke** [comment] 2015-10-03 22:42
Happens without OMZ loaded, too. Pretty clear this is an upstream `zsh` bug in `zsh` 5.1.1.

This is enough to reproduce:
```
zsh -f
autoload -Uz bracketed-paste-magic
zle -N bracketed-paste bracketed-paste-magic
echo  # and then paste 惷惼誃 here
```

(`zsh -f` runs zsh without any of the startup files, so is an easy way to test behavior in a stock non-OMZ zsh.)

**Comment by apjanke** [comment] 2015-10-03 22:51
From the zsh developers mailing list:

> Known issue, fixed Sept. 11 by workers/36496 plus 36525 on Sept. 12.

Sounds like maybe we should not enable `bracketed-paste-magic` when running under zsh 5.1.1. Or just advise users to use a different version of zsh if they work with non-English text regularly. Thoughts?

**Comment by LukeMauldin** [comment] 2015-10-04 18:42
The latest oh-my-zsh update resolved my problem without pasting.  Do you want me to close this issue?

**Comment by apjanke** [comment] 2015-10-05 09:42
That's a surprise. We didn't check in any fixes for it as far as I know, and it is still broken for me after updating to the current OMZ.

Let's leave this open until we have a confirmed fix, because I bet other people are still experiencing it.

Any ideas what in particular fixed it for you in this last update?

**Comment by LukeMauldin** [comment] 2015-10-05 17:00
The last time I ran update-oh-my-zsh, I saw that lib/misc.zsh was updated so I just figured that fixed it.  If you have anything you want me to try, just let me know.

**Comment by apjanke** [comment] 2015-10-06 03:37
Hmmmm... the [last two commits](https://github.com/robbyrussell/oh-my-zsh/commits/master/lib/misc.zsh) were for `ack-grep`, which is totally unrelated. Last update before that was on [Sep 10](https://github.com/robbyrussell/oh-my-zsh/commit/19c0b185ad9b37b448a979fb6cc995cc648e76a4#diff-d0d9b77e802868afae51086e4b3e7dd1), and that's what (I think) would have caused this problem in the first place: it was the one that *enabled* bracketed-paste-magic support. There's no fix in recent updates.

Glad it's resolved for you! But it's still busted for other users. Your report here is the best description of the issue, so I'd like to leave it open until we understand it and have a fix for everyone. Would you mind not closing this until we have a confirmed fix, or a well-understood and documented workaround? If you don't want to get notification emails from GitHub, I think you can click the "Unscubscribe" button over that way. ------->

**Comment by kevinburkeshyp** [comment] 2015-10-06 03:40
This is still broken for me on latest `.oh-my-zsh` and 5.1.1

**Comment by andycaramba** [comment] 2015-10-06 16:55
I have the same issue. Pasting from clipboard with any characters (only english too) pastes nothing and breaks keyboard input until ctrl+c. When I comment `source "$ZSH/oh-my-zsh.sh"` clipboard pasting works fine. Turning off all zsh plugins has no effect.

```
OMZ commit f3fa41834d9c954ee2d352c6c5b60d72f7a93593
OS X 10.11 (on 10.10 I had this issue too)
zsh 5.1.1 (x86_64-apple-darwin14.5.0)
```

**Comment by apjanke** [comment] 2015-10-07 01:07
Hi folks, here's a workaround that just doesn't enable bracketed-paste or url-quote under 5.1.1. Works for me. Give it a try and let me know if it fixes it for you.

https://github.com/apjanke/oh-my-zsh/tree/5_1_1-bracketed-paste-hack

To try this out locally:
```
cd ~/.oh-my-zsh
git remote add apjanke https://github.com/apjanke/oh-my-zsh.git
git fetch apjanke
git checkout apjanke/5_1_1-bracketed-paste-hack
```
and then launch a new terminal session.

**Comment by andycaramba** [comment] 2015-10-08 11:34
@apjanke Hi. Your workaround works for me too. I've just deleted smart urls block and clipboard pasting now works fine. Thank you. PR?

**Comment by apjanke** [comment] 2015-10-08 23:07
PR: #4473

**Comment by apjanke** [comment] 2015-10-09 02:00
Actually, since bracketed paste mode [is now the default in zsh 5.1.1](https://github.com/zsh-users/zsh/blob/zsh-5.1.1/README#L35-L45), maybe the real fix is to tweak `url-quote-magic` to work with it, and not require `bracketed-paste-magic`.

**Closed** 2015-10-20 06:26 UTC

**Comment by apjanke** [comment] 2015-10-20 11:25
PR is merged. Update OMZ and give it another try, folks...

**Comment by mlibbey** [comment] 2017-10-23 23:04
bracketed-paste-magic is still broken on Mac 10.12 and 10.13, which translate to zsh 5.2 and zsh 5.3.
