### ISSUE TITLE
Integration with Git-radar

### ISSUE THREAD

**Issue by mpdehnel** [robbyrussell/oh-my-zsh#4290] opened 2015-08-28 10:09 UTC
Would there be any way to integrate Git-Radar (https://github.com/michaeldfallen/git-radar) with oh-my-zsh e.g. as a plugin? I know some of its functionality is included in the plugin git-prompt, but not all of it is there, and it looks really useful, but I don't want to stop using oh-my-zsh :-)

Thanks!

**Comment by mcornella** [comment] 2015-09-01 18:37
Duplicate of #4288

**Closed** 2018-06-15 21:17 UTC
