### ISSUE TITLE
How to search for a previous command with the prefix I just typed, using arrow keys preferably?

### ISSUE THREAD

**Issue by NightMachinary** [robbyrussell/oh-my-zsh#6869] opened 2018-05-28 22:20 UTC
And not using C-r.

**Comment by NightMachinary** [comment] 2018-05-28 22:30
Found the solution:
https://github.com/robbyrussell/oh-my-zsh/issues/1720#issuecomment-286366959

**Comment by NightMachinary** [comment] 2018-05-28 22:31
I suggest incorporating it into the canon source code; Very unuserfriendly for new users.

**Comment by mcornella** [comment] 2018-06-12 15:35
[It's already added](https://github.com/robbyrussell/oh-my-zsh/blob/019e0d7c71429650de33b5fb48b066ee46f37199/lib/key-bindings.zsh#L30), the problem is that you're using vi mode and so the bindkeys are not set up for vi mode. This will be fixed once #5113 is merged, so if you'd like you can go ahead and test it. It might cause other issues but your input would be very much appreciated.

**Closed by mcornella** 2018-06-12 15:35 UTC
