### ISSUE TITLE
[Discuss] What should installer behavior be, esp wrt launching new shells?

### ISSUE THREAD

**Issue by apjanke** [robbyrussell/oh-my-zsh#4393] opened 2015-09-23 23:25 UTC
We've had some issues around the installer scripts and their interactive behavior for a while, not just with the implementation, but with the design and desired behavior. Let's hash out exactly what we want it to do, and why.

This issue is specifically _not_ about how `$PATH`  is altered by the constructor; I don't want that to distract from the other issues. `$PATH` is important, but it is out of scope for this issue. See #1359 for discussion on that.
### Questions to consider
- Should `install.sh` and `uninstall.sh` launch new interactive shell sessions as part of the installation?
  - If so, should they `exec`, or just run as sub-processes?
- How should the scripts be invoked, and what invocation methods should be supported?
  - Should they require OMZ to run?
- Should there be an non-interactive installation option?
- How about uniform diagnostics: always print errors on `stderr`, and exit non-zero upon error?
- Any other aspects of their behavior to consider or change?
### References
- #3447: oh-my-zsh uninstall.sh issues - switch back to bash is unsatisfactory
- #3664: printf/terminfo portability – has a long discussion about the subshell invocation
- #4355: Tracking: install script related issues
#### Invocation

It's not clear exactly how some of the `tools/*.sh` files can be run. E.g. for uninstallation, the README says to "run uninstall_oh_my_zsh from the command-line", which runs `tools/uninstall.sh` under `sh`. Can `uninstall.sh` also be run on its own? I think that would be nice, so you don't depend on a running OMZ instance to do the installation. But it has now shebang line and isn't executable.

Most of the files in `tools/` look like scripts to be run as external commands. I think it would be nice to support that where possible. And for scripts where it is supported, the files should be `+x` and have a `#!` at the top to indicate which shell they run under and support direct invocation.
#### On launching subshells and sourcing

If you run an interactive subshell (or any other interactive subprocess), then the behavior of the scripts is going to differ depending on whether you use the `curl ... | sh` or `sh -c "$(curl ...)"` form, because the subprocess takes over stdin.

If you launch a subshell from a script that's run directly, instead of fully pre-buffered using `$(cat ...)`, and the script is modified while the interactive subshell is still running, it can have unpredicatble behavior and/or errors after the subshell exits.

Sourcing `/etc/profile` and `~/.zshrc` files inside running sessions is problematic. They're not designed to be run multiple times, and you don't have a clean sesion because you still have state left over from the original startup file runs.

`uninstall.sh` sources `/etc/profile` or `.zshrc`, but it doesn't detect what shell it's running under.

I think the `source` calls should be removed from `uninstall.sh` completely; it doesn't know which is the right one to invoke, and can't end up with a clean shell environment anyway. It should just tell you to restart your shell session.
#### On uninstallation
- Should probably check for local changes in `~/.oh-my-zsh` before blowing it away, to avoid destroying user data. In fact, should maybe check to make sure it points to an OMZ repo.
#### Miscellaneous

As a sysadmin and a tester of OMZ, I always appreciate a fully noninteractive option for installation and management scripts, so they can easily be run repeatedly or scripted themselves.

We should consider the case of people who have their config files like `~/.zshrc` synced across multiple machines or otherwise under source control.

**Comment by leoj3n** [comment] 2016-08-19 17:46
If you use `exec zsh` from inside a script, it takes over the process (and PID) of the script, not the shell the script was run from. If you use just `zsh` from inside a script it keeps the script process open, and spawns a new sub-process under it, both of which remain open until the new sub-process is exited.

Either way, non-exported variables will not pollute the scope, so it's probably better to subsume the script process with `exec` simply to avoid spawning another process.

The only reason you might not want to subsume the script process is if you wanted to run some cleanup or something when the `zsh` subprocess ended (any code placed after the call to `zsh`).

**Comment by loket** [comment] 2017-04-24 12:17
FYI: I updated the installation script to allow non-interactive installation (i.e. from a script): #5893

**Comment by cig0** [comment] 2017-11-12 22:15
I'm not sure is my suggestion belongs to this thread, if not please let me know and I create a new issue.

One **incredible important issue** I would like to see addressed is that the install script instead forcing the user to set Zsh as the default shell, actually _offer_ to set it.

There are multiple reasons to avoid setting Zsh as the default shell -- or, for instance, any other than the default shell shipped with the given OS.

**Comment by leoj3n** [comment] 2018-08-19 21:13
@cig0 can't you just just CTRL-C the chsh password prompt?

At any rate, it sounds like https://github.com/robbyrussell/oh-my-zsh/pull/5893 would address your concern if something like it were merged.

**Comment by apjanke** [comment] 2018-08-20 01:49
@cig0 Could you go in to a little more detail about what breakage you experienced when switching default shells? Doing `chsh` changes the user-specific login/default interactive shell. So most scripts should be unaffected. The various shells use distinct startup files, and scripts generally indicate the specific shell they are to run under using shebang lines or other mechanisms. I would think that the compatibility issues would mostly be restricted to interactive use, or things the user invokes directly with `.` or `source`.

I do agree that maybe the shell-changing should be optional, with an option to disable it entirely for unattended installs.

I think that the installation script should still at least _offer_ to change your default shell to `zsh`: OMZ is an on-ramp for new Zsh users to get in to using Zsh, and they may not know how to do that change themselves.

**Comment by mcornella** [comment] 2019-05-28 18:00
Hi everybody, #5169 introduces a flag and variable to allow skipping the default shell change. It still makes it opt-in though—maybe in a future version there will be a prompt. The thing is that #5169 has a bunch of other fixes and features, and it's now ready to test.

If you want to help speed up the testing and merge (which should happen early next week), you can wget or curl it from the URL `https://raw.githubusercontent.com/mcornella/oh-my-zsh/refactor-installer/tools/install.sh`. Read the comments at the top of the script to know how to call it.

Thanks!

**Comment by cig0** [comment] 2019-05-30 01:25
Hi @apjanke, sure: my story dates back at 2014/2015 when I was still using GNU+Linux as my daily driver: I remember that right after changing the default shell (Bash) for Zsh, invariably next time I wanted to log back into the system (after logging out) I wouldn't be able to do so. I remember this happening on Arch, Gentoo and Ubuntu. IIRC it happened because at that time I was trying to run Zsh in *native* mode (in contrast to Bash-compatible mode) and it seems those distributions shipped with scripts that wouldn't work on Zsh. Eventually, changing the default shell back to Bash solved the issue all the times.
About Zsh on macOS I can confirm it works as expected on High Sierra -- that is, no (visible) breakage here. I can't speak for Mojave as I'm not currently using Zsh anymore.

**Comment by mcornella** [comment] 2019-06-01 19:14
> It still makes it opt-in though—maybe in a future version there will be a prompt.

I've pushed an update that adds a prompt to ask the user if they want to change the default shell to zsh, defaulting to yes.

**Comment by mcornella** [comment] 2019-06-03 15:28
Closed by #5169.

**Closed by mcornella** 2019-06-03 15:28 UTC
Labels: Area: installer, Type: discussion
