### ISSUE TITLE
COMPLETION_WAITING_DOTS breaks multi-line prompts

### ISSUE THREAD

**Issue by muesli** [robbyrussell/oh-my-zsh#5767] opened 2017-01-10 13:40 UTC
Setting COMPLETION_WAITING_DOTS to true breaks multiline prompts. It will move the cursor up to the first line of the prompt and the completion output will start in the middle of your prompt.

**Comment by muesli** [comment] 2017-01-10 13:51
Update: This problem gets triggered by 'zle redisplay' apparently.

**Comment by AlecBenzer** [comment] 2017-11-30 16:35
Hm, interesting. I had a multi-line prompt and completion dots on with no issues before, but it broke after upgrading to High Sierra. Maybe the zsh version changed?

**Comment by krupenja** [comment] 2019-02-05 21:38
For me this is broken on macOS Mojave (and I *think* it was fine in High Sierra) but works fine on Ubuntu 18.10.

**Comment by krupenja** [comment] 2019-02-06 16:50
Interestingly, I cannot reproduce this with `bira` theme, which has multiline prompt. This theme is the only theme with multiline prompt that I have tried and that does not not have a clock. Perhaps that is the cause?

**Comment by mcornella** [comment] 2019-06-27 14:49
Closing as duplicate of #5765.

**Closed by mcornella** 2019-06-27 14:49 UTC
Labels: Area: theme, Topic: completion, Type: bug
