### ISSUE TITLE
Make setting the default shell during installation optional

### ISSUE THREAD

**Issue by bbil** [robbyrussell/oh-my-zsh#7865] opened 2019-05-20 03:35 UTC
Setting the default shell to`/bin/zsh` has been causing me some problems. Particularly on linux systems, there is a problem that comes up where having `zsh` as the default shell causes snap packages to misbehave and not show in the application launcher. Changing the default shell back to `/bin/bash` fixes the problem.

https://forum.snapcraft.io/t/desktop-snaps-do-not-appear-in-the-dash-menu-on-gnome-in-17-10-final-beta/2340/13

Furthermore, there doesn't seem to be any way to stop this behavior from happening. Other than killing the install process when `chsh` is prompting for your password. Although, this may not even work if you've already granted `sudo` permissions on your current session (haven't tested that out).

**Describe the solution you'd like**
Prompt user with a choice, if they would like to change their default shell.

Many users may not even know what this means, so an explanation of what changing this actually means would be a nice touch.

Also, during this prompt to change the default shell, there could be an explanation on configuring your terminal emulator to start `zsh` instead of `bash`. Since the main purpose of setting the default shell is to make `zsh` execute immediately when opening a terminal. Maybe that should be the approach instead of trying to change something on the system level?

**Additional context**
Some other related issues have been raised in the past about `oh-my-zsh`s setting of the default shell, both during the install and uninstall process. Where the uninstall script just assigns the default shell back to `/bin/bash` instead of the user's preferred shell (e.g. `fish`)
https://github.com/robbyrussell/oh-my-zsh/issues/7721

**Comment by mcornella** [comment] 2019-05-20 16:15
Duplicate of #7721 and #7100 but I appreciate the extra information. I'm working on it!

**Closed by mcornella** 2019-05-20 16:15 UTC
Labels: Type: feature request

**Comment by mcornella** [comment] 2019-05-28 17:51
Hi there, I could finally finish #5169 to add an option not to change the default shell, and it's now ready for testing. I could use comments and suggestions on what is good and what should change.

If you want to help speed up the testing and merge (which should happen early next week), you can wget or curl it from the URL `https://raw.githubusercontent.com/mcornella/oh-my-zsh/refactor-installer/tools/install.sh`. Read the comments at the top of the script to know how to call it.

Thanks!
