### ISSUE TITLE
Segmentation Fault on LS -LA alias (l)

### ISSUE THREAD

**Issue by Splace42** [robbyrussell/oh-my-zsh#5696] opened 2016-12-08 21:04 UTC
Try to write l\ and press enter two time

Cya zsh :D

**Comment by mcornella** [comment] 2016-12-08 21:43
Can't reproduce
```
$ alias l='ls -la'
$ l\
> 
total 132
drwxr-xr-x  2 XXXX XXXX   4096 dic  8 22:39 .
drwxr-xr-x 83 XXXX XXXX 126976 dic  8 22:39 ..
$ zsh --version
zsh 5.2 (x86_64-debian-linux-gnu)
```

Please provide more information about your system and test on multiple filesystems.

**Comment by Splace42** [comment] 2016-12-09 19:14
```Last login: Fri Dec  9 20:12:28 on console
➜  ~ sh
sh-3.2$ zsh
➜  ~ l\
>
Segmentation fault: 11
sh-3.2$ ZSH
➜  ~ zsh --version
zsh 5.0.8 (x86_64-apple-darwin15.0)
➜  ~
➜  ~````

**Comment by mkwardakov** [comment] 2016-12-14 19:42
It is definitely not a oh-my-zsh issue, please see http://stackoverflow.com/questions/14248514/what-could-possibly-cause-a-linux-ls-command-to-return-a-seg-fault

**Comment by mcornella** [comment] 2016-12-14 22:04
Closing then. If it turns out to be an Oh My Zsh issue feel free to reopen.

**Closed by mcornella** 2016-12-14 22:04 UTC
Labels: not our issue, question
