### ISSUE TITLE
when I login，show sth wrong

### ISSUE THREAD

**Issue by ybjie** [robbyrussell/oh-my-zsh#5525] opened 2016-10-12 11:06 UTC
info:
/Users/yubingjie/.oh-my-zsh/tools/check_for_upgrade.sh:3: failed to load module `zsh/datetime': dlopen(/usr/lib/zsh/5.0.8/zsh/datetime.so, 9): image not found
_current_epoch:1: bad math expression: operand expected at `/ 60 / 60 ...'

Here is some commands I tried
which -a zsh
/usr/local/bin/zsh
/bin/zsh

echo $path
/usr/local/bin /usr/bin /bin /usr/sbin /sbin

Also I have tried uninstall oh-my-zsh and re-installed,but the problem still occcured

**Comment by mcornella** [comment] 2016-10-13 22:00
Duplicate of #5438, please subscribe to that issue and follow the solutions suggested there.

**Closed by mcornella** 2016-10-13 22:00 UTC
