### ISSUE TITLE
Inconsistencies in ZSH compared to Bash 

### ISSUE THREAD

**Issue by 0x0luke** [robbyrussell/oh-my-zsh#8377] opened 2019-11-12 13:21 UTC
**Describe the bug**
There seems to be a inconsistency in the way ZSH manages incrementing strings to a variable - In bash the code below will output something along the lines of 

`test2_filename.txt`

If the script is executed with the ZSH shell, it throws a syntax error.
`./test.sh: 4: ./test.sh: var1+=_filename.txt: not found`

**To Reproduce**
PoC code provided below:
```
var1="test"
var2="test2"

var1=$var2 && var1+="_filename.txt"

echo $var1
```

**Expected behavior**
The script should output test2_filename.txt, however when it's executed with the ZSH shell, it throws a syntax error - This doesn't occur with the Bash shell.

As seen here; += should be supported in ZSH: http://zsh.sourceforge.net/Doc/Release/Arithmetic-Evaluation.html

**System:**
 - OS: Raspbian Linux 9 - Also reproducible on MacOS Catalina 
 - Zsh version 5.6.1

**Comment by mcornella** [comment] 2019-11-14 17:21
I can't reproduce this neither on zsh 5.7.1 nor zsh 5.6.1 via the official docker image. Are you sure you're using the same zsh to run the script? Add `echo $ZSH_VERSION` to the script to make sure.

Either way, this should be an upstream bug, so I'm closing this (Zsh bugs should be reported to the [Zsh mailing list](http://zsh.org/mla)).

**Closed by mcornella** 2019-11-14 17:21 UTC

**Comment by mcornella** [comment] 2019-11-14 17:28
I can't actually reproduce this even in 4.3.11, so either there's something wrong with your zsh installation or you're running it on another shell other than zsh.
