### ISSUE TITLE
.oh-my-zsh/oh-my-zsh.sh:42: parse error near `||'

### ISSUE THREAD

**Issue by sinlov** [robbyrussell/oh-my-zsh#4871] opened 2016-02-23 03:54 UTC
38 is_plugin() {
 39   local base_dir=$1
 40   local name=$2
 41   test -f $base_dir/plugins/$name/$name.plugin.zsh \
 42     || test -f $base_dir/plugins/$name/_$name
 43 }

zsh 5.2 (x86_64-apple-darwin14.5.0)

**Comment by mcornella** [comment] 2016-02-23 09:05
Duplicate of #4870

**Closed by mcornella** 2016-02-23 09:05 UTC

**Comment by sinlov** [comment] 2016-02-23 09:56
Thanks
