### ISSUE TITLE
Error message when logging in from a tty

### ISSUE THREAD

**Issue by Ljle** [robbyrussell/oh-my-zsh#3425] opened 2014-12-18 23:08 UTC
I have a working oh-my-zsh setup in my Arch Linux machine (default config, I only added some aliases for pacman and other programs), but every time I log in from a **tty** I get the following error message:

![image](https://cloud.githubusercontent.com/assets/696474/5497389/fff632ac-8708-11e4-9778-0e34cc73aedd.png)

**Comment by jamietanna** [comment] 2015-01-12 14:25
Hi @Ljle, I can't seem to reproduce - I'm running a clean Arch install in a VM, and have installed oh-my-zsh to a new user. On login, I see no such error. Have you made any changes to zsh profiles i.e. `/etc/zprofile`, `/etc/zshrc` ?

**Comment by mcornella** [comment] 2015-01-13 13:40
Check if your `git config core.autoclrf` returns anything. If it does, delete it with `git config --unset core.autoclrf` and reinstall oh-my-zsh

**Comment by Ljle** [comment] 2015-01-14 01:56
Hi @jamietanna, @mcornella. I just realized it was the theme I was using **[(gnzh)](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes#gnzh)**. I checked it and It has some improper syntax quite similar to [this](https://bbs.archlinux.org/viewtopic.php?id=104080) post in the Arch Linux forums.
I changed my theme and I don't get the error anymore.

**Comment by jamietanna** [comment] 2015-01-14 10:30
Issue has been found at [L13](https://github.com/robbyrussell/oh-my-zsh/blob/c78277fd8bda5fec87504469afdf121355876006/themes/gnzh.zsh-theme#L13). It seems that the quoting is the issue, as replacing the double quote with a single quote (`s/'/"/g`) seems to resolve the error.

As you can see below, the difference in the TTY is noticeable - the blue text has disappeared, but it does not *seem* to have any difference when running in X. (Tested on BSPWM, running stock xterm).

Patch is as follows:
```
-eval PR_NO_COLOR="%{$terminfo[sgr0]%}"
+eval PR_NO_COLOR='%{$terminfo[sgr0]%}'
```

@mcornella shall I create a PR for this?

Before:
![before-tty](https://cloud.githubusercontent.com/assets/3315059/5737328/70e52cb0-9bd7-11e4-81ee-ae2cddf1400f.png)
![before-x](https://cloud.githubusercontent.com/assets/3315059/5737331/70ed8964-9bd7-11e4-8478-bcdad3de2a86.png)

After:
![after-tty](https://cloud.githubusercontent.com/assets/3315059/5737329/70e9165e-9bd7-11e4-8b83-ffbe0f5789db.png)
![after-x](https://cloud.githubusercontent.com/assets/3315059/5737330/70ebed02-9bd7-11e4-9384-1a2bfd25739d.png)

**Comment by Ljle** [comment] 2015-01-14 21:11
I tried that @jamietanna, but even after modifying it I still get the error.

![rsz_2015-01-14-162623_1440x900_scrot](https://cloud.githubusercontent.com/assets/696474/5747525/896a03a6-9c30-11e4-9055-ec482a40b599.jpg)

![rsz_fb0](https://cloud.githubusercontent.com/assets/696474/5747637/7053dce2-9c31-11e4-94b7-1a9c9d4ca65e.jpg)

**Comment by mcornella** [comment] 2015-01-14 21:39
You can try running zsh in debug mode to see which line is responsible. That said, I'd get rid of all those pesky evals :joy:

**Comment by apjanke** [comment] 2015-02-18 15:07
This sounds like it might be dependent on the particular terminal emulator you're running. I.e. those syntax errors look like they happen when the terminfo db doesn't have an entry for `sgr0` or `bold`, and referencing them collapses to an empty string, 

What terminal emulators are you folks running these in?

If this is in fact the issue, the theme could probably be fixed up using variable defaulting instead of `eval` protection to produce an empty or fallback string for unsupported term capabilities.

**Comment by Ljle** [comment] 2015-02-18 15:45
I'm running [rxvt-unicode](https://wiki.archlinux.org/index.php/rxvt-unicode).

**Comment by apjanke** [comment] 2015-02-18 18:44
Okay. Can you paste the output you get for the following commands?

    echo $TERM
    echo ${#terminfo[sgr0]}
    echo ${#terminfo[bold]}

**Comment by Ljle** [comment] 2015-02-18 19:25
![image](https://cloud.githubusercontent.com/assets/696474/6254886/153d77e2-b77e-11e4-99ad-e7c42ee2909c.png)

**Comment by mcornella** [comment] 2015-02-19 14:33
Ok let's use the bazooka (`matar moscas a cañonazos`) to get rid of this bug: you have to run zsh in debug mode and post the output. Here's how you do it:
```
zsh -xvi -c 'exit' &>~/zsh-debug.log
```
then post the `zsh-debug.log` file in a [gist](https://gist.github.com) and post the URL here.

**Comment by apjanke** [comment] 2015-02-19 16:19
I can reproduce now. It's in the eval that @jamietanna identifies, all right. I think the cause is that `eval` is breaking the double-quote protection, which is an issue if the terminfo entry contains special characters wrt zsh syntax. And the `linux` virtual console `sgr0` entry does (but xterm or rxvt entries don't). (Maybe ljle had an issue when testing the quoting fix?)

On Fedora 21, if I set the theme to `gnzh` and log in on a virtual console, I see the exact behavior in the original question. There's a`(eval):1: parse error near '}'` error, and then too much blue text. I'm matching the behavior of the other posters where the console login prompt stays blue for the second login.

![screen shot 2015-02-19 at 10 32 04 am](https://cloud.githubusercontent.com/assets/2618447/6269698/fa6fca1e-b822-11e4-8488-742dd874eebc.png)

![screen shot 2015-02-19 at 10 36 04 am](https://cloud.githubusercontent.com/assets/2618447/6269736/30f5748a-b823-11e4-821a-da31c20b13bd.png)

I think the problem is that the `sgr0` terminfo entry for the `linux` virtual console terminal has a semicolon in it, and the `eval` is breaking the quote protection it needs.

    ╰─➤  infocmp -1 linux | grep sgr0
    	sgr0=\E[0;10m,

As a result, `PR_NO_COLOR` doesn't get set, and the text color doesn't get reset to default after the last time it's set to blue in the prompt.

I can get a syntax issue if I manually construct a similar variable using that terminfo entry.
```shell
 ~  foo="%{\E[0;10m,}%"
 ~  eval foo="%{\E[0;10m,}%"
zsh: command not found: 10m,}%
 ~
```

If I remove the `eval` before PR_NO_COLOR on line 12, it works: no syntax error, and no extra blue text. Changing the double quotes to single quotes like @jamietanna there also works; don't know why it didn't for @Ljle.  (That `nano` screenshot shows an unsaved file... maybe it didn't get saved before you logged in on a console again?)

I think the only reason for any of these `eval`s is that loop that uses `PR_$color=...` to dynamically compute variable names. We can probably just remove the rest of them. If I remove them and switch the single quotes to double quotes (so substitution happens at the same time as under eval + single quotes), the theme works fine for me. And I think that's a more robust approach: it'll be less sensitive to the content of terminfo entries, and more readable. (With `eval` and single quotes, if a terminfo entry contains a single quote, that'll break.)

**Comment by mcornella** [comment] 2015-07-01 11:45
Hi, did we ever implement a fix for this?

**Comment by apjanke** [comment] 2015-07-01 13:06
Not that I can see, but I can knock one out today. (I'll pull in the commit from #2052 as well if those changes would need to be revised to match the fix.)

**Comment by apjanke** [comment] 2015-07-01 15:17
Okay, I've put in a fix. #4113

That PR changes a lot of lines, because there was kind of a tangle of eager vs. lazy evaluation issues in there that led up to the `eval` in the first place. This straightens them out by switching everything to a) eager evaluation (`local` vars with `"..."` double-quote strings) for the prompt string construction, and b) lazy evaluation (regular `zsh` `%F`/`%f` [prompt escapes](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Visual-effects)) for the terminal escape sequences.

I've tested on Windows, Debian 7 Linux, and OS X 10.9, with various terminal emulators.

This should take care of the `eval`-related error messages. But it may not clear up all the issues folks on this thread are having – I found recently that some Linux distributions may have bad `terminfo` entries for `rxvt-unicode` (see #2750), so `urxvt` users may still have some cosmetic problems. If so, note it here or on #2750 and we'll try to iron that out, too. (Or you may just be using a font that doesn't have glyphs for the special characters `gnzh` uses; nothing to be done there.)

**Closed** 2015-09-19 15:53 UTC
